// AUTO-GENERADO desde "Depreciacion.xlsx" (hoja "Centro de Produccion").
// Depreciacion Mensual PERC: 44 centros de produccion. "areas" es fijo (solo lectura);
// "Depreciacion mensual" se captura por mes y arranca en 0 cada mes nuevo.
export type DepreRow = { centro: string; areas: string };
export const DEPRECIACION_ROWS: DepreRow[] = [
  { centro: "66-Hospitalizacion medicina interna", areas: "Hospitalizacion Medicina Mujeres Hospitalizacion Medicina Mujeres 2 Hospitalizacion Medicina Mujeres 3 Hospitalizacion Medicina Hombres Hospitalizacion Medicina Hombres 2 Hospitalizacion Medicina Hombres 3 Hospitalizacion Medicina Aislados" },
  { centro: "95-Hospitalizacion cirugia general", areas: "Hospitalizacion Cirugia Mujeres Hospitalizacion Cirugia Hombres Neurocirugia" },
  { centro: "745-Hospitalizacion servicios por convenios", areas: "Unidad de convenios Hospitalizacion convenios UCI convenios UCINT convenios" },
  { centro: "166-Unidad de cuidados intensivos", areas: "Todas las UCIS (menos UCI Convenios)" },
  { centro: "179-Unidad de cuidados intermedios", areas: "Todas los Intermedios  (menos UCINT Convenios)" },
  { centro: "201-Emergencias", areas: "Unidad de Admisiones Unidad de evaluacon y observacion medica" },
  { centro: "743-Clinica empresarial", areas: "Clinica de empleados" },
  { centro: "806-Centro quirurgico", areas: "Centro quirurgico Y Anestesiologia" },
  { centro: "767-Unidad de cuidados especiales", areas: "Hospitalizacion y oficinas de Cuidados paliativos" },
  { centro: "766-Servicio de apoyo a riiss", areas: "Servicio de apoyo a riiss" },
  { centro: "398-Vacunacion", areas: "Vacunacion" },
  { centro: "518-Laboratorio clinico", areas: "Laboratorio clinico" },
  { centro: "530-Laboratorio de biologia molecular", areas: "Laboratorio de biologia molecular" },
  { centro: "538-Resonancia magnetica", areas: "Resonancia magnetica" },
  { centro: "541-Tomografia", areas: "Tomografia" },
  { centro: "791-Estudio de radiologia", areas: "Estudio de radiologia" },
  { centro: "559-Ultrasonografia", areas: "Ultrasonografia" },
  { centro: "776-Estudios gastroclinicos", areas: "Area de procedimientos medicos (Antiguo quirofano?)" },
  { centro: "562-Terapia fisica", areas: "Servicio de fisioteraía" },
  { centro: "566-Terapia respiratoria", areas: "Terapia respiratoria" },
  { centro: "570-Rehabilitacion pulmonar", areas: "Rehabilitacion pulmonar" },
  { centro: "575-Banco de sangre", areas: "Banco de sangre" },
  { centro: "579-Unidad de hemodinamia", areas: "Unidad de Terapia Intervencionista Endovascular" },
  { centro: "268-Hemodialisis", areas: "Unidad de Terapia Extracorporea" },
  { centro: "593-Servicio farmaceutico", areas: "Servicio farmaceutico" },
  { centro: "803-Rehablitacion psicosocial", areas: "Psicologia" },
  { centro: "750-Alimentacion enteral", areas: "Alimentacion enteral" },
  { centro: "760-Nutricion parenteral", areas: "Nutricion parenteral" },
  { centro: "662-Central de esterilizacion", areas: "Central de esterilizacion" },
  { centro: "761-Saneamiento ambiental", areas: "Saneamiento ambiental" },
  { centro: "648-Aseo", areas: "Servicios Generales" },
  { centro: "721-Almacen", areas: "Almacen de insumos medicos Almacen de medicamento Almacen de suministros generales" },
  { centro: "652-Servicio de alimentacion", areas: "Servicio de alimentacion" },
  { centro: "659-Lavanderia", areas: "Lavanderia" },
  { centro: "664-Transporte general", areas: "Transporte general" },
  { centro: "665-Mantenimiento", areas: "Mantenimiento Activo Fijo" },
  { centro: "713-Trabajo social", areas: "Trabajo social" },
  { centro: "702-Docencia e investigacion", areas: "Unidad de Desarrollo Profesional" },
  { centro: "670-Administracion", areas: "ESDOMED Informatica Recursos Humanos Unidad Financiera UCP Planificacion y calidad Unidad juridica División medica Auditoria Interna División de diagnostico Enfermeria Direccion Sub Direccion Sub Direccion Administrativa Departamento de Cirugia Comunicaciones Unidad de Epidemiologia Comité de salud y seguridad Dpto de Medicina Critica Dpto de Medicina Preventiva Dpto de Medicina Interna Unidad de Asesoria de Medicamentos Unidad de Cumplimiento Unidad de Gestion Documental Area de Monitoreo y comedor Gestion Documental" },
  { centro: "Cardiologia", areas: "Hospitalizacion cardiologia" },
  { centro: "DPI", areas: "Hospitalizacion Nefrologia" },
  { centro: "Hemato Onco", areas: "Hospitalizacion Hematologia Hospitalizacion Oncologia" },
  { centro: "Quimioterapia ambulatoria", areas: "Hospitalizacion Quimioterapia ambulatoria (Pasillo despues de Convenios)" },
  { centro: "Centro de Telemedicina (DoctorSV)", areas: "Megacentro de vacunacion" },
];
