// AUTO-GENERADO desde "GASTOS.xlsx" (hoja "Distribucion Gasto General").
// Matriz de Gastos PERC: 34 categorias de gasto (columnas) x 39 centros de costo
// (filas). Fila especial "Tipo de Distribucion" (1-4) por categoria. Mensual.
export type GastoExpense = { header: string; tipo: number };
export const GASTOS_EXPENSES: GastoExpense[] = [
  { header: "249-Alumbrado publico", tipo: 4 },
  { header: "250-Arrendamientos inmobiliarios", tipo: 4 },
  { header: "251-Arrendamientos mobiliarios", tipo: 4 },
  { header: "209-Arrendamientos y derechos de bienes intangibles", tipo: 4 },
  { header: "214-Consultorias, estudios e investigaciones diversas", tipo: 4 },
  { header: "88-Depreciaciones y amortizaciones", tipo: 4 },
  { header: "105-Gastos en activos intangibles", tipo: 4 },
  { header: "118-Impuestos, tasas y derechos", tipo: 4 },
  { header: "252-Instalaciones hoteleras, alojamiento y convenciones", tipo: 4 },
  { header: "129-Mantenimiento equipo de computo", tipo: 4 },
  { header: "253-Mantenimiento y reparacion de inmuebles administrativos", tipo: 4 },
  { header: "254-Mantenimiento y reparacion de inmuebles de salud", tipo: 4 },
  { header: "255-Mantenimiento y reparacion de inmuebles diversos", tipo: 4 },
  { header: "256-Mantenimiento y reparacion de mobiliarios y equipos diversos", tipo: 4 },
  { header: "135-Mantenimiento y reparacion de vehiculos", tipo: 4 },
  { header: "140-Maquinaria y equipo", tipo: 4 },
  { header: "145-Otros gastos generales", tipo: 4 },
  { header: "148-Otros servicios y arrendamientos diversos", tipo: 4 },
  { header: "150-Pasajes y viaticos", tipo: 4 },
  { header: "158-Publicidad y propaganda", tipo: 4 },
  { header: "48-Servicio de agua", tipo: 2 },
  { header: "169-Servicio de alimentacion", tipo: 4 },
  { header: "92-Servicio de energia", tipo: 2 },
  { header: "258-Servicio de fumigacion y control de plagas", tipo: 4 },
  { header: "259-Servicio de impresiones, publicaciones y reproducciones", tipo: 4 },
  { header: "177-Servicio de laboratorio", tipo: 4 },
  { header: "205-Servicio de lavanderia y planchado", tipo: 4 },
  { header: "179-Servicio de mensajeria y/o correo", tipo: 4 },
  { header: "192-Servicio de telecomunicaciones", tipo: 3 },
  { header: "257-Servicio de transporte y manejo de carga", tipo: 4 },
  { header: "182-Servicio de vigilancia y seguridad", tipo: 4 },
  { header: "260-Servicios de inspeccion", tipo: 4 },
  { header: "261-Servicios de limpieza y tratamiento de desechos", tipo: 1 },
  { header: "262-Servicios financieros", tipo: 4 },
];
export const GASTOS_COST_CENTERS: string[] = [
  "66-Hospitalizacion medicina interna",
  "95-Hospitalizacion cirugia general",
  "745-Hospitalizacion servicios por convenios",
  "166-Unidad de cuidados intensivos",
  "179-Unidad de cuidados intermedios",
  "201-Emergencias",
  "743-Clinica empresarial",
  "806-Centro quirurgico",
  "767-Unidad de cuidados especiales",
  "766-Servicio de apoyo a riiss",
  "398-Vacunacion",
  "518-Laboratorio clinico",
  "530-Laboratorio de biologia molecular",
  "538-Resonancia magnetica",
  "541-Tomografia",
  "791-Estudio de radiologia",
  "559-Ultrasonografia",
  "776-Estudios gastroclinicos",
  "562-Terapia fisica",
  "566-Terapia respiratoria",
  "570-Rehabilitacion pulmonar",
  "575-Banco de sangre",
  "579-Unidad de hemodinamia",
  "268-Hemodialisis",
  "593-Servicio farmaceutico",
  "803-Rehablitacion psicosocial",
  "750-Alimentacion enteral",
  "760-Nutricion parenteral",
  "662-Central de esterilizacion",
  "761-Saneamiento ambiental",
  "648-Aseo",
  "721-Almacen",
  "652-Servicio de alimentacion",
  "659-Lavanderia",
  "664-Transporte general",
  "665-Mantenimiento",
  "713-Trabajo social",
  "670-Administracion",
  "702-Docencia e investigacion",
];
