// AUTO-GENERADO (formato Distribucion de Horas: empleados x centros de costo).
// Mismo formato para todas las areas; cambian las columnas (centros) y empleados.
/** Empleado sembrado: solo nombre, o nombre + DUI (documento de identidad). */
export type HorasSeed = string | { name: string; dui?: string };

export type HorasTemplate = {
  serviceId: string;
  establishment: string;
  /** Centros de costo a los que el area distribuye horas (columnas). */
  columns: string[];
  /** Empleados iniciales (editable: se pueden agregar/quitar). */
  seedEmployees: HorasSeed[];
};

export const HORAS_TEMPLATES: Record<string, HorasTemplate> = {
  esdomed: {
    serviceId: "esdomed",
    establishment: "HOSPITAL NACIONAL EL SALVADOR",
    columns: ["ADMINISTRACION"],
    seedEmployees: [
      { dui: "03596842-9", name: "HEBER BENJAMIN CARDOZA GUEVARA" },
      { dui: "01658710-9", name: "BORIS ANDREE RODRIGUEZ QUINTANILLA" },
      { dui: "03676985-2", name: "JUAN CARLOS MIRANDA MARROQUIN" },
      { dui: "04505539-1", name: "JOSE DANIEL HERNANDEZ ZEPEDA" },
      { dui: "05760583-5", name: "VINICIO ALEXANDER HERNANDEZ QUIJANO" },
      { dui: "04304339-8", name: "ALFONSO MONTES GUTIERREZ" },
      { dui: "05060484-6", name: "DENYS RICARDO ALVAREZ SORTO" },
      { dui: "03598713-0", name: "DIEGO IVAN LOPEZ" },
      { dui: "05548384-7", name: "FERNANDO JAVIER GALVEZ SAMPSON" },
      { dui: "02430226-2", name: "PILAR DEL CARMEN CANDRAY AMAYA" },
      { dui: "00529335-7", name: "HENRY OMAR MACIAS BARRIENTOS" },
      { dui: "04800141-4", name: "BRENDA MARGARITA RAMIREZ OVIEDO" },
      { dui: "05837047-5", name: "LUIS FERNANDO AMAYA GRANDE" },
      { dui: "03231178-8", name: "BILLIE NAPOLEON CRUZ GARCIA" },
      { dui: "02989402-8", name: "CARLOS RODIL SALEGIO SALINAS" },
      { dui: "05080791-5", name: "VANESSA FABIOLA NAVES LARIN" },
      { dui: "05298662-6", name: "GABRIELA ALEJANDRA CALPAÑO RODRIGUEZ" },
      { dui: "03614327-6", name: "CARLA SOFIA GIRON CERNA" },
      { dui: "03979953-9", name: "OSCAR ALEXANDER GUARDADO GUEVARA" },
      { dui: "05649041-5", name: "VIOLETA SARAI CASTRO ORELLANA" },
      { dui: "04297389-1", name: "VANESSA TATIANA HERRERA ALAS" },
      { dui: "03532673-2", name: "BARTIMEO OLIVERIO LOPEZ PICHINTE" },
      { dui: "01980666-7", name: "CARLOS ABRAHAM MONTOYA ARROYO" },
      { dui: "05258503-0", name: "KARLA ALEJANDRA GARCIA DIAZ" },
      { dui: "06656459-1", name: "BEATRIZ ALEJANDRA BARRERA DE VASQUEZ" },
      { dui: "05513800-2", name: "ANDREA GABRIELA FLORES MANGANDI" },
      { dui: "06342595-0", name: "ALEJANDRO GABRIEL HERNANDEZ HERRERA" },
    ],
  },
  "asesores-de-medicamentos": {
    serviceId: "asesores-de-medicamentos",
    establishment: "HOSPITAL NACIONAL EL SALVADOR",
    columns: ["ADMINISTRACION"],
    seedEmployees: [
      { dui: "04148240-7", name: "Ana Lydia Moran Morales" },
      { dui: "04061675-2", name: "Fernando Ernesto Preza Franco" },
      { dui: "02149231-9", name: "César Guillermo Cartagena Benítez" },
    ],
  },
  "trabajo-social": {
    serviceId: "trabajo-social",
    establishment: "HOSPITAL NACIONAL EL SALVADOR",
    columns: ["TRABAJO SOCIAL", "SERVICIO DE APOYO A RIISS", "ADMINISTRACION"],
    seedEmployees: [
      { dui: "04203005-9", name: "Brenda Patricia Mejia Ramírez" },
      { dui: "05366636-8", name: "Erika Eloisa Gonzalez Rodriguez" },
      { dui: "04282005-6", name: "Marcela Anabel Ramirez Siciliano" },
      { dui: "04085907-5", name: "Ricardo Balmore Santos Diaz" },
      { dui: "03919231-3", name: "Sandra Guadalupe Vasquez Bolaños" },
      { dui: "04270017-5", name: "Maria Beatriz Santamaria Pocasangre" },
      { dui: "04042197-9", name: "Claudia Yanira Ayala de Palacios" },
      { dui: "06754264-9", name: "Versy Yalem Bejarano Vargas" },
      { dui: "00686492-3", name: "Raquel Betzabe Acosta De Canjura" },
      { dui: "03973540-4", name: "Carlos Francisco Vasquez" },
      { dui: "02780035-8", name: "Elena Maricela Zepeda" },
      { dui: "04291245-5", name: "Ana Veronica Villatoro Guzman" },
      { dui: "03755136-7", name: "Lissette Magaly Batres Barahona" },
      { dui: "04197776-1", name: "Kryssia Yesenia Ramírez Navarro" },
      "Febe Del Carmen Fuentes Moreno (Servicios Profesionales)",
      "Jennifer Celestina Romero Rivas (Servicios Profesionales)",
      "Madelyn Yacira Ruiz Urbina (Servicios Profesionales)",
      "Susana Beatriz Crespin Gonzalez (Servicios Profesionales)",
      { dui: "06393203-8", name: "KATERIN BEATRIZ MARTÍNEZ MACHADO" },
      { dui: "04652189-0", name: "KARLA JASSMIN SANCHEZ RAMIREZ" },
      { dui: "06514743-5", name: "GUIZEL ESMERALDA MUÑOZ ACOSTA" },
      { dui: "03148537-2", name: "SAMUEL ERNESTO CONTRERAS VALENCIA" },
      { dui: "05195221-8", name: "LUCIA ESPERANZA MARTÍNEZ MUÑOZ" },
      { dui: "02356120-3", name: "JACQUELINE LISSETTE ACEVEDO DE ALVARENGA" },
      { dui: "01136653-2", name: "FREDDY ALEXIS HERRERA LOPEZ" },
      { dui: "05075758-4", name: "JOHANA ELIZABETH HENRRIQUEZ LEÓN" },
    ],
  },
  planificacion: {
    serviceId: "planificacion",
    establishment: "HOSPITAL NACIONAL EL SALVADOR",
    columns: ["ADMINISTRACION"],
    seedEmployees: [
      { dui: "02597708-6", name: "JOSE ROBERTO CENTENO ZAMBRANO" },
      { dui: "04320030-6", name: "DAVID ERNESTO ARTEAGA AGUILAR" },
      { dui: "01750504-5", name: "FLOR DE MARIA FUENTES URBINA" },
      { dui: "04563791-5", name: "FRANCISCO OVIDIO COLORADO RIVERA" },
    ],
  },
  epidemiologia: {
    serviceId: "epidemiologia",
    establishment: "HOSPITAL NACIONAL EL SALVADOR",
    columns: ["ADMINISTRACION"],
    seedEmployees: [
      { dui: "02479331-6", name: "Irma Elena Lopéz de Sanchez" },
      { dui: "01725078-9", name: "Jorge Alexis Henriquez" },
      { dui: "00198564-3", name: "Carlos Espinoza Lazo" },
      "William Francisco Huezo Vasquez",
      { dui: "04850600-8", name: "Angela Alejandra Molina Duque" },
    ],
  },
  cumplimiento: {
    serviceId: "cumplimiento",
    establishment: "HOSPITAL NACIONAL EL SALVADOR",
    columns: ["ADMINISTRACION"],
    seedEmployees: [
      { dui: "05423566-5", name: "Yaquelin Elizabeth Hernández Martinez" },
      { dui: "04255755-6", name: "Esmeralda del Carmen Mártir Rojas" },
    ],
  },
  "auditoria-interna": {
    serviceId: "auditoria-interna",
    establishment: "HOSPITAL NACIONAL EL SALVADOR",
    columns: ["ADMINISTRACION"],
    seedEmployees: [
      { dui: "05083293-6", name: "Mirna Liseth Martínez Molina" },
      { dui: "01140719-2", name: "Edwin Alexander Calzadilla Hernández" },
      { dui: "01103443-6", name: "Carlos Alexander Quiñónez Monroy" },
      { dui: "05745786-8", name: "KISSEIMA MARCELA RIVERA AMAYA" },
    ],
  },
  "unidad-financiera": {
    serviceId: "unidad-financiera",
    establishment: "HOSPITAL NACIONAL EL SALVADOR",
    columns: ["ADMINISTRACION"],
    seedEmployees: [
      { dui: "02068270-9", name: "René Alexander Fuentes Fuentes" },
      { dui: "00785271-7", name: "Deysi Esmeralda Olmedo Diaz" },
      { dui: "00635886-7", name: "Beatriz Cecilia Garcia" },
      { dui: "04533160-8", name: "Erick Arnoldo Guzman Perez" },
      { dui: "00124189-5", name: "Miguel Angel Solis Rivera" },
      "Oscar Humberto Pineda Escobar",
      { dui: "03843461-5", name: "Roberto Antonio Arevalo Galan" },
      { dui: "02325723-6", name: "Manuel Enrique Amaya Perez" },
      { dui: "06434577-1", name: "KATHERINE MELISSA CARCAMO ARGUMEDO" },
      { dui: "04295155-6", name: "ISAAC VLADIMIR REYES GUTIERREZ" },
      { dui: "05574197-8", name: "CARMEN ELENA TOBAR ALVARENGA" },
      { dui: "04160876-0", name: "JACQUELINE ROXANA RIVERA ECHEGOYEN" },
      { dui: "03559327-4", name: "HEYZELL ASTRID RUIZ" },
      { dui: "05127954-7", name: "GERSON ADALBERTO RAMIREZ MENJIVAR" },
      { dui: "05822615-5", name: "GABRIELA ELIZABETH PEÑA MANCIA" },
      { dui: "04801027-7", name: "RUTH ELIZABETH MENDEZ MIRA" },
    ],
  },
  "unidad-juridica": {
    serviceId: "unidad-juridica",
    establishment: "HOSPITAL NACIONAL EL SALVADOR",
    columns: ["ADMINISTRACION"],
    seedEmployees: [
      { dui: "01701606-2", name: "Romel Morales Ruiz" },
      { dui: "05064375-1", name: "Jacqueline Carolina Castro Vasquez" },
      { dui: "05178787-5", name: "Vanessa Alexandra Deras Mejia" },
      { dui: "02393572-9", name: "Jorge Alberto Portillo Colato" },
      { dui: "03633584-9", name: "Jose Alfonso Cisneros de Leon" },
      "Adriana Michelle Rivera Serrano",
    ],
  },
  comunicaciones: {
    serviceId: "comunicaciones",
    establishment: "HOSPITAL NACIONAL EL SALVADOR",
    columns: ["ADMINISTRACION"],
    seedEmployees: [
      { dui: "05622550-1", name: "Karla Vanessa Linares Flores" },
    ],
  },
  "almacen-medicamentos": {
    serviceId: "almacen-medicamentos",
    establishment: "HOSPITAL NACIONAL EL SALVADOR",
    columns: ["ADMINISTRACION"],
    seedEmployees: [
      { dui: "00046027-6", name: "Oscar Ernesto Gutierrez Caceres" },
      { dui: "02879836-8", name: "Oscar Stanley Cruz Reyes" },
      { dui: "05042600-2", name: "Mario Adilio Magaña Valenzuela" },
      { dui: "05042580-2", name: "Luis Alberto Garcia Zelaya" },
    ],
  },
  "unidad-de-convenios": {
    serviceId: "unidad-de-convenios",
    establishment: "HOSPITAL NACIONAL EL SALVADOR",
    columns: ["HOSPITALIZACION SERVICIOS POR CONVENIOS", "ADMINISTRACION"],
    seedEmployees: [
      { dui: "04212344-6", name: "NATALY RAQUEL VARELA RAMOS" },
      { dui: "02708901-7", name: "NATALIA CAROLINA AVELAR DE DURAN" },
      { dui: "03417811-0", name: "KAREN LISSETTE GARCIA RODRIGUEZ" },
      { dui: "04340274-6", name: "DANIEL ALEJANDRO CENTENO ALVAREZ" },
      { dui: "05521455-7", name: "NICOLLE ALEXANDRA MELENDEZ GALLARDO" },
      { dui: "04582002-1", name: "EVELIN YAMILETH MARTIR ROJAS" },
      { dui: "00943940-0", name: "RHINA LIZZETTE PACHECO ARGUETA" },
      { dui: "03718624-3", name: "JESSICA LOPEZ LOPEZ" },
      { dui: "02576910-8", name: "EMELY OFELIA RAMIREZ DE CASTRO" },
      { dui: "00212842-2", name: "ROBERTO RAMIREZ GIRON" },
      { dui: "03925120-6", name: "SORAYA GUADALUPE GRANDE TEODORO" },
    ],
  },
  "jefaturas-division-medica": {
    serviceId: "jefaturas-division-medica",
    establishment: "HOSPITAL NACIONAL EL SALVADOR",
    columns: [
      "HOSPITALIZACION MEDICINA INTERNA",
      "SERVICIOS DE APOYO A LA RISS",
      "ADMINISTRACION",
    ],
    seedEmployees: [
      { dui: "00640749-6", name: "WERNER STANLEY POSADA SORIANO" },
      { dui: "04260303-0", name: "ROSAURA PATRICIA VALENCIA ROSALES" },
      { dui: "00658452-3", name: "DANIELA ALEXANDER MONROY MARTINEZ" },
      { dui: "01629135-0", name: "CARLOS FABRICIO ALVARENGA ALVARENGA" },
      { dui: "04198426-3", name: "JOSE EDUARDO MALDONADO MADRID" },
      { dui: "00658452-3", name: "HECTOR MARIO MONJARAS QUEZADA" },
      { dui: "04586381-7", name: "LUCIA MERCEDES SANDOVAL CARCAMO" },
      "— MEDICOS DESTACADOS —",
      "ERICK DANIEL BONILLA SALOMON",
      "RUBEN FRANCISCO AGUILAR CARDONA",
      "LUIS MARIO CAMPOS ROSALES",
      "DOUGLAS DANIEL LUE RIVERA",
      "CLAUDIA CAROLINA ALVARADO TORRES",
      "JUAN JOSE AVALOS",
      "ALVARO ENRIQUE TORRES ALEGRIA",
      "WALFRED CASTRO AGUILAR",
      "LISSETH BEATRIZ VASQUEZ IGLESIAS",
      "WILLIAM EDUARDO CASTRO MORAN",
      "ALBA YANIRA CATACHO ARTEAGA",
      "MARITZA ELIZABETH PINO JAIMES",
      "FERMIN ELI MONTERROSA LOPEZ",
      "BLANCA LUZ ARTIGA RIVERA",
      "JESSIE CONCEPCION RAMOS PONCE",
      "ROSA AMELIA GUILLEN LANDAVERDE",
      "FRANCISCO ANTONIO LINARES GARCIA",
      "MAYA XOCHITL MELGAR DE MARTINEZ",
      "IRIS MARLENE OLANO",
      "ERIKA YAMILETH DE LEON HENRIQUEZ",
      "DENYS ROBERTO ORTIZ CASTILLO",
      "ASTRID MARGARITA MARTINEZ FIGUEROA",
      "MARCELA FLORITA ARGUETA SOLORZANO",
      "ANA GUADALUPE TORRES GONZALEZ",
      "HOWARD JOSE GALEAS VELASQUEZ",
      "ANA BELGICA MUÑOZ DE FRAILE",
      "JUAN FRANCISCO VANEGAS CASTILLO",
      "HENRRY JOSUE MOLINA CALZADA",
      "JOSE LUIS BONILLA GOMEZ",
      "SILVIA ENCARNACION ALFARO",
      "MAYNOR DELMO ERAZO PALENCIA",
      "RAFAEL JOSE GALVEZ ZECEÑA",
      "MARIA FERNANDA ROSALES HERRERA",
      "CLAUDIA MARIA RUIZ RUANO",
      "MILAGRO ELIZABETH BLANCO RAMOS",
      "ENA MERCEDES ALFARO PORTILLO",
      "EVA YAMILETH SALAS TORRES",
      "AARON ERNESTO GARCIA AMAYA",
      "CATHERINE ELIZABETH RIVAS DE SANCHEZ",
      "TATIANA YAMILETH VASQUEZ CERON",
      "LOURDES LISSETH CABRERA CRUZ",
      "ELIDA LISETH ZELAYA LOPEZ",
      "OLGA ESTHER FLORES GONZALEZ",
      "SANTA MARIA REINA ELIZABETH RAMIREZ GONZALEZ",
      "XAVIER ALEXIS MERINO CALDERON",
      "SAMUEL DE JESUS CHEVEZ SANCHEZ",
      "KAREN ABIGAIL QUINTANILLA DE CAMPOS",
      "JOHAO ALEJANDRO GONZALEZ SANTOS",
    ],
  },
  "jefatura-division-apoyo": {
    serviceId: "jefatura-division-apoyo",
    establishment: "HOSPITAL NACIONAL EL SALVADOR",
    columns: ["ADMINISTRACION"],
    seedEmployees: [
      { dui: "01658539-3", name: "Juan Manuel Ayala Lazo" },
      { dui: "00254687-4", name: "Ana Patricia Orellana de Figueroa" },
      { dui: "02869798-6", name: "Blanca Margarita Coto Navarrete" },
    ],
  },
  udp: {
    serviceId: "udp",
    establishment: "HOSPITAL NACIONAL EL SALVADOR",
    columns: ["DOCENCIA E INVESTIGACION Y CAPACITACION"],
    seedEmployees: [
      { dui: "03286212-9", name: "Veronica Judith Molina Moran" },
      { dui: "00272513-5", name: "Zayra Geraldine Garcia Melendez" },
    ],
  },
  "servicio-farmaceutico": {
    serviceId: "servicio-farmaceutico",
    establishment: "HOSPITAL NACIONAL EL SALVADOR",
    columns: ["SERVICIO FARMACEUTICO", "ADMINISTRACION"],
    seedEmployees: [
      "Jesus Alberto Cardona Landaverde",
      { dui: "05042836-3", name: "Andrea Marcella Juarez Chiquillo" },
      { dui: "03690291-3", name: "Dennis Ericson Merino Hernandez" },
      { dui: "05653633-4", name: "Liliana Estefani Iraheta Hernandez" },
      { dui: "05640349-2", name: "Alvaro Ramon Martinez Vasquez" },
      "Mardoqueo Ismael Trejo Torrento",
      "Brayan Leonardo Gonzalez Salazar",
      "Carlos Melvin Sorto Caballero",
      "Ismenia Margarita Amaya Juarez",
      { dui: "04503900-2", name: "Jesus Alfredo Hernandez Torres" },
      "Manuel Antonio Ramos Romero",
      "Cecil Fernando Portillo Miranda",
      { dui: "04470630-5", name: "Cynthia Rebeca Carpio Marquez" },
      "Evelyn Elizabeth Arevalo Rodriguez",
      { dui: "05205086-5", name: "Josselyn Estefania Martinez Vasquez" },
      { dui: "04741755-7", name: "Katerin Leticia Moz Mejia" },
      "Kenya Lisseth Hernandez Villanueva",
      { dui: "04428602-0", name: "Lorena Patricia Mendez Acosta" },
      "Jose Roberto Claros Ramos",
      "Blanca Wendy Alicia Toledo Soriano",
      { dui: "05268846-4", name: "Orlando Antonio Canales Hernandez" },
      "Jessica Esmeralda Portillo Rodriguez",
      { dui: "03674836-9", name: "Karen Ivonne Johanna Castro de Mendez" },
      { dui: "05495274-6", name: "Brayan Francisco Posada Orellana" },
      { dui: "04481252-0", name: "Blanca Estela Hernandez Hernandez" },
      { dui: "05281067-1", name: "Osmin Enrique Reyes Martinez" },
      { dui: "05872056-5", name: "Fredy Alexis Mena Recinos" },
      "Carlos Enrique Acevedo Sorto",
      { dui: "05383669-6", name: "Lorena Rosemarie Tejada Iraheta" },
      { dui: "05157082-0", name: "Marta Aida Cuatro Escalante" },
      { dui: "04674406-6", name: "Ruth Eunice Gonzalez Garcia" },
      { dui: "05616998-3", name: "Reina Briseyda Menjivar Molina" },
      { dui: "04041163-1", name: "Maria de los Angeles Chavez de Alvarado" },
      { dui: "05085365-7", name: "Rodrigo Javier Coto Martinez" },
      { dui: "05022518-9", name: "Ana Andrea Galvez Campos" },
      { dui: "02681172-0", name: "Mario Roberto Valencia Meza" },
      { dui: "05167058-1", name: "Samuel Oswaldo Belloso Hernandez" },
      { dui: "05944447-1", name: "Cesar Alexander Argueta Martinez" },
      { dui: "05586963-7", name: "Fatima Sofia Sosa Flores" },
      "Monica Beatriz Romero Salinas",
      { dui: "04755868-8", name: "Daniel Emanuel Flores Amaya" },
      { dui: "04983126-0", name: "Erika Johana Martinez Ramos" },
      "Vanessa Alejandra Rivera de Martinez",
      { dui: "05539447-0", name: "Kathya Sofia Parada Siliezar" },
      { dui: "05237352-2", name: "Kevin Moises Flores Ayala" },
      "William Alexander Santiago Ortez",
      { dui: "05914108-1", name: "Andrea Marcela Cortez Palma" },
      { dui: "06278565-8", name: "Marvin Levi Chavez Arevalo" },
      "Daniel Antonio Vividor Ramos",
      { dui: "04037201-5", name: "Fernando Rafael Murillo Aguilar" },
      { dui: "05358647-9", name: "Maria Jose Lopez Abrego" },
      { dui: "05730559-0", name: "Fatima Elizabeth Cortez Valladares" },
      { dui: "05162967-9", name: "Jenny Estefany Lopez Montes" },
      { dui: "05634810-5", name: "Josue Isaac Jimenez Pineda" },
      { dui: "05378873-8", name: "Kathia Alexandra Ayala Ayala" },
      "Valeria Alejandra Portillo Monterrosa",
      { dui: "05201802-5", name: "Efrain Enrique Hernandez Figueroa" },
      "Oscar Alexander Rivas Rivas",
      { dui: "04444812-7", name: "Mayra Alejandra Bracety Torres" },
      "Blanca Edith Rivas Cubias",
      { dui: "04578509-3", name: "Yoselin Sosa Garcia" },
      { dui: "03989593-7", name: "Oscar Anderson Rivas Gonzalez" },
      { dui: "05008236-1", name: "Peter Jonas Ramos Cuellar" },
      { dui: "04312654-4", name: "Guillermo Alfredo Garcia Molina" },
      "Carlos Alfredo Ortiz Ortiz",
      "Carlos Eduardo Dueñas Lemus",
      "Kevin Fernando Diaz Ortiz",
      "Ricardo Rafael Carcamo Juarez",
      "Eugenia Elizabeth Magaña de Vasquez",
      "Keisy Sabina Ramos Cuellar",
      "Cristina Elizabeth Martinez Parada",
      "Claudia Stefany Sandoval de Cortez",
      "Katherine Vanessa Melara Perez",
      "Glenda Melany Ramos Roldan",
      "Yaneth del Pilar Lemus de Rodriguez",
    ],
  },
  "banco-de-sangre": {
    serviceId: "banco-de-sangre",
    establishment: "HOSPITAL NACIONAL EL SALVADOR",
    columns: ["BANCO DE SANGRE", "SERVICIO DE APOYO A RIISS", "ADMINISTRACION"],
    seedEmployees: [
      "DILSIA MARLENE CORNEJO ESTRADA",
      "CARLOS MAURICIO OSORIO ALVARADO",
      "SANDRA CECILIA SORIANO MARTINEZ",
      "JOHANNA GABRIELA ACEVEDO ESTRADA",
      "FATIMA RAQUEL FUENTES CLARA",
      "FRANCIS ALFREDO SEGURA CALDERON",
      "ALEJANDRA JOSE MONTERROSA ALEGRIA",
      "JEFFREY MANASES SOLIS SANCHEZ",
      "NORMA CAROLINA MIRANDA MARTINEZ",
      "TERESA CAROLINA MORAN HERNANDEZ",
      "VIRGINIA ESTER FERNANDEZ MEDINA",
      "HECTOR ADOLFO GONZALEZ LOPEZ",
      "EDWIN ALEXANDER FLORES GARCIA",
      "JEFERSON STEVE ANAYA LIZAMA",
      "LUIS ANGEL ESPAÑA CASTELLANOS",
      "LESLI LORENA ARELY MUNDO CANALES",
      "FRANCESA AMANDA YAZEL AYALA RODRIGUEZ",
      "EDWIN VLADIMIR ESCOBAR VILLALTA",
      "RANDAL GIOVANNI MARTINEZ RIVERA",
      "JUAN JOSE MURCIA LOPEZ",
    ],
  },
};

export function getHorasTemplate(serviceId: string | null | undefined): HorasTemplate | null {
  if (!serviceId) return null;
  return HORAS_TEMPLATES[serviceId] || null;
}

export function hasHorasTemplate(serviceId: string | null | undefined): boolean {
  return !!serviceId && serviceId in HORAS_TEMPLATES;
}

