// AUTO-GENERADO desde "INSUMOS ALMACEN 2026.xlsx".
// Matriz de costos: filas = centros de costo, columnas = categorias de insumo.
// Las sumas replican EXACTAMENTE las formulas del Excel (no se inventan):
//  - Filas padre (con `sumOf`) = suma por columna de sus filas hijas.
//  - "Total por producto" (por fila) = suma de las 31 columnas de esa fila.
//  - "Total por servicio" (fila final) = suma de TODAS las filas 2..97 por columna,
//    tal como la formula =SUM(C2:C97) del Excel (incluye padres e hijas).

export type InsumoColumn = { key: string; label: string };
export type InsumoRow = {
  key: string;
  /** Centro de costo (columna B del Excel). */
  label: string;
  /** Si es fila padre: por cada columna, suma estas filas hijas (keys). Solo lectura. */
  sumOf?: string[];
};
export type InsumosTemplate = {
  serviceId: string;
  establishment: string;
  columns: InsumoColumn[];
  rows: InsumoRow[];
  /** Etiqueta de la fila de total general (por columna). */
  grandTotalLabel: string;
  /** Etiqueta de la columna de total por fila. */
  rowTotalLabel: string;
};

export const INSUMOS_ALMACEN_TEMPLATE: InsumosTemplate = {
  serviceId: "almacen",
  establishment: "HOSPITAL NACIONAL EL SALVADOR",
  rowTotalLabel: "TOTAL POR PRODUCTO",
  grandTotalLabel: "TOTAL POR SERVICIO",
  columns: [
    { key: "c1", label: "3-Combustibles y lubricantes" },
    { key: "c2", label: "9-Gases medicinales" },
    { key: "c3", label: "15-Material de odontologia" },
    { key: "c4", label: "16-Material de osteosintesis y protesis" },
    { key: "c5", label: "17-Material imagenologia" },
    { key: "c6", label: "18-Material medico quirurgico" },
    { key: "c7", label: "19-Material y reactivos de laboratorio" },
    { key: "c8", label: "24-Materiales de oficina, productos de papel e impresos" },
    { key: "c9", label: "29-Materiales y elementos de aseo" },
    { key: "c10", label: "30-Medicamentos" },
    { key: "c11", label: "43-Productos textiles, vestuario y calzado" },
    { key: "c12", label: "230-Accesorios de costura" },
    { key: "c13", label: "231-Accesorios para generacion y distribucion de energia" },
    { key: "c14", label: "232-Accesorios y suministros para manejo, acondicionamiento y almacenamiento de materiales" },
    { key: "c15", label: "233-Componentes electronicos, iluminacion y acondicionamiento" },
    { key: "c16", label: "234-Componentes y sistemas para vehiculo" },
    { key: "c17", label: "235-Componentes y suministros de fabricacion, estructuras y construcciones" },
    { key: "c18", label: "236-Instrumentos de medida y observacion" },
    { key: "c19", label: "237-Productos de proteccion y resguardo medico, docificacion y gas hospitalario." },
    { key: "c20", label: "238-Productos de rehabilitacion y terapia ocupacional y fisica" },
    { key: "c21", label: "239-Productos para la esterilizacion de instrumental medico" },
    { key: "c22", label: "240-Productos quimicos, bioquimicos, minerales y gases industriales" },
    { key: "c23", label: "241-Publicaciones y formularios impresos y electronicos" },
    { key: "c24", label: "242-Suministro para tratamiento de agua" },
    { key: "c25", label: "243-Suministros de nutricion clinica" },
    { key: "c26", label: "244-Suministros para manejo y almacenamiento de materiales" },
    { key: "c27", label: "245-Suministros y productos de tratamiento y cuidados medicos" },
    { key: "c28", label: "246-Telecomunicaciones y radiodifusion de tecnologia de la informacion" },
    { key: "c29", label: "247-Utensilios y equipos menores de cocina" },
    { key: "c30", label: "248-Vacunas" },
    { key: "c31", label: "201-Productos alimenticios para personas" },
  ],
  rows: [
    { key: "r2", label: "66-Hospitalizacion medicina interna", sumOf: ["r3", "r4", "r98", "r5", "r6", "r99"] },
    { key: "r3", label: "Hospitalizacion Medicina Mujeres 1" },
    { key: "r4", label: "Hospitalizacion Medicina Mujeres 2" },
    { key: "r98", label: "Hospitalizacion Medicina Mujeres 3" },
    { key: "r5", label: "Hospitalizacion Medicina Hombres 1" },
    { key: "r6", label: "Hospitalizacion Medicina Hombres 2" },
    { key: "r99", label: "Hospitalizacion Medicina Hombres 3" },
    { key: "r7", label: "95-Hospitalizacion cirugia general", sumOf: ["r8", "r9"] },
    { key: "r8", label: "Hospitalizacion Cirugia Mujeres" },
    { key: "r9", label: "Hospitalizacion Cirugia Hombres" },
    { key: "r10", label: "745-Hospitalizacion servicios por convenios", sumOf: ["r11", "r12", "r13", "r14"] },
    { key: "r11", label: "Unidad de convenios" },
    { key: "r12", label: "Hospitalizacion convenios" },
    { key: "r13", label: "UCI convenios" },
    { key: "r14", label: "UCINT convenios" },
    { key: "r15", label: "166-Unidad de cuidados intensivos", sumOf: ["r16", "r17", "r18", "r19", "r20", "r21", "r22"] },
    { key: "r16", label: "UCI general I" },
    { key: "r17", label: "UCI Coronario y posquirurgicos" },
    { key: "r18", label: "UCI aislados" },
    { key: "r19", label: "UCI quirurgicos" },
    { key: "r20", label: "UCI cardiovasculares y Cardiología" },
    { key: "r21", label: "UCI neurointensivos" },
    { key: "r22", label: "UCI extracorporea" },
    { key: "r23", label: "179-Unidad de cuidados intermedios", sumOf: ["r24", "r25", "r26"] },
    { key: "r24", label: "Unidad de Cuidados Intermedios" },
    { key: "r25", label: "UCINT aislados" },
    { key: "r26", label: "UCINT cronicos" },
    { key: "r27", label: "201-Emergencias", sumOf: ["r28"] },
    { key: "r28", label: "Unidad de Admisiones" },
    { key: "r29", label: "743-Clinica empresarial" },
    { key: "r30", label: "806-Centro quirurgico", sumOf: ["r31", "r32"] },
    { key: "r31", label: "Centro quirurgico" },
    { key: "r32", label: "Anestesia" },
    { key: "r33", label: "767-Unidad de cuidados especiales", sumOf: ["r34"] },
    { key: "r34", label: "Cuidados paliativos" },
    { key: "r35", label: "766-Servicio de apoyo a riiss" },
    { key: "r36", label: "398-Vacunacion" },
    { key: "r37", label: "518-Laboratorio clinico" },
    { key: "r38", label: "530-Laboratorio de biologia molecular" },
    { key: "r39", label: "538-Resonancia magnetica" },
    { key: "r40", label: "541-Tomografia" },
    { key: "r41", label: "791-Estudio de radiologia" },
    { key: "r42", label: "559-Ultrasonografia" },
    { key: "r43", label: "776-Estudios gastroclinicos" },
    { key: "r44", label: "562-Terapia fisica" },
    { key: "r45", label: "566-Terapia respiratoria" },
    { key: "r46", label: "570-Rehabilitacion pulmonar" },
    { key: "r47", label: "575-Banco de sangre" },
    { key: "r48", label: "579-Unidad de hemodinamia" },
    { key: "r49", label: "268-Hemodialisis" },
    { key: "r50", label: "593-Servicio farmaceutico" },
    { key: "r51", label: "803-Rehablitacion psicosocial" },
    { key: "r52", label: "750-Alimentacion enteral" },
    { key: "r53", label: "760-Nutricion parenteral" },
    { key: "r54", label: "662-Central de esterilizacion" },
    { key: "r55", label: "761-Saneamiento ambiental" },
    { key: "r56", label: "648-Aseo" },
    { key: "r57", label: "721-Almacen", sumOf: ["r58", "r59", "r60"] },
    { key: "r58", label: "Almacen de insumos medicos" },
    { key: "r59", label: "Almacen de medicamento" },
    { key: "r60", label: "Almacen de suministros" },
    { key: "r61", label: "652-Servicio de alimentacion" },
    { key: "r62", label: "659-Lavanderia" },
    { key: "r63", label: "664-Transporte general" },
    { key: "r64", label: "665-Mantenimiento", sumOf: ["r65", "r66"] },
    { key: "r65", label: "Mantenimiento" },
    { key: "r66", label: "Activo Fijo" },
    { key: "r67", label: "713-Trabajo social" },
    { key: "r68", label: "702-Docencia e investigacion" },
    { key: "r69", label: "670-Administracion", sumOf: ["r70", "r71", "r72", "r73", "r74", "r75", "r76", "r77", "r78", "r79", "r80", "r81", "r82", "r83", "r84", "r85", "r86", "r87", "r88", "r89", "r90", "r91", "r92", "r93", "r94", "r95", "r96", "r97"] },
    { key: "r70", label: "ESDOMED" },
    { key: "r71", label: "Informatica" },
    { key: "r72", label: "Recursos Humanos" },
    { key: "r73", label: "UCP" },
    { key: "r74", label: "Unidad Financiera" },
    { key: "r75", label: "Planificacion y calidad" },
    { key: "r76", label: "Unidad juridica" },
    { key: "r77", label: "División medica" },
    { key: "r78", label: "Auditoria Interna" },
    { key: "r79", label: "Transporte" },
    { key: "r80", label: "División de diagnostico" },
    { key: "r81", label: "Enfermeria" },
    { key: "r82", label: "UCI" },
    { key: "r83", label: "Direccion" },
    { key: "r84", label: "Sub Direccion" },
    { key: "r85", label: "Sub Direccion Administrativa" },
    { key: "r86", label: "Departamento de Cirugia" },
    { key: "r87", label: "Comunicaciones" },
    { key: "r88", label: "Unidad de Epidemiologia" },
    { key: "r89", label: "Comité de salud y seguridad" },
    { key: "r90", label: "Dpto de Medicina Critica" },
    { key: "r91", label: "Dpto de Medicina Preventiva" },
    { key: "r92", label: "Dpto de Medicina Interna" },
    { key: "r93", label: "Oficina para el Derecho de la Salud" },
    { key: "r94", label: "Unidad de Asesoria de Suministro" },
    { key: "r95", label: "Fisioterapia" },
    { key: "r96", label: "Unidad de Cumplimiento" },
    { key: "r97", label: "Unidad de Gestion Documental" },
  ],
};