// AUTO-GENERADO desde "PSICOLOGIA .xlsx" (hoja MES ACTUAL).
// Tabulador SEPS de Psicologia, asignado al servicio "rehablitacion-psicosocial".
// Regenerar con el script de parseo si cambia la plantilla oficial.
import type { SepsTemplate } from "@/lib/seps-templates";

export const PSICOLOGIA_TEMPLATE: SepsTemplate = {
  serviceId: "rehablitacion-psicosocial",
  establishment: "HOSPITAL NACIONAL EL SALVADOR",
  tables: [
    {
      id: "t1",
      title: "TABULADOR DIARIO DE ACTIVIDADES DE PSICOLOGIA",
      detailLabel: "Detalle",
      rows: [
        { key: "t1_7", label: "# Personas primera vez" },
        { key: "t1_8", label: "Atenciones a consulta" },
        { key: "t1_9", label: "Referidos" },
      ],
    },
    {
      id: "t2",
      title: "TABULADOR DIARIO DE ACTIVIDADES DE PROMOCIÓN DE LA SALUD V",
      detailLabel: "Detalle",
      rows: [
        { key: "t2_19", label: "0 - 7 años · Mujeres", group: "SESIONES EDUCATIVAS · Salud mental" },
        { key: "t2_20", label: "0 - 7 años · Hombres", group: "SESIONES EDUCATIVAS · Salud mental" },
        { key: "t2_21", label: "8 - 9 años · Mujeres", group: "SESIONES EDUCATIVAS · Salud mental" },
        { key: "t2_22", label: "8 - 9 años · Hombres", group: "SESIONES EDUCATIVAS · Salud mental" },
        { key: "t2_23", label: "10 - 11 años · Mujeres", group: "SESIONES EDUCATIVAS · Salud mental" },
        { key: "t2_24", label: "10 - 11 años · Hombres", group: "SESIONES EDUCATIVAS · Salud mental" },
        { key: "t2_25", label: "12 - 14 años · Mujeres", group: "SESIONES EDUCATIVAS · Salud mental" },
        { key: "t2_26", label: "12 - 14 años · Hombres", group: "SESIONES EDUCATIVAS · Salud mental" },
        { key: "t2_27", label: "15 - 17 años · Mujeres", group: "SESIONES EDUCATIVAS · Salud mental" },
        { key: "t2_28", label: "15 - 17 años · Hombres", group: "SESIONES EDUCATIVAS · Salud mental" },
        { key: "t2_29", label: "18 - 19 años · Mujeres", group: "SESIONES EDUCATIVAS · Salud mental" },
        { key: "t2_30", label: "18 - 19 años · Hombres", group: "SESIONES EDUCATIVAS · Salud mental" },
        { key: "t2_31", label: "20-59 años · Mujeres", group: "SESIONES EDUCATIVAS · Salud mental" },
        { key: "t2_32", label: "20-59 años · Hombres", group: "SESIONES EDUCATIVAS · Salud mental" },
        { key: "t2_33", label: "60 años y más · Mujeres", group: "SESIONES EDUCATIVAS · Salud mental" },
        { key: "t2_34", label: "60 años y más · Hombres", group: "SESIONES EDUCATIVAS · Salud mental" },
        { key: "t2_35", label: "Sesiones con grupos · Salud Materna", group: "SESIONES EDUCATIVAS · Salud mental" },
        { key: "t2_36", label: "Sesiones con grupos · Salud infantil", group: "SESIONES EDUCATIVAS · Salud mental" },
        { key: "t2_37", label: "Sesiones con grupos · Adolescentes", group: "SESIONES EDUCATIVAS · Salud mental" },
        { key: "t2_38", label: "Sesiones con grupos · Adultos mayores", group: "SESIONES EDUCATIVAS · Salud mental" },
        { key: "t2_39", label: "Sesiones con grupos · Autoayuda de personas con enfermedades no transmisibles y factores de riesgo", group: "SESIONES EDUCATIVAS · Salud mental" },
        { key: "t2_40", label: "Sesiones con grupos · Otro grupo organizado", group: "SESIONES EDUCATIVAS · Salud mental" },
        { key: "t2_41", label: "Sesiones con grupos · Total de sesiones", group: "SESIONES EDUCATIVAS · Salud mental" },
      ],
    },
    {
      id: "t3",
      title: "TABULADOR DIARIO DE ACTIVIDADES DE PROMOCIÓN DE LA SALUD VII",
      detailLabel: "Detalle",
      rows: [
        { key: "t3_50", label: "0 - 7 años · Mujeres", group: "SESIONES EDUCATIVAS · Habilidades para la vida" },
        { key: "t3_51", label: "0 - 7 años · Hombres", group: "SESIONES EDUCATIVAS · Habilidades para la vida" },
        { key: "t3_52", label: "8 - 9 años · Mujeres", group: "SESIONES EDUCATIVAS · Habilidades para la vida" },
        { key: "t3_53", label: "8 - 9 años · Hombres", group: "SESIONES EDUCATIVAS · Habilidades para la vida" },
        { key: "t3_54", label: "10 - 11 años · Mujeres", group: "SESIONES EDUCATIVAS · Habilidades para la vida" },
        { key: "t3_55", label: "10 - 11 años · Hombres", group: "SESIONES EDUCATIVAS · Habilidades para la vida" },
        { key: "t3_56", label: "12 - 14 años · Mujeres", group: "SESIONES EDUCATIVAS · Habilidades para la vida" },
        { key: "t3_57", label: "12 - 14 años · Hombres", group: "SESIONES EDUCATIVAS · Habilidades para la vida" },
        { key: "t3_58", label: "15 - 17 años · Mujeres", group: "SESIONES EDUCATIVAS · Habilidades para la vida" },
        { key: "t3_59", label: "15 - 17 años · Hombres", group: "SESIONES EDUCATIVAS · Habilidades para la vida" },
        { key: "t3_60", label: "18 - 19 años · Mujeres", group: "SESIONES EDUCATIVAS · Habilidades para la vida" },
        { key: "t3_61", label: "18 - 19 años · Hombres", group: "SESIONES EDUCATIVAS · Habilidades para la vida" },
        { key: "t3_62", label: "20-59 años · Mujeres", group: "SESIONES EDUCATIVAS · Habilidades para la vida" },
        { key: "t3_63", label: "20-59 años · Hombres", group: "SESIONES EDUCATIVAS · Habilidades para la vida" },
        { key: "t3_64", label: "60 años y más · Mujeres", group: "SESIONES EDUCATIVAS · Habilidades para la vida" },
        { key: "t3_65", label: "60 años y más · Hombres", group: "SESIONES EDUCATIVAS · Habilidades para la vida" },
        { key: "t3_66", label: "Sesiones con grupos · Salud Materna", group: "SESIONES EDUCATIVAS · Habilidades para la vida" },
        { key: "t3_67", label: "Sesiones con grupos · Salud infantil", group: "SESIONES EDUCATIVAS · Habilidades para la vida" },
        { key: "t3_68", label: "Sesiones con grupos · Adolescentes", group: "SESIONES EDUCATIVAS · Habilidades para la vida" },
        { key: "t3_69", label: "Sesiones con grupos · Adultos mayores", group: "SESIONES EDUCATIVAS · Habilidades para la vida" },
        { key: "t3_70", label: "Sesiones con grupos · Autoayuda de personas con enfermedades no transmisibles y factores de riesgo", group: "SESIONES EDUCATIVAS · Habilidades para la vida" },
        { key: "t3_71", label: "Sesiones con grupos · Otro grupo organizado", group: "SESIONES EDUCATIVAS · Habilidades para la vida" },
        { key: "t3_72", label: "Sesiones con grupos · Total de sesiones", group: "SESIONES EDUCATIVAS · Habilidades para la vida" },
      ],
    },
    {
      id: "t4",
      title: "TABULADOR DIARIO DE ACTIVIDADES DE PROMOCIÓN DE LA SALUD VIII",
      detailLabel: "Detalle",
      rows: [
        { key: "t4_81", label: "0 - 7 años · Mujeres", group: "SESIONES EDUCATIVAS · Descanso e higiene del sueño" },
        { key: "t4_82", label: "0 - 7 años · Hombres", group: "SESIONES EDUCATIVAS · Descanso e higiene del sueño" },
        { key: "t4_83", label: "8 - 9 años · Mujeres", group: "SESIONES EDUCATIVAS · Descanso e higiene del sueño" },
        { key: "t4_84", label: "8 - 9 años · Hombres", group: "SESIONES EDUCATIVAS · Descanso e higiene del sueño" },
        { key: "t4_85", label: "10 - 11 años · Mujeres", group: "SESIONES EDUCATIVAS · Descanso e higiene del sueño" },
        { key: "t4_86", label: "10 - 11 años · Hombres", group: "SESIONES EDUCATIVAS · Descanso e higiene del sueño" },
        { key: "t4_87", label: "12 - 14 años · Mujeres", group: "SESIONES EDUCATIVAS · Descanso e higiene del sueño" },
        { key: "t4_88", label: "12 - 14 años · Hombres", group: "SESIONES EDUCATIVAS · Descanso e higiene del sueño" },
        { key: "t4_89", label: "15 - 17 años · Mujeres", group: "SESIONES EDUCATIVAS · Descanso e higiene del sueño" },
        { key: "t4_90", label: "15 - 17 años · Hombres", group: "SESIONES EDUCATIVAS · Descanso e higiene del sueño" },
        { key: "t4_91", label: "18 - 19 años · Mujeres", group: "SESIONES EDUCATIVAS · Descanso e higiene del sueño" },
        { key: "t4_92", label: "18 - 19 años · Hombres", group: "SESIONES EDUCATIVAS · Descanso e higiene del sueño" },
        { key: "t4_93", label: "20-59 años · Mujeres", group: "SESIONES EDUCATIVAS · Descanso e higiene del sueño" },
        { key: "t4_94", label: "20-59 años · Hombres", group: "SESIONES EDUCATIVAS · Descanso e higiene del sueño" },
        { key: "t4_95", label: "60 años y más · Mujeres", group: "SESIONES EDUCATIVAS · Descanso e higiene del sueño" },
        { key: "t4_96", label: "60 años y más · Hombres", group: "SESIONES EDUCATIVAS · Descanso e higiene del sueño" },
        { key: "t4_97", label: "Sesiones con grupos · Salud Materna", group: "SESIONES EDUCATIVAS · Descanso e higiene del sueño" },
        { key: "t4_98", label: "Sesiones con grupos · Salud infantil", group: "SESIONES EDUCATIVAS · Descanso e higiene del sueño" },
        { key: "t4_99", label: "Sesiones con grupos · Adolescentes", group: "SESIONES EDUCATIVAS · Descanso e higiene del sueño" },
        { key: "t4_100", label: "Sesiones con grupos · Adultos mayores", group: "SESIONES EDUCATIVAS · Descanso e higiene del sueño" },
        { key: "t4_101", label: "Sesiones con grupos · Autoayuda de personas con enfermedades no transmisibles y factores de riesgo", group: "SESIONES EDUCATIVAS · Descanso e higiene del sueño" },
        { key: "t4_102", label: "Sesiones con grupos · Otro grupo organizado", group: "SESIONES EDUCATIVAS · Descanso e higiene del sueño" },
        { key: "t4_103", label: "Sesiones con grupos · Total de sesiones", group: "SESIONES EDUCATIVAS · Descanso e higiene del sueño" },
      ],
    },
    {
      id: "t5",
      title: "TABULADOR DIARIO DE ATENCIONES GRUPALES DE SALUD MENTAL I",
      detailLabel: "Detalle",
      rows: [
        { key: "t5_112", label: "0 a 7 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 1. Grupo terapéutico o psicoterapia" },
        { key: "t5_113", label: "0 a 7 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 1. Grupo terapéutico o psicoterapia" },
        { key: "t5_114", label: "8 a 9 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 1. Grupo terapéutico o psicoterapia" },
        { key: "t5_115", label: "8 a 9 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 1. Grupo terapéutico o psicoterapia" },
        { key: "t5_116", label: "10 a 11 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 1. Grupo terapéutico o psicoterapia" },
        { key: "t5_117", label: "10 a 11 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 1. Grupo terapéutico o psicoterapia" },
        { key: "t5_118", label: "12 a 17 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 1. Grupo terapéutico o psicoterapia" },
        { key: "t5_119", label: "12 a 17 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 1. Grupo terapéutico o psicoterapia" },
        { key: "t5_120", label: "18 a 19 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 1. Grupo terapéutico o psicoterapia" },
        { key: "t5_121", label: "18 a 19 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 1. Grupo terapéutico o psicoterapia" },
        { key: "t5_122", label: "20 a 59 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 1. Grupo terapéutico o psicoterapia" },
        { key: "t5_123", label: "20 a 59 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 1. Grupo terapéutico o psicoterapia" },
        { key: "t5_124", label: "60 años a más · Masculino", group: "ATENCIÓN ESPECIALIZADA · 1. Grupo terapéutico o psicoterapia" },
        { key: "t5_125", label: "60 años a más · Femenino", group: "ATENCIÓN ESPECIALIZADA · 1. Grupo terapéutico o psicoterapia" },
        { key: "t5_126", label: "N° de sesiones realizadas", group: "ATENCIÓN ESPECIALIZADA · 1. Grupo terapéutico o psicoterapia" },
        { key: "t5_127", label: "N° de Embarazadas · Adolescentes", group: "ATENCIÓN ESPECIALIZADA · 1. Grupo terapéutico o psicoterapia" },
        { key: "t5_128", label: "N° de Embarazadas · Adultas", group: "ATENCIÓN ESPECIALIZADA · 1. Grupo terapéutico o psicoterapia" },
        { key: "t5_129", label: "0 a 7 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 2. Jornada de autocuidado" },
        { key: "t5_130", label: "0 a 7 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 2. Jornada de autocuidado" },
        { key: "t5_131", label: "8 a 9 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 2. Jornada de autocuidado" },
        { key: "t5_132", label: "8 a 9 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 2. Jornada de autocuidado" },
        { key: "t5_133", label: "10 a 11 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 2. Jornada de autocuidado" },
        { key: "t5_134", label: "10 a 11 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 2. Jornada de autocuidado" },
        { key: "t5_135", label: "12 a 17 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 2. Jornada de autocuidado" },
        { key: "t5_136", label: "12 a 17 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 2. Jornada de autocuidado" },
        { key: "t5_137", label: "18 a 19 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 2. Jornada de autocuidado" },
        { key: "t5_138", label: "18 a 19 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 2. Jornada de autocuidado" },
        { key: "t5_139", label: "20 a 59 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 2. Jornada de autocuidado" },
        { key: "t5_140", label: "20 a 59 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 2. Jornada de autocuidado" },
        { key: "t5_141", label: "60 años a más · Masculino", group: "ATENCIÓN ESPECIALIZADA · 2. Jornada de autocuidado" },
        { key: "t5_142", label: "60 años a más · Femenino", group: "ATENCIÓN ESPECIALIZADA · 2. Jornada de autocuidado" },
        { key: "t5_143", label: "N° Jornadas Realizadas", group: "ATENCIÓN ESPECIALIZADA · 2. Jornada de autocuidado" },
        { key: "t5_144", label: "0 a 7 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 3. Terapia lúdica" },
        { key: "t5_145", label: "0 a 7 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 3. Terapia lúdica" },
        { key: "t5_146", label: "8 a 9 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 3. Terapia lúdica" },
        { key: "t5_147", label: "8 a 9 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 3. Terapia lúdica" },
        { key: "t5_148", label: "10 a 11 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 3. Terapia lúdica" },
        { key: "t5_149", label: "10 a 11 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 3. Terapia lúdica" },
        { key: "t5_150", label: "12 a 17 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 3. Terapia lúdica" },
        { key: "t5_151", label: "12 a 17 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 3. Terapia lúdica" },
        { key: "t5_152", label: "18 a 19 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 3. Terapia lúdica" },
        { key: "t5_153", label: "18 a 19 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 3. Terapia lúdica" },
        { key: "t5_154", label: "20 a 59 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 3. Terapia lúdica" },
        { key: "t5_155", label: "20 a 59 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 3. Terapia lúdica" },
        { key: "t5_156", label: "60 años a más · Masculino", group: "ATENCIÓN ESPECIALIZADA · 3. Terapia lúdica" },
        { key: "t5_157", label: "60 años a más · Femenino", group: "ATENCIÓN ESPECIALIZADA · 3. Terapia lúdica" },
        { key: "t5_158", label: "N°de Sesiones Realizadas", group: "ATENCIÓN ESPECIALIZADA · 3. Terapia lúdica" },
      ],
    },
    {
      id: "t6",
      title: "TABULADOR DIARIO DE ATENCIONES GRUPALES DE SALUD MENTAL II",
      detailLabel: "Detalle",
      rows: [
        { key: "t6_167", label: "0 a 7 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 4. Arte-terapia" },
        { key: "t6_168", label: "0 a 7 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 4. Arte-terapia" },
        { key: "t6_169", label: "8 a 9 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 4. Arte-terapia" },
        { key: "t6_170", label: "8 a 9 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 4. Arte-terapia" },
        { key: "t6_171", label: "10 a 11 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 4. Arte-terapia" },
        { key: "t6_172", label: "10 a 11 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 4. Arte-terapia" },
        { key: "t6_173", label: "12 a 17 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 4. Arte-terapia" },
        { key: "t6_174", label: "12 a 17 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 4. Arte-terapia" },
        { key: "t6_175", label: "18 a 19 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 4. Arte-terapia" },
        { key: "t6_176", label: "18 a 19 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 4. Arte-terapia" },
        { key: "t6_177", label: "20 a 59 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 4. Arte-terapia" },
        { key: "t6_178", label: "20 a 59 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 4. Arte-terapia" },
        { key: "t6_179", label: "60 años a más · Masculino", group: "ATENCIÓN ESPECIALIZADA · 4. Arte-terapia" },
        { key: "t6_180", label: "60 años a más · Femenino", group: "ATENCIÓN ESPECIALIZADA · 4. Arte-terapia" },
        { key: "t6_181", label: "N°de Sesiones Realizadas", group: "ATENCIÓN ESPECIALIZADA · 4. Arte-terapia" },
        { key: "t6_182", label: "12 a 17 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 5. Grupo de autoayuda o apoyo" },
        { key: "t6_183", label: "12 a 17 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 5. Grupo de autoayuda o apoyo" },
        { key: "t6_184", label: "18 a 19 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 5. Grupo de autoayuda o apoyo" },
        { key: "t6_185", label: "18 a 19 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 5. Grupo de autoayuda o apoyo" },
        { key: "t6_186", label: "20 a 59 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 5. Grupo de autoayuda o apoyo" },
        { key: "t6_187", label: "20 a 59 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 5. Grupo de autoayuda o apoyo" },
        { key: "t6_188", label: "60 y mas años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 5. Grupo de autoayuda o apoyo" },
        { key: "t6_189", label: "60 y mas años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 5. Grupo de autoayuda o apoyo" },
        { key: "t6_190", label: "N°de Sesiones Realizadas", group: "ATENCIÓN ESPECIALIZADA · 5. Grupo de autoayuda o apoyo" },
        { key: "t6_191", label: "12 a 17 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 6. Grupo psicoeducativo" },
        { key: "t6_192", label: "12 a 17 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 6. Grupo psicoeducativo" },
        { key: "t6_193", label: "18 a 19 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 6. Grupo psicoeducativo" },
        { key: "t6_194", label: "18 a 19 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 6. Grupo psicoeducativo" },
        { key: "t6_195", label: "20 a 59 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 6. Grupo psicoeducativo" },
        { key: "t6_196", label: "20 a 59 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 6. Grupo psicoeducativo" },
        { key: "t6_197", label: "60 y mas años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 6. Grupo psicoeducativo" },
        { key: "t6_198", label: "60 y mas años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 6. Grupo psicoeducativo" },
        { key: "t6_199", label: "N° de Sesiones Realizadas", group: "ATENCIÓN ESPECIALIZADA · 6. Grupo psicoeducativo" },
        { key: "t6_200", label: "0 a 7 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 7. Intervención en crisis" },
        { key: "t6_201", label: "0 a 7 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 7. Intervención en crisis" },
        { key: "t6_202", label: "8 a 9 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 7. Intervención en crisis" },
        { key: "t6_203", label: "8 a 9 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 7. Intervención en crisis" },
        { key: "t6_204", label: "10 a 11 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 7. Intervención en crisis" },
        { key: "t6_205", label: "10 a 11 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 7. Intervención en crisis" },
        { key: "t6_206", label: "12 a 17 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 7. Intervención en crisis" },
        { key: "t6_207", label: "12 a 17 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 7. Intervención en crisis" },
        { key: "t6_208", label: "18 a 19 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 7. Intervención en crisis" },
        { key: "t6_209", label: "18 a 19 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 7. Intervención en crisis" },
        { key: "t6_210", label: "20 a 59 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 7. Intervención en crisis" },
        { key: "t6_211", label: "20 a 59 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 7. Intervención en crisis" },
        { key: "t6_212", label: "60 años a más · Masculino", group: "ATENCIÓN ESPECIALIZADA · 7. Intervención en crisis" },
        { key: "t6_213", label: "60 años a más · Femenino", group: "ATENCIÓN ESPECIALIZADA · 7. Intervención en crisis" },
        { key: "t6_214", label: "N° de Sesiones Realizadas", group: "ATENCIÓN ESPECIALIZADA · 7. Intervención en crisis" },
      ],
    },
    {
      id: "t7",
      title: "TABULADOR DIARIO DE ATENCIONES GRUPALES DE SALUD MENTAL III",
      detailLabel: "Detalle",
      rows: [
        { key: "t7_223", label: "0 a 7 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional fisioterapia" },
        { key: "t7_224", label: "0 a 7 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional fisioterapia" },
        { key: "t7_225", label: "8 a 9 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional fisioterapia" },
        { key: "t7_226", label: "8 a 9 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional fisioterapia" },
        { key: "t7_227", label: "10 a 11 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional fisioterapia" },
        { key: "t7_228", label: "10 a 11 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional fisioterapia" },
        { key: "t7_229", label: "12 a 17 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional fisioterapia" },
        { key: "t7_230", label: "12 a 17 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional fisioterapia" },
        { key: "t7_231", label: "18 a 19 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional fisioterapia" },
        { key: "t7_232", label: "18 a 19 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional fisioterapia" },
        { key: "t7_233", label: "20 a 59 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional fisioterapia" },
        { key: "t7_234", label: "20 a 59 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional fisioterapia" },
        { key: "t7_235", label: "60 años a más · Masculino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional fisioterapia" },
        { key: "t7_236", label: "60 años a más · Femenino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional fisioterapia" },
        { key: "t7_237", label: "N° de Sesiones Realizadas", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional fisioterapia" },
        { key: "t7_238", label: "0 a 7 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 9. Otras intervenciones" },
        { key: "t7_239", label: "0 a 7 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 9. Otras intervenciones" },
        { key: "t7_240", label: "8 a 9 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 9. Otras intervenciones" },
        { key: "t7_241", label: "8 a 9 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 9. Otras intervenciones" },
        { key: "t7_242", label: "10 a 11 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 9. Otras intervenciones" },
        { key: "t7_243", label: "10 a 11 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 9. Otras intervenciones" },
        { key: "t7_244", label: "12 a 17 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 9. Otras intervenciones" },
        { key: "t7_245", label: "12 a 17 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 9. Otras intervenciones" },
        { key: "t7_246", label: "18 a 19 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 9. Otras intervenciones" },
        { key: "t7_247", label: "18 a 19 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 9. Otras intervenciones" },
        { key: "t7_248", label: "20 a 59 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 9. Otras intervenciones" },
        { key: "t7_249", label: "20 a 59 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 9. Otras intervenciones" },
        { key: "t7_250", label: "60 años a más · Masculino", group: "ATENCIÓN ESPECIALIZADA · 9. Otras intervenciones" },
        { key: "t7_251", label: "60 años a más · Femenino", group: "ATENCIÓN ESPECIALIZADA · 9. Otras intervenciones" },
        { key: "t7_252", label: "N°de Sesiones Realizadas", group: "ATENCIÓN ESPECIALIZADA · 9. Otras intervenciones" },
        { key: "t7_253", label: "Tabaco y otras drogas", group: "ATENCIÓN ESPECIALIZADA · 10.Charlas de salud mental" },
        { key: "t7_254", label: "Alcohol", group: "ATENCIÓN ESPECIALIZADA · 10.Charlas de salud mental" },
        { key: "t7_255", label: "Estrategia Aprender y Crecer Saludables", group: "ATENCIÓN ESPECIALIZADA · 10.Charlas de salud mental" },
        { key: "t7_256", label: "Prevención de suicidio", group: "ATENCIÓN ESPECIALIZADA · 10.Charlas de salud mental" },
        { key: "t7_257", label: "Trastornos de salud mental", group: "ATENCIÓN ESPECIALIZADA · 10.Charlas de salud mental" },
        { key: "t7_258", label: "Duelo · Prematurez", group: "ATENCIÓN ESPECIALIZADA · 10.Charlas de salud mental" },
        { key: "t7_259", label: "Duelo · Malformaciones congénitas", group: "ATENCIÓN ESPECIALIZADA · 10.Charlas de salud mental" },
        { key: "t7_260", label: "Duelo · Riesgo de muerte", group: "ATENCIÓN ESPECIALIZADA · 10.Charlas de salud mental" },
        { key: "t7_261", label: "Duelo · Suicidio", group: "ATENCIÓN ESPECIALIZADA · 10.Charlas de salud mental" },
        { key: "t7_262", label: "Juego en la niñez", group: "ATENCIÓN ESPECIALIZADA · 10.Charlas de salud mental" },
        { key: "t7_263", label: "Otras", group: "ATENCIÓN ESPECIALIZADA · 10.Charlas de salud mental" },
        { key: "t7_264", label: "Total de Charlas", group: "ATENCIÓN ESPECIALIZADA · 10.Charlas de salud mental" },
        { key: "t7_265", label: "No. de participantes", group: "ATENCIÓN ESPECIALIZADA · 10.Charlas de salud mental" },
        { key: "t7_266", label: "0 a 7 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 11. Sesiones Psicoeducativas" },
        { key: "t7_267", label: "0 a 7 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 11. Sesiones Psicoeducativas" },
        { key: "t7_268", label: "8 a 9 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 11. Sesiones Psicoeducativas" },
        { key: "t7_269", label: "8 a 9 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 11. Sesiones Psicoeducativas" },
        { key: "t7_270", label: "10 a 11 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 11. Sesiones Psicoeducativas" },
        { key: "t7_271", label: "10 a 11 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 11. Sesiones Psicoeducativas" },
        { key: "t7_272", label: "12 a 17 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 11. Sesiones Psicoeducativas" },
        { key: "t7_273", label: "12 a 17 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 11. Sesiones Psicoeducativas" },
        { key: "t7_274", label: "18 a 19 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 11. Sesiones Psicoeducativas" },
        { key: "t7_275", label: "18 a 19 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 11. Sesiones Psicoeducativas" },
        { key: "t7_276", label: "20 a 59 años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 11. Sesiones Psicoeducativas" },
        { key: "t7_277", label: "20 a 59 años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 11. Sesiones Psicoeducativas" },
        { key: "t7_278", label: "60 y mas años · Masculino", group: "ATENCIÓN ESPECIALIZADA · 11. Sesiones Psicoeducativas" },
        { key: "t7_279", label: "60 y mas años · Femenino", group: "ATENCIÓN ESPECIALIZADA · 11. Sesiones Psicoeducativas" },
        { key: "t7_280", label: "N° de personas atendidas", group: "ATENCIÓN ESPECIALIZADA · 11. Sesiones Psicoeducativas" },
        { key: "t7_281", label: "N° de Sesiones realizadas", group: "ATENCIÓN ESPECIALIZADA · 11. Sesiones Psicoeducativas" },
      ],
    },
    {
      id: "t8",
      title: "TABULADOR DIARIO DE ATENCIONES GRUPALES DE SALUD MENTAL IV",
      detailLabel: "Detalle",
      rows: [
        { key: "t8_290", label: "Establecimiento de salud", group: "Atencion especializada · 12. Jornadas en Salud Mental" },
        { key: "t8_291", label: "Centro Escolar", group: "Atencion especializada · 12. Jornadas en Salud Mental" },
        { key: "t8_292", label: "Comunidad/Intersectorialidad", group: "Atencion especializada · 12. Jornadas en Salud Mental" },
        { key: "t8_293", label: "No. de jornadas realizadas", group: "Atencion especializada · 12. Jornadas en Salud Mental" },
        { key: "t8_294", label: "N° de participantes", group: "Atencion especializada · 12. Jornadas en Salud Mental" },
        { key: "t8_295", label: "No. De Sesiones", group: "Atencion especializada · 13. Terapia de pareja" },
        { key: "t8_296", label: "No. de personas atendidas", group: "Atencion especializada · 13. Terapia de pareja" },
        { key: "t8_297", label: "No. De Sesiones", group: "ESTRATEGIAS DE SALUD MENTAL · 14. Terapia de familia" },
        { key: "t8_298", label: "Total de escalas aplicadas.", group: "ESTRATEGIAS DE SALUD MENTAL · 15. Aplicación de escalas y pruebas psicométricas" },
        { key: "t8_299", label: "Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 16. Internconsultas" },
        { key: "t8_300", label: "Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 16. Internconsultas" },
        { key: "t8_301", label: "12 a 17 años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 17.Grupo de Familia a familia" },
        { key: "t8_302", label: "12 a 17 años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 17.Grupo de Familia a familia" },
        { key: "t8_303", label: "18 a 19 años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 17.Grupo de Familia a familia" },
        { key: "t8_304", label: "18 a 19 años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 17.Grupo de Familia a familia" },
        { key: "t8_305", label: "20 a 59 años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 17.Grupo de Familia a familia" },
        { key: "t8_306", label: "20 a 59 años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 17.Grupo de Familia a familia" },
        { key: "t8_307", label: "60 y mas años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 17.Grupo de Familia a familia" },
        { key: "t8_308", label: "60 y mas años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 17.Grupo de Familia a familia" },
        { key: "t8_309", label: "Total de sesiones", group: "ESTRATEGIAS DE SALUD MENTAL · 17.Grupo de Familia a familia" },
        { key: "t8_310", label: "12 a 17 años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 18. Grupo de autoayuda o apoyo para el manejo de las adicciones" },
        { key: "t8_311", label: "12 a 17 años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 18. Grupo de autoayuda o apoyo para el manejo de las adicciones" },
        { key: "t8_312", label: "18 a 19 años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 18. Grupo de autoayuda o apoyo para el manejo de las adicciones" },
        { key: "t8_313", label: "18 a 19 años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 18. Grupo de autoayuda o apoyo para el manejo de las adicciones" },
        { key: "t8_314", label: "20 a 59 años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 18. Grupo de autoayuda o apoyo para el manejo de las adicciones" },
        { key: "t8_315", label: "20 a 59 años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 18. Grupo de autoayuda o apoyo para el manejo de las adicciones" },
        { key: "t8_316", label: "60 y mas años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 18. Grupo de autoayuda o apoyo para el manejo de las adicciones" },
        { key: "t8_317", label: "60 y mas años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 18. Grupo de autoayuda o apoyo para el manejo de las adicciones" },
        { key: "t8_318", label: "Total de sesiones", group: "ESTRATEGIAS DE SALUD MENTAL · 18. Grupo de autoayuda o apoyo para el manejo de las adicciones" },
        { key: "t8_319", label: "0 a 7 años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 19. Recomendaciones de Salud mental: ¨Primeros pasos" },
        { key: "t8_320", label: "0 a 7 años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 19. Recomendaciones de Salud mental: ¨Primeros pasos" },
        { key: "t8_321", label: "Total de sesiones", group: "ESTRATEGIAS DE SALUD MENTAL · 19. Recomendaciones de Salud mental: ¨Primeros pasos" },
        { key: "t8_322", label: "8 a 9 años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 20. Grupo de terapia conductual para niñas, niños y adolescentes" },
        { key: "t8_323", label: "8 a 9 años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 20. Grupo de terapia conductual para niñas, niños y adolescentes" },
        { key: "t8_324", label: "10 a 11 años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 20. Grupo de terapia conductual para niñas, niños y adolescentes" },
        { key: "t8_325", label: "10 a 11 años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 20. Grupo de terapia conductual para niñas, niños y adolescentes" },
        { key: "t8_326", label: "12 a 17 años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 20. Grupo de terapia conductual para niñas, niños y adolescentes" },
        { key: "t8_327", label: "12 a 17 años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 20. Grupo de terapia conductual para niñas, niños y adolescentes" },
        { key: "t8_328", label: "Total de sesiones", group: "ESTRATEGIAS DE SALUD MENTAL · 20. Grupo de terapia conductual para niñas, niños y adolescentes" },
      ],
    },
    {
      id: "t9",
      title: "TABULADOR DIARIO DE ATENCIONES GRUPALES DE SALUD MENTAL V",
      detailLabel: "Detalle",
      rows: [
        { key: "t9_337", label: "20 a 59 años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 21. Grupo de terapia conductual para madres, padres y cuidadores" },
        { key: "t9_338", label: "20 a 59 años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 21. Grupo de terapia conductual para madres, padres y cuidadores" },
        { key: "t9_339", label: "60 y mas años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 21. Grupo de terapia conductual para madres, padres y cuidadores" },
        { key: "t9_340", label: "60 y mas años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 21. Grupo de terapia conductual para madres, padres y cuidadores" },
        { key: "t9_341", label: "Total de Sesiones", group: "ESTRATEGIAS DE SALUD MENTAL · 21. Grupo de terapia conductual para madres, padres y cuidadores" },
        { key: "t9_342", label: "0 a 7 años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 22. Recorrido participativo para niñas y niños \"Aprendamos juntos de salud mental\"" },
        { key: "t9_343", label: "0 a 7 años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 22. Recorrido participativo para niñas y niños \"Aprendamos juntos de salud mental\"" },
        { key: "t9_344", label: "8 a 9 años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 22. Recorrido participativo para niñas y niños \"Aprendamos juntos de salud mental\"" },
        { key: "t9_345", label: "8 a 9 años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 22. Recorrido participativo para niñas y niños \"Aprendamos juntos de salud mental\"" },
        { key: "t9_346", label: "10 a 11 años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 22. Recorrido participativo para niñas y niños \"Aprendamos juntos de salud mental\"" },
        { key: "t9_347", label: "10 a 11 años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 22. Recorrido participativo para niñas y niños \"Aprendamos juntos de salud mental\"" },
        { key: "t9_348", label: "12 a 17 años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 22. Recorrido participativo para niñas y niños \"Aprendamos juntos de salud mental\"" },
        { key: "t9_349", label: "12 a 17 años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 22. Recorrido participativo para niñas y niños \"Aprendamos juntos de salud mental\"" },
        { key: "t9_350", label: "18 a 19 años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 22. Recorrido participativo para niñas y niños \"Aprendamos juntos de salud mental\"" },
        { key: "t9_351", label: "18 a 19 años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 22. Recorrido participativo para niñas y niños \"Aprendamos juntos de salud mental\"" },
        { key: "t9_352", label: "Total realizados", group: "ESTRATEGIAS DE SALUD MENTAL · 22. Recorrido participativo para niñas y niños \"Aprendamos juntos de salud mental\"" },
        { key: "t9_353", label: "0 a 7 años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 23. Visita Domiciliar" },
        { key: "t9_354", label: "0 a 7 años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 23. Visita Domiciliar" },
        { key: "t9_355", label: "8 a 9 años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 23. Visita Domiciliar" },
        { key: "t9_356", label: "8 a 9 años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 23. Visita Domiciliar" },
        { key: "t9_357", label: "10 a 11 años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 23. Visita Domiciliar" },
        { key: "t9_358", label: "10 a 11 años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 23. Visita Domiciliar" },
        { key: "t9_359", label: "12 a 17 años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 23. Visita Domiciliar" },
        { key: "t9_360", label: "12 a 17 años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 23. Visita Domiciliar" },
        { key: "t9_361", label: "18 a 19 años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 23. Visita Domiciliar" },
        { key: "t9_362", label: "18 a 19 años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 23. Visita Domiciliar" },
        { key: "t9_363", label: "20 a 59 años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 23. Visita Domiciliar" },
        { key: "t9_364", label: "20 a 59 años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 23. Visita Domiciliar" },
        { key: "t9_365", label: "60 y mas años · Masculino", group: "ESTRATEGIAS DE SALUD MENTAL · 23. Visita Domiciliar" },
        { key: "t9_366", label: "60 y mas años · Femenino", group: "ESTRATEGIAS DE SALUD MENTAL · 23. Visita Domiciliar" },
        { key: "t9_367", label: "Total de Sesiones", group: "ESTRATEGIAS DE SALUD MENTAL · 23. Visita Domiciliar" },
        { key: "t9_368", label: "No. dinamizador del juego", group: "ESPACIOS AMIGABLES · Salas de espera consulta externa" },
        { key: "t9_369", label: "No. de niñas participantes", group: "ESPACIOS AMIGABLES · Salas de espera consulta externa" },
        { key: "t9_370", label: "No. de niños participantes", group: "ESPACIOS AMIGABLES · Salas de espera consulta externa" },
        { key: "t9_371", label: "No. padres de familias participantes", group: "ESPACIOS AMIGABLES · Salas de espera consulta externa" },
        { key: "t9_372", label: "Demostraciones lúdicas", group: "ESPACIOS AMIGABLES · Salas de espera consulta externa" },
        { key: "t9_373", label: "No. de niñas participantes", group: "ESPACIOS AMIGABLES · Ludotecas" },
        { key: "t9_374", label: "No. de niños participantes", group: "ESPACIOS AMIGABLES · Ludotecas" },
        { key: "t9_375", label: "No. padres de familias participantes", group: "ESPACIOS AMIGABLES · Ludotecas" },
        { key: "t9_376", label: "No. Juegos lúdicos", group: "ESPACIOS AMIGABLES · Ludotecas" },
        { key: "t9_377", label: "No. de niñas participantes", group: "ESPACIOS AMIGABLES · Otros espacios de juego" },
        { key: "t9_378", label: "No. de niños participantes", group: "ESPACIOS AMIGABLES · Otros espacios de juego" },
        { key: "t9_379", label: "No. padres de familias participantes", group: "ESPACIOS AMIGABLES · Otros espacios de juego" },
        { key: "t9_380", label: "Demostraciones lúdicas", group: "ESPACIOS AMIGABLES · Otros espacios de juego" },
      ],
    },
    {
      id: "t10",
      title: "TABULADOR DIARIO DE ACTIVIDADES DE DETECCION DE PERSONAS VICTIMAS DE VIOLENCIA I",
      detailLabel: "Detalle",
      rows: [
        { key: "t10_387", label: "1-De 0- 11 años · Niñas", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · A-Física (1+2+3+4+5+6)" },
        { key: "t10_388", label: "1-De 0- 11 años · Niños", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · A-Física (1+2+3+4+5+6)" },
        { key: "t10_389", label: "2-De 12-17 años · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · A-Física (1+2+3+4+5+6)" },
        { key: "t10_390", label: "2-De 12-17 años · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · A-Física (1+2+3+4+5+6)" },
        { key: "t10_391", label: "3-De 18-19 años · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · A-Física (1+2+3+4+5+6)" },
        { key: "t10_392", label: "3-De 18-19 años · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · A-Física (1+2+3+4+5+6)" },
        { key: "t10_393", label: "4-Embarazadas · 10-14 años", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · A-Física (1+2+3+4+5+6)" },
        { key: "t10_394", label: "4-Embarazadas · 15- 19 años", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · A-Física (1+2+3+4+5+6)" },
        { key: "t10_395", label: "4-Embarazadas · 20- 49 años", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · A-Física (1+2+3+4+5+6)" },
        { key: "t10_396", label: "5-De 20 a 59 · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · A-Física (1+2+3+4+5+6)" },
        { key: "t10_397", label: "5-De 20 a 59 · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · A-Física (1+2+3+4+5+6)" },
        { key: "t10_398", label: "6-De 60 y más · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · A-Física (1+2+3+4+5+6)" },
        { key: "t10_399", label: "6-De 60 y más · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · A-Física (1+2+3+4+5+6)" },
        { key: "t10_400", label: "1-De 0-9 Años · Niñas", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · B-Psicológica (1+2+3+4+5+6)" },
        { key: "t10_401", label: "1-De 0-9 Años · Niños", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · B-Psicológica (1+2+3+4+5+6)" },
        { key: "t10_402", label: "2-De 10-14 años · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · B-Psicológica (1+2+3+4+5+6)" },
        { key: "t10_403", label: "2-De 10-14 años · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · B-Psicológica (1+2+3+4+5+6)" },
        { key: "t10_404", label: "3-De 15-19 años · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · B-Psicológica (1+2+3+4+5+6)" },
        { key: "t10_405", label: "3-De 15-19 años · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · B-Psicológica (1+2+3+4+5+6)" },
        { key: "t10_406", label: "4-Embarazadas · 10-14 años", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · B-Psicológica (1+2+3+4+5+6)" },
        { key: "t10_407", label: "4-Embarazadas · 15- 19 años", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · B-Psicológica (1+2+3+4+5+6)" },
        { key: "t10_408", label: "4-Embarazadas · 20- 49 años", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · B-Psicológica (1+2+3+4+5+6)" },
        { key: "t10_409", label: "5-De 20 a 59 · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · B-Psicológica (1+2+3+4+5+6)" },
        { key: "t10_410", label: "5-De 20 a 59 · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · B-Psicológica (1+2+3+4+5+6)" },
        { key: "t10_411", label: "6-De 60 y más · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · B-Psicológica (1+2+3+4+5+6)" },
        { key: "t10_412", label: "6-De 60 y más · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · B-Psicológica (1+2+3+4+5+6)" },
      ],
    },
    {
      id: "t11",
      title: "TABULADOR DIARIO DE ACTIVIDADES DE DETECCION DE PERSONAS VICTIMAS DE VIOLENCIA II",
      detailLabel: "Detalle",
      rows: [
        { key: "t11_420", label: "1-De 0- 11 años · Niñas", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · C-Sexual (1+2+3+4+5+6)" },
        { key: "t11_421", label: "1-De 0- 11 años · Niños", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · C-Sexual (1+2+3+4+5+6)" },
        { key: "t11_422", label: "2-De 12-17 años · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · C-Sexual (1+2+3+4+5+6)" },
        { key: "t11_423", label: "2-De 12-17 años · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · C-Sexual (1+2+3+4+5+6)" },
        { key: "t11_424", label: "3-De 18-19 años · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · C-Sexual (1+2+3+4+5+6)" },
        { key: "t11_425", label: "3-De 18-19 años · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · C-Sexual (1+2+3+4+5+6)" },
        { key: "t11_426", label: "4-Embarazadas · 10-14 años", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · C-Sexual (1+2+3+4+5+6)" },
        { key: "t11_427", label: "4-Embarazadas · 15- 19 años", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · C-Sexual (1+2+3+4+5+6)" },
        { key: "t11_428", label: "4-Embarazadas · 20- 49 años", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · C-Sexual (1+2+3+4+5+6)" },
        { key: "t11_429", label: "5-De 20 a 59 · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · C-Sexual (1+2+3+4+5+6)" },
        { key: "t11_430", label: "5-De 20 a 59 · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · C-Sexual (1+2+3+4+5+6)" },
        { key: "t11_431", label: "6-De 60 y más · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · C-Sexual (1+2+3+4+5+6)" },
        { key: "t11_432", label: "6-De 60 y más · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · C-Sexual (1+2+3+4+5+6)" },
        { key: "t11_433", label: "1-De 0-9 Años · Niñas", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · D-Negligencia y Abandono (1+2+3) POR CONDICION DE PACIENTE" },
        { key: "t11_434", label: "1-De 0-9 Años · Niños", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · D-Negligencia y Abandono (1+2+3) POR CONDICION DE PACIENTE" },
        { key: "t11_435", label: "2-De 60 y más · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · D-Negligencia y Abandono (1+2+3) POR CONDICION DE PACIENTE" },
        { key: "t11_436", label: "2-De 60 y más · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · D-Negligencia y Abandono (1+2+3) POR CONDICION DE PACIENTE" },
        { key: "t11_437", label: "3-Personas con Discapacidad · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · D-Negligencia y Abandono (1+2+3) POR CONDICION DE PACIENTE" },
        { key: "t11_438", label: "3-Personas con Discapacidad · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · D-Negligencia y Abandono (1+2+3) POR CONDICION DE PACIENTE" },
        { key: "t11_439", label: "1-De 0-9 Años · Niñas", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · E- Niñas, Niños y Adolescentes en Situación de Trabajo Infantil (1+2+3)" },
        { key: "t11_440", label: "1-De 0-9 Años · Niños", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · E- Niñas, Niños y Adolescentes en Situación de Trabajo Infantil (1+2+3)" },
        { key: "t11_441", label: "2-De 10-14 años · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · E- Niñas, Niños y Adolescentes en Situación de Trabajo Infantil (1+2+3)" },
        { key: "t11_442", label: "2-De 10-14 años · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · E- Niñas, Niños y Adolescentes en Situación de Trabajo Infantil (1+2+3)" },
        { key: "t11_443", label: "3-De 15 a 18 años · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · E- Niñas, Niños y Adolescentes en Situación de Trabajo Infantil (1+2+3)" },
        { key: "t11_444", label: "3-De 15 a 18 años · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · E- Niñas, Niños y Adolescentes en Situación de Trabajo Infantil (1+2+3)" },
        { key: "t11_445", label: "1-De 0-9 Años · Niñas", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · F- Niñas, Niños y Adolescentes en Situación de Calle (1+2+3)" },
        { key: "t11_446", label: "1-De 0-9 Años · Niños", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · F- Niñas, Niños y Adolescentes en Situación de Calle (1+2+3)" },
        { key: "t11_447", label: "2-De 10-14 años · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · F- Niñas, Niños y Adolescentes en Situación de Calle (1+2+3)" },
        { key: "t11_448", label: "2-De 10-14 años · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · F- Niñas, Niños y Adolescentes en Situación de Calle (1+2+3)" },
        { key: "t11_449", label: "3-De 15 a 18 años · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · F- Niñas, Niños y Adolescentes en Situación de Calle (1+2+3)" },
        { key: "t11_450", label: "3-De 15 a 18 años · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · F- Niñas, Niños y Adolescentes en Situación de Calle (1+2+3)" },
      ],
    },
    {
      id: "t12",
      title: "TABULADOR DIARIO DE ACTIVIDADES DE DETECCION DE PERSONAS VICTIMAS DE VIOLENCIA III",
      detailLabel: "Detalle",
      rows: [
        { key: "t12_458", label: "1-De 0 - 9 años · Niñas", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · G-Trata de Personas (1+2+3+4+5+6)" },
        { key: "t12_459", label: "1-De 0 - 9 años · Niños", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · G-Trata de Personas (1+2+3+4+5+6)" },
        { key: "t12_460", label: "2-De 10 -14 años · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · G-Trata de Personas (1+2+3+4+5+6)" },
        { key: "t12_461", label: "2-De 10 -14 años · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · G-Trata de Personas (1+2+3+4+5+6)" },
        { key: "t12_462", label: "3-De 15 -19 años · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · G-Trata de Personas (1+2+3+4+5+6)" },
        { key: "t12_463", label: "3-De 15 -19 años · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · G-Trata de Personas (1+2+3+4+5+6)" },
        { key: "t12_464", label: "4-Embarazadas · 10-14 años", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · G-Trata de Personas (1+2+3+4+5+6)" },
        { key: "t12_465", label: "4-Embarazadas · 15- 19 años", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · G-Trata de Personas (1+2+3+4+5+6)" },
        { key: "t12_466", label: "4-Embarazadas · 20- 49 años", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · G-Trata de Personas (1+2+3+4+5+6)" },
        { key: "t12_467", label: "5-De 20 a 59 · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · G-Trata de Personas (1+2+3+4+5+6)" },
        { key: "t12_468", label: "5-De 20 a 59 · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · G-Trata de Personas (1+2+3+4+5+6)" },
        { key: "t12_469", label: "6-De 60 O + años · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · G-Trata de Personas (1+2+3+4+5+6)" },
        { key: "t12_470", label: "6-De 60 O + años · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · G-Trata de Personas (1+2+3+4+5+6)" },
        { key: "t12_471", label: "1-De 0 - 9 años · Niñas", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · H-Explotación Sexual (1+2+3+4)" },
        { key: "t12_472", label: "1-De 0 - 9 años · Niños", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · H-Explotación Sexual (1+2+3+4)" },
        { key: "t12_473", label: "2-De 10 -14 años · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · H-Explotación Sexual (1+2+3+4)" },
        { key: "t12_474", label: "2-De 10 -14 años · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · H-Explotación Sexual (1+2+3+4)" },
        { key: "t12_475", label: "3-De 15 -19 años · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · H-Explotación Sexual (1+2+3+4)" },
        { key: "t12_476", label: "3-De 15 -19 años · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · H-Explotación Sexual (1+2+3+4)" },
        { key: "t12_477", label: "4-De 20 a 59 años · Niñas", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · H-Explotación Sexual (1+2+3+4)" },
        { key: "t12_478", label: "4-De 20 a 59 años · Niños", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · H-Explotación Sexual (1+2+3+4)" },
        { key: "t12_479", label: "5- De 60 o + años · Mujeres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · H-Explotación Sexual (1+2+3+4)" },
        { key: "t12_480", label: "5- De 60 o + años · Hombres", group: "PERSONAS DETECTADAS EN SITUACION DE VIOLENCIA · H-Explotación Sexual (1+2+3+4)" },
        { key: "t12_481", label: "Junta de Protección de la Niñez y de la Adolescencia", group: "Aviso a instancias Legales" },
        { key: "t12_482", label: "Fiscalía General de la República (FGR)", group: "Aviso a instancias Legales" },
        { key: "t12_483", label: "Policía Nacional Civil", group: "Aviso a instancias Legales" },
      ],
    },
  ],
};
