// AUTO-GENERADO desde "FISIOTERAPIA_1.xlsx" (hoja MES ACTUAL).
// Tabulador SEPS de Fisioterapia, asignado al servicio "terapia-fisica".
// Regenerar con el script de parseo si cambia la plantilla oficial.
import type { SepsTemplate } from "@/lib/seps-templates";

export const FISIOTERAPIA_TEMPLATE: SepsTemplate = {
  serviceId: "terapia-fisica",
  establishment: "HOSPITAL NACIONAL EL SALVADOR",
  tables: [
    {
      id: "t1",
      title: "TABULADOR DIARIO DE PROCEDIMIENTO DE FISIOTERAPIA I",
      detailLabel: "Detalle",
      rows: [
        { key: "t1_7", label: "1) 0 - 7 años", group: "TIPO DE ATENCIÓN (1+2) · 1. PRIMERA VEZ(A+B) · A. Femenino (1+2+3+4+5+6+7+8)" },
        { key: "t1_8", label: "2) 8 - 9 años", group: "TIPO DE ATENCIÓN (1+2) · 1. PRIMERA VEZ(A+B) · A. Femenino (1+2+3+4+5+6+7+8)" },
        { key: "t1_9", label: "3) 10 - 11 años", group: "TIPO DE ATENCIÓN (1+2) · 1. PRIMERA VEZ(A+B) · A. Femenino (1+2+3+4+5+6+7+8)" },
        { key: "t1_10", label: "4) 12 - 14 años", group: "TIPO DE ATENCIÓN (1+2) · 1. PRIMERA VEZ(A+B) · A. Femenino (1+2+3+4+5+6+7+8)" },
        { key: "t1_11", label: "5) 15 - 17años", group: "TIPO DE ATENCIÓN (1+2) · 1. PRIMERA VEZ(A+B) · A. Femenino (1+2+3+4+5+6+7+8)" },
        { key: "t1_12", label: "6) 18 - 19 años", group: "TIPO DE ATENCIÓN (1+2) · 1. PRIMERA VEZ(A+B) · A. Femenino (1+2+3+4+5+6+7+8)" },
        { key: "t1_13", label: "7) 20 - 59 años", group: "TIPO DE ATENCIÓN (1+2) · 1. PRIMERA VEZ(A+B) · A. Femenino (1+2+3+4+5+6+7+8)" },
        { key: "t1_14", label: "8) 60 años y más", group: "TIPO DE ATENCIÓN (1+2) · 1. PRIMERA VEZ(A+B) · A. Femenino (1+2+3+4+5+6+7+8)" },
        { key: "t1_15", label: "1) 0 - 7 años", group: "TIPO DE ATENCIÓN (1+2) · 1. PRIMERA VEZ(A+B) · B. Masculino (1+2+3+4+5+6+7+8)" },
        { key: "t1_16", label: "2) 8 - 9 años", group: "TIPO DE ATENCIÓN (1+2) · 1. PRIMERA VEZ(A+B) · B. Masculino (1+2+3+4+5+6+7+8)" },
        { key: "t1_17", label: "3) 10 - 11 años", group: "TIPO DE ATENCIÓN (1+2) · 1. PRIMERA VEZ(A+B) · B. Masculino (1+2+3+4+5+6+7+8)" },
        { key: "t1_18", label: "4) 12 - 14 años", group: "TIPO DE ATENCIÓN (1+2) · 1. PRIMERA VEZ(A+B) · B. Masculino (1+2+3+4+5+6+7+8)" },
        { key: "t1_19", label: "5) 15 - 17años", group: "TIPO DE ATENCIÓN (1+2) · 1. PRIMERA VEZ(A+B) · B. Masculino (1+2+3+4+5+6+7+8)" },
        { key: "t1_20", label: "6) 18 - 19 años", group: "TIPO DE ATENCIÓN (1+2) · 1. PRIMERA VEZ(A+B) · B. Masculino (1+2+3+4+5+6+7+8)" },
        { key: "t1_21", label: "7) 20 - 59 años", group: "TIPO DE ATENCIÓN (1+2) · 1. PRIMERA VEZ(A+B) · B. Masculino (1+2+3+4+5+6+7+8)" },
        { key: "t1_22", label: "8) 60 años y más", group: "TIPO DE ATENCIÓN (1+2) · 1. PRIMERA VEZ(A+B) · B. Masculino (1+2+3+4+5+6+7+8)" },
        { key: "t1_23", label: "1) 0 - 7 años", group: "TIPO DE ATENCIÓN (1+2) · 2. SUBSECUENTE (A+B) · A. Femenino (1+2+3+4+5+6+7+8)" },
        { key: "t1_24", label: "2) 8 - 9 años", group: "TIPO DE ATENCIÓN (1+2) · 2. SUBSECUENTE (A+B) · A. Femenino (1+2+3+4+5+6+7+8)" },
        { key: "t1_25", label: "3) 10 - 11 años", group: "TIPO DE ATENCIÓN (1+2) · 2. SUBSECUENTE (A+B) · A. Femenino (1+2+3+4+5+6+7+8)" },
        { key: "t1_26", label: "4) 12 - 14 años", group: "TIPO DE ATENCIÓN (1+2) · 2. SUBSECUENTE (A+B) · A. Femenino (1+2+3+4+5+6+7+8)" },
        { key: "t1_27", label: "5) 15 - 17años", group: "TIPO DE ATENCIÓN (1+2) · 2. SUBSECUENTE (A+B) · A. Femenino (1+2+3+4+5+6+7+8)" },
        { key: "t1_28", label: "6) 18 - 19 años", group: "TIPO DE ATENCIÓN (1+2) · 2. SUBSECUENTE (A+B) · A. Femenino (1+2+3+4+5+6+7+8)" },
        { key: "t1_29", label: "7) 20 - 59 años", group: "TIPO DE ATENCIÓN (1+2) · 2. SUBSECUENTE (A+B) · A. Femenino (1+2+3+4+5+6+7+8)" },
        { key: "t1_30", label: "8) 60 años y más", group: "TIPO DE ATENCIÓN (1+2) · 2. SUBSECUENTE (A+B) · A. Femenino (1+2+3+4+5+6+7+8)" },
        { key: "t1_31", label: "1) 0 - 7 años", group: "TIPO DE ATENCIÓN (1+2) · 2. SUBSECUENTE (A+B) · B. Masculino (1+2+3+4+5+6+7+8)" },
        { key: "t1_32", label: "2) 8 - 9 años", group: "TIPO DE ATENCIÓN (1+2) · 2. SUBSECUENTE (A+B) · B. Masculino (1+2+3+4+5+6+7+8)" },
        { key: "t1_33", label: "3) 10 - 11 años", group: "TIPO DE ATENCIÓN (1+2) · 2. SUBSECUENTE (A+B) · B. Masculino (1+2+3+4+5+6+7+8)" },
        { key: "t1_34", label: "4) 12 - 14 años", group: "TIPO DE ATENCIÓN (1+2) · 2. SUBSECUENTE (A+B) · B. Masculino (1+2+3+4+5+6+7+8)" },
        { key: "t1_35", label: "5) 15 - 17años", group: "TIPO DE ATENCIÓN (1+2) · 2. SUBSECUENTE (A+B) · B. Masculino (1+2+3+4+5+6+7+8)" },
        { key: "t1_36", label: "6) 18 - 19 años", group: "TIPO DE ATENCIÓN (1+2) · 2. SUBSECUENTE (A+B) · B. Masculino (1+2+3+4+5+6+7+8)" },
        { key: "t1_37", label: "7) 20 - 59 años", group: "TIPO DE ATENCIÓN (1+2) · 2. SUBSECUENTE (A+B) · B. Masculino (1+2+3+4+5+6+7+8)" },
        { key: "t1_38", label: "8) 60 años y más", group: "TIPO DE ATENCIÓN (1+2) · 2. SUBSECUENTE (A+B) · B. Masculino (1+2+3+4+5+6+7+8)" },
        { key: "t1_39", label: "a) A otro estabecimiento", group: "1- Interconsulta" },
        { key: "t1_40", label: "b) de otro establecimiento", group: "1- Interconsulta" },
        { key: "t1_41", label: "a) A otro estabecimiento", group: "2- Referencia" },
        { key: "t1_42", label: "b) de otro establecimiento", group: "2- Referencia" },
      ],
    },
    {
      id: "t2",
      title: "TABULADOR DIARIO DE PROCEDIMIENTO DE FISIOTERAPIA II",
      detailLabel: "Detalle",
      rows: [
        { key: "t2_48", label: "1) 0 - 7 años", group: "Número de procedimientos · Fisioterapia" },
        { key: "t2_49", label: "2) 8 - 9 años", group: "Número de procedimientos · Fisioterapia" },
        { key: "t2_50", label: "3) 10 - 11 años", group: "Número de procedimientos · Fisioterapia" },
        { key: "t2_51", label: "4) 12 - 14 años", group: "Número de procedimientos · Fisioterapia" },
        { key: "t2_52", label: "5) 15 - 17años", group: "Número de procedimientos · Fisioterapia" },
        { key: "t2_53", label: "6) 18 - 19 años", group: "Número de procedimientos · Fisioterapia" },
        { key: "t2_54", label: "7) 20 - 59 años", group: "Número de procedimientos · Fisioterapia" },
        { key: "t2_55", label: "8) 60 años y más", group: "Número de procedimientos · Fisioterapia" },
        { key: "t2_56", label: "Individual", group: "Número de procedimientos · Fisioterapia · Total de sesiones" },
        { key: "t2_57", label: "grupal", group: "Número de procedimientos · Fisioterapia · Total de sesiones" },
        { key: "t2_58", label: "1) 0 - 7 años", group: "Número de procedimientos · Terapia ocupacional" },
        { key: "t2_59", label: "2) 8 - 9 años", group: "Número de procedimientos · Terapia ocupacional" },
        { key: "t2_60", label: "3) 10 - 11 años", group: "Número de procedimientos · Terapia ocupacional" },
        { key: "t2_61", label: "4) 12 - 14 años", group: "Número de procedimientos · Terapia ocupacional" },
        { key: "t2_62", label: "5) 15 - 17años", group: "Número de procedimientos · Terapia ocupacional" },
        { key: "t2_63", label: "6) 18 - 19 años", group: "Número de procedimientos · Terapia ocupacional" },
        { key: "t2_64", label: "7) 20 - 59 años", group: "Número de procedimientos · Terapia ocupacional" },
        { key: "t2_65", label: "8) 60 años y más", group: "Número de procedimientos · Terapia ocupacional" },
        { key: "t2_66", label: "Individual", group: "Número de procedimientos · Terapia ocupacional · Total de sesiones" },
        { key: "t2_67", label: "grupal", group: "Número de procedimientos · Terapia ocupacional · Total de sesiones" },
        { key: "t2_68", label: "1) 0 - 7 años", group: "Número de procedimientos · Terapia de audición, voz y habla" },
        { key: "t2_69", label: "2) 8 - 9 años", group: "Número de procedimientos · Terapia de audición, voz y habla" },
        { key: "t2_70", label: "3) 10 - 11 años", group: "Número de procedimientos · Terapia de audición, voz y habla" },
        { key: "t2_71", label: "4) 12 - 14 años", group: "Número de procedimientos · Terapia de audición, voz y habla" },
        { key: "t2_72", label: "5) 15 - 17años", group: "Número de procedimientos · Terapia de audición, voz y habla" },
        { key: "t2_73", label: "6) 18 - 19 años", group: "Número de procedimientos · Terapia de audición, voz y habla" },
        { key: "t2_74", label: "7) 20 - 59 años", group: "Número de procedimientos · Terapia de audición, voz y habla" },
        { key: "t2_75", label: "8) 60 años y más", group: "Número de procedimientos · Terapia de audición, voz y habla" },
        { key: "t2_76", label: "Individual", group: "Número de procedimientos · Terapia de audición, voz y habla · Total de sesiones" },
        { key: "t2_77", label: "grupal", group: "Número de procedimientos · Terapia de audición, voz y habla · Total de sesiones" },
        { key: "t2_78", label: "1) 0 - 7 años", group: "Número de procedimientos · Terapia Educativa" },
        { key: "t2_79", label: "2) 8 - 9 años", group: "Número de procedimientos · Terapia Educativa" },
        { key: "t2_80", label: "3) 10 - 11 años", group: "Número de procedimientos · Terapia Educativa" },
        { key: "t2_81", label: "4) 12 - 14 años", group: "Número de procedimientos · Terapia Educativa" },
        { key: "t2_82", label: "5) 15 - 17años", group: "Número de procedimientos · Terapia Educativa" },
        { key: "t2_83", label: "6) 18 - 19 años", group: "Número de procedimientos · Terapia Educativa" },
        { key: "t2_84", label: "7) 20 - 59 años", group: "Número de procedimientos · Terapia Educativa" },
        { key: "t2_85", label: "8) 60 años y más", group: "Número de procedimientos · Terapia Educativa" },
        { key: "t2_86", label: "Total de sesiones individuales", group: "Número de procedimientos · Terapia Educativa" },
        { key: "t2_87", label: "1) 0 - 7 años", group: "Número de procedimientos · Terapia de estimulacion visual y baja visión" },
        { key: "t2_88", label: "2) 8 - 9 años", group: "Número de procedimientos · Terapia de estimulacion visual y baja visión" },
        { key: "t2_89", label: "3) 10 - 11 años", group: "Número de procedimientos · Terapia de estimulacion visual y baja visión" },
        { key: "t2_90", label: "4) 12 - 14 años", group: "Número de procedimientos · Terapia de estimulacion visual y baja visión" },
        { key: "t2_91", label: "5) 15 - 17años", group: "Número de procedimientos · Terapia de estimulacion visual y baja visión" },
        { key: "t2_92", label: "6) 18 - 19 años", group: "Número de procedimientos · Terapia de estimulacion visual y baja visión" },
        { key: "t2_93", label: "7) 20 - 59 años", group: "Número de procedimientos · Terapia de estimulacion visual y baja visión" },
        { key: "t2_94", label: "8) 60 años y más", group: "Número de procedimientos · Terapia de estimulacion visual y baja visión" },
        { key: "t2_95", label: "Total de sesiones individuales", group: "Número de procedimientos · Terapia de estimulacion visual y baja visión" },
      ],
    },
    {
      id: "t3",
      title: "TABULADOR DIARIO DE PROCEDIMIENTO DE FISIOTERAPIA III",
      detailLabel: "Detalle",
      rows: [
        { key: "t3_101", label: "1) 0 - 7 años", group: "C o n d i c i ó n d e a l t a · 1) sin dificultad" },
        { key: "t3_102", label: "2) 8 - 9 años", group: "C o n d i c i ó n d e a l t a · 1) sin dificultad" },
        { key: "t3_103", label: "3) 10 - 11 años", group: "C o n d i c i ó n d e a l t a · 1) sin dificultad" },
        { key: "t3_104", label: "4) 12 - 14 años", group: "C o n d i c i ó n d e a l t a · 1) sin dificultad" },
        { key: "t3_105", label: "5) 15 - 17años", group: "C o n d i c i ó n d e a l t a · 1) sin dificultad" },
        { key: "t3_106", label: "6) 18 - 19 años", group: "C o n d i c i ó n d e a l t a · 1) sin dificultad" },
        { key: "t3_107", label: "7) 20 - 59 años", group: "C o n d i c i ó n d e a l t a · 1) sin dificultad" },
        { key: "t3_108", label: "8) 60 años y más", group: "C o n d i c i ó n d e a l t a · 1) sin dificultad" },
        { key: "t3_109", label: "1) 0 - 7 años", group: "C o n d i c i ó n d e a l t a · 2) con dificultad ligera" },
        { key: "t3_110", label: "2) 8 - 9 años", group: "C o n d i c i ó n d e a l t a · 2) con dificultad ligera" },
        { key: "t3_111", label: "3) 10 - 11 años", group: "C o n d i c i ó n d e a l t a · 2) con dificultad ligera" },
        { key: "t3_112", label: "4) 12 - 14 años", group: "C o n d i c i ó n d e a l t a · 2) con dificultad ligera" },
        { key: "t3_113", label: "5) 15 - 17años", group: "C o n d i c i ó n d e a l t a · 2) con dificultad ligera" },
        { key: "t3_114", label: "6) 18 - 19 años", group: "C o n d i c i ó n d e a l t a · 2) con dificultad ligera" },
        { key: "t3_115", label: "7) 20 - 59 años", group: "C o n d i c i ó n d e a l t a · 2) con dificultad ligera" },
        { key: "t3_116", label: "8) 60 años y más", group: "C o n d i c i ó n d e a l t a · 2) con dificultad ligera" },
        { key: "t3_117", label: "1) 0 - 7 años", group: "C o n d i c i ó n d e a l t a · 3) con dificultad moderada" },
        { key: "t3_118", label: "2) 8 - 9 años", group: "C o n d i c i ó n d e a l t a · 3) con dificultad moderada" },
        { key: "t3_119", label: "3) 10 - 11 años", group: "C o n d i c i ó n d e a l t a · 3) con dificultad moderada" },
        { key: "t3_120", label: "4) 12 - 14 años", group: "C o n d i c i ó n d e a l t a · 3) con dificultad moderada" },
        { key: "t3_121", label: "5) 15 - 17años", group: "C o n d i c i ó n d e a l t a · 3) con dificultad moderada" },
        { key: "t3_122", label: "6) 18 - 19 años", group: "C o n d i c i ó n d e a l t a · 3) con dificultad moderada" },
        { key: "t3_123", label: "7) 20 - 59 años", group: "C o n d i c i ó n d e a l t a · 3) con dificultad moderada" },
        { key: "t3_124", label: "8) 60 años y más", group: "C o n d i c i ó n d e a l t a · 3) con dificultad moderada" },
        { key: "t3_125", label: "1) 0 - 7 años", group: "C o n d i c i ó n d e a l t a · 4) con dificultad grave" },
        { key: "t3_126", label: "2) 8 - 9 años", group: "C o n d i c i ó n d e a l t a · 4) con dificultad grave" },
        { key: "t3_127", label: "3) 10 - 11 años", group: "C o n d i c i ó n d e a l t a · 4) con dificultad grave" },
        { key: "t3_128", label: "4) 12 - 14 años", group: "C o n d i c i ó n d e a l t a · 4) con dificultad grave" },
        { key: "t3_129", label: "5) 15 - 17años", group: "C o n d i c i ó n d e a l t a · 4) con dificultad grave" },
        { key: "t3_130", label: "6) 18 - 19 años", group: "C o n d i c i ó n d e a l t a · 4) con dificultad grave" },
        { key: "t3_131", label: "7) 20 - 59 años", group: "C o n d i c i ó n d e a l t a · 4) con dificultad grave" },
        { key: "t3_132", label: "8) 60 años y más", group: "C o n d i c i ó n d e a l t a · 4) con dificultad grave" },
        { key: "t3_133", label: "1) 0 - 7 años", group: "C o n d i c i ó n d e a l t a · 5) con dificultad completa" },
        { key: "t3_134", label: "2) 8 - 9 años", group: "C o n d i c i ó n d e a l t a · 5) con dificultad completa" },
        { key: "t3_135", label: "3) 10 - 11 años", group: "C o n d i c i ó n d e a l t a · 5) con dificultad completa" },
        { key: "t3_136", label: "4) 12 - 14 años", group: "C o n d i c i ó n d e a l t a · 5) con dificultad completa" },
        { key: "t3_137", label: "5) 15 - 17años", group: "C o n d i c i ó n d e a l t a · 5) con dificultad completa" },
        { key: "t3_138", label: "6) 18 - 19 años", group: "C o n d i c i ó n d e a l t a · 5) con dificultad completa" },
        { key: "t3_139", label: "7) 20 - 59 años", group: "C o n d i c i ó n d e a l t a · 5) con dificultad completa" },
        { key: "t3_140", label: "8) 60 años y más", group: "C o n d i c i ó n d e a l t a · 5) con dificultad completa" },
      ],
    },
    {
      id: "t4",
      title: "TABULADOR DIARIO DE PROCEDIMIENTOS DE FISIOTERAPIA IV",
      detailLabel: "Detalle",
      rows: [
        { key: "t4_146", label: "1) 0 - 7 años", group: "Grado de dependencia funcional al alta · 1) Total" },
        { key: "t4_147", label: "2) 8 - 9 años", group: "Grado de dependencia funcional al alta · 1) Total" },
        { key: "t4_148", label: "3) 10 - 11 años", group: "Grado de dependencia funcional al alta · 1) Total" },
        { key: "t4_149", label: "4) 12 - 14 años", group: "Grado de dependencia funcional al alta · 1) Total" },
        { key: "t4_150", label: "5) 15 - 17años", group: "Grado de dependencia funcional al alta · 1) Total" },
        { key: "t4_151", label: "6) 18 - 19 años", group: "Grado de dependencia funcional al alta · 1) Total" },
        { key: "t4_152", label: "7) 20 - 59 años", group: "Grado de dependencia funcional al alta · 1) Total" },
        { key: "t4_153", label: "8) 60 años y más", group: "Grado de dependencia funcional al alta · 1) Total" },
        { key: "t4_154", label: "1) 0 - 7 años", group: "Grado de dependencia funcional al alta · 2) Grave" },
        { key: "t4_155", label: "2) 8 - 9 años", group: "Grado de dependencia funcional al alta · 2) Grave" },
        { key: "t4_156", label: "3) 10 - 11 años", group: "Grado de dependencia funcional al alta · 2) Grave" },
        { key: "t4_157", label: "4) 12 - 14 años", group: "Grado de dependencia funcional al alta · 2) Grave" },
        { key: "t4_158", label: "5) 15 - 17años", group: "Grado de dependencia funcional al alta · 2) Grave" },
        { key: "t4_159", label: "6) 18 - 19 años", group: "Grado de dependencia funcional al alta · 2) Grave" },
        { key: "t4_160", label: "7) 20 - 59 años", group: "Grado de dependencia funcional al alta · 2) Grave" },
        { key: "t4_161", label: "8) 60 años y más", group: "Grado de dependencia funcional al alta · 2) Grave" },
        { key: "t4_162", label: "1) 0 - 7 años", group: "Grado de dependencia funcional al alta · 3) Moderada" },
        { key: "t4_163", label: "2) 8 - 9 años", group: "Grado de dependencia funcional al alta · 3) Moderada" },
        { key: "t4_164", label: "3) 10 - 11 años", group: "Grado de dependencia funcional al alta · 3) Moderada" },
        { key: "t4_165", label: "4) 12 - 14 años", group: "Grado de dependencia funcional al alta · 3) Moderada" },
        { key: "t4_166", label: "5) 15 - 17años", group: "Grado de dependencia funcional al alta · 3) Moderada" },
        { key: "t4_167", label: "6) 18 - 19 años", group: "Grado de dependencia funcional al alta · 3) Moderada" },
        { key: "t4_168", label: "7) 20 - 59 años", group: "Grado de dependencia funcional al alta · 3) Moderada" },
        { key: "t4_169", label: "8) 60 años y más", group: "Grado de dependencia funcional al alta · 3) Moderada" },
        { key: "t4_170", label: "1) 0 - 7 años", group: "Grado de dependencia funcional al alta · 4) Leve" },
        { key: "t4_171", label: "2) 8 - 9 años", group: "Grado de dependencia funcional al alta · 4) Leve" },
        { key: "t4_172", label: "3) 10 - 11 años", group: "Grado de dependencia funcional al alta · 4) Leve" },
        { key: "t4_173", label: "4) 12 - 14 años", group: "Grado de dependencia funcional al alta · 4) Leve" },
        { key: "t4_174", label: "5) 15 - 17años", group: "Grado de dependencia funcional al alta · 4) Leve" },
        { key: "t4_175", label: "6) 18 - 19 años", group: "Grado de dependencia funcional al alta · 4) Leve" },
        { key: "t4_176", label: "7) 20 - 59 años", group: "Grado de dependencia funcional al alta · 4) Leve" },
        { key: "t4_177", label: "8) 60 años y más", group: "Grado de dependencia funcional al alta · 4) Leve" },
        { key: "t4_178", label: "1) 0 - 7 años", group: "Grado de dependencia funcional al alta · 5) Independiente" },
        { key: "t4_179", label: "2) 8 - 9 años", group: "Grado de dependencia funcional al alta · 5) Independiente" },
        { key: "t4_180", label: "3) 10 - 11 años", group: "Grado de dependencia funcional al alta · 5) Independiente" },
        { key: "t4_181", label: "4) 12 - 14 años", group: "Grado de dependencia funcional al alta · 5) Independiente" },
        { key: "t4_182", label: "5) 15 - 17años", group: "Grado de dependencia funcional al alta · 5) Independiente" },
        { key: "t4_183", label: "6) 18 - 19 años", group: "Grado de dependencia funcional al alta · 5) Independiente" },
        { key: "t4_184", label: "7) 20 - 59 años", group: "Grado de dependencia funcional al alta · 5) Independiente" },
        { key: "t4_185", label: "8) 60 años y más", group: "Grado de dependencia funcional al alta · 5) Independiente" },
      ],
    },
    {
      id: "t5",
      title: "TABULADOR DIARIO DE FISIOTERAPIA V - RESUMEN (GRUPO 1/2/3)",
      detailLabel: "Detalle",
      rows: [
        { key: "t5_191", label: "1. Consulta Externa", group: "GENERAL · Servicios de Procedencia" },
        { key: "t5_192", label: "2. Hospitalización", group: "GENERAL · Servicios de Procedencia" },
        { key: "t5_193", label: "3. Emergencia", group: "GENERAL · Servicios de Procedencia" },
        { key: "t5_194", label: "Número de procedimientos", group: "GENERAL · Procedimientos" },
        { key: "t5_196", label: "1. Individual", group: "GENERAL · Sesiones Realizadas" },
        { key: "t5_197", label: "2. Grupal", group: "GENERAL · Sesiones Realizadas" },
        { key: "t5_198", label: "1. Rehabilitado", group: "GENERAL · Tipos de Altas" },
        { key: "t5_199", label: "2. Voluntaria", group: "GENERAL · Tipos de Altas" },
        { key: "t5_200", label: "3. Defunción", group: "GENERAL · Tipos de Altas" },
        { key: "t5_201", label: "4. Referido a otro establecimiento", group: "GENERAL · Tipos de Altas" },
        { key: "t5_202", label: "1. No hay dificultad", group: "GENERAL · Condición de alta" },
        { key: "t5_203", label: "2. Dificultad Ligera", group: "GENERAL · Condición de alta" },
        { key: "t5_204", label: "3. Dificultad moderada", group: "GENERAL · Condición de alta" },
        { key: "t5_205", label: "4. Dificultad grave", group: "GENERAL · Condición de alta" },
        { key: "t5_206", label: "5. Dificultad completa", group: "GENERAL · Condición de alta" },
        { key: "t5_207", label: "1. A otro establecimiento", group: "GENERAL · Interconsulta" },
        { key: "t5_208", label: "2. De otro establecimiento", group: "GENERAL · Interconsulta" },
        { key: "t5_209", label: "Referencia de otro Establecimiento de Salud", group: "GENERAL · Referencia de otro establecimiento" },
      ],
    },
    {
      id: "t6",
      title: "ATENCIONES ESPECIFICAS DE DOLOR Y CUIDADOS PALIATIVOS",
      detailLabel: "Detalle",
      rows: [
        { key: "t6_256", label: "Terapia física", group: "II. Atención de primera y subsecuente · Rehabilitacion y habiltación · Terapia FISIOTERAPIA" },
        { key: "t6_257", label: "Terapia ocupacional", group: "II. Atención de primera y subsecuente · Rehabilitacion y habiltación · Terapia FISIOTERAPIA" },
      ],
    },
    {
      id: "t7",
      title: "TABULADOR DIARIO DE ATENCIONES GRUPALES DE SALUD MENTAL III",
      detailLabel: "Detalle",
      rows: [
        { key: "t7_265", label: "Masculino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional/ FISIOTERAPIA · 0 a 7 años" },
        { key: "t7_266", label: "Femenino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional/ FISIOTERAPIA · 0 a 7 años" },
        { key: "t7_267", label: "Masculino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional/ FISIOTERAPIA · 8 a 9 años" },
        { key: "t7_268", label: "Femenino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional/ FISIOTERAPIA · 8 a 9 años" },
        { key: "t7_269", label: "Masculino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional/ FISIOTERAPIA · 10 a 11 años" },
        { key: "t7_270", label: "Femenino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional/ FISIOTERAPIA · 10 a 11 años" },
        { key: "t7_271", label: "Masculino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional/ FISIOTERAPIA · 12 a 17 años" },
        { key: "t7_272", label: "Femenino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional/ FISIOTERAPIA · 12 a 17 años" },
        { key: "t7_273", label: "Masculino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional/ FISIOTERAPIA · 18 a 19 años" },
        { key: "t7_274", label: "Femenino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional/ FISIOTERAPIA · 18 a 19 años" },
        { key: "t7_275", label: "Masculino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional/ FISIOTERAPIA · 20 a 59 años" },
        { key: "t7_276", label: "Femenino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional/ FISIOTERAPIA · 20 a 59 años" },
        { key: "t7_277", label: "Masculino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional/ FISIOTERAPIA · 60 años a más" },
        { key: "t7_278", label: "Femenino", group: "ATENCIÓN ESPECIALIZADA · 8. Terapia ocupacional/ FISIOTERAPIA · 60 años a más" },
      ],
    },
    {
      id: "t8",
      title: "TABULADOR DIARIO DE ACTIVIDADES DE PROMOCIÓN DE LA SALUD VIII",
      detailLabel: "Detalle",
      rows: [
        { key: "t8_288", label: "Mujeres", group: "SESIONES EDUCATIVAS · Actividad física · 0 - 7 años" },
        { key: "t8_289", label: "Hombres", group: "SESIONES EDUCATIVAS · Actividad física · 0 - 7 años" },
        { key: "t8_290", label: "Mujeres", group: "SESIONES EDUCATIVAS · Actividad física · 8 - 9 años" },
        { key: "t8_291", label: "Hombres", group: "SESIONES EDUCATIVAS · Actividad física · 8 - 9 años" },
        { key: "t8_292", label: "Mujeres", group: "SESIONES EDUCATIVAS · Actividad física · 10 - 11 años" },
        { key: "t8_293", label: "Hombres", group: "SESIONES EDUCATIVAS · Actividad física · 10 - 11 años" },
        { key: "t8_294", label: "Mujeres", group: "SESIONES EDUCATIVAS · Actividad física · 12 - 14 años" },
        { key: "t8_295", label: "Hombres", group: "SESIONES EDUCATIVAS · Actividad física · 12 - 14 años" },
        { key: "t8_296", label: "Mujeres", group: "SESIONES EDUCATIVAS · Actividad física · 15 - 17 años" },
        { key: "t8_297", label: "Hombres", group: "SESIONES EDUCATIVAS · Actividad física · 15 - 17 años" },
        { key: "t8_298", label: "Mujeres", group: "SESIONES EDUCATIVAS · Actividad física · 18 - 19 años" },
        { key: "t8_299", label: "Hombres", group: "SESIONES EDUCATIVAS · Actividad física · 18 - 19 años" },
        { key: "t8_300", label: "Mujeres", group: "SESIONES EDUCATIVAS · Actividad física · 20-59 años" },
        { key: "t8_301", label: "Hombres", group: "SESIONES EDUCATIVAS · Actividad física · 20-59 años" },
        { key: "t8_302", label: "Mujeres", group: "SESIONES EDUCATIVAS · Actividad física · 60 años y más" },
        { key: "t8_303", label: "Hombres", group: "SESIONES EDUCATIVAS · Actividad física · 60 años y más" },
        { key: "t8_304", label: "Salud Materna", group: "SESIONES EDUCATIVAS · Actividad física · Sesiones con grupos" },
        { key: "t8_305", label: "Salud infantil", group: "SESIONES EDUCATIVAS · Actividad física · Sesiones con grupos" },
        { key: "t8_306", label: "Adolescentes", group: "SESIONES EDUCATIVAS · Actividad física · Sesiones con grupos" },
        { key: "t8_307", label: "Adultos mayores", group: "SESIONES EDUCATIVAS · Actividad física · Sesiones con grupos" },
        { key: "t8_308", label: "Autoayuda de personas con enfermedades no transmisibles y factores de riesgo", group: "SESIONES EDUCATIVAS · Actividad física · Sesiones con grupos" },
        { key: "t8_309", label: "Otro grupo organizado", group: "SESIONES EDUCATIVAS · Actividad física · Sesiones con grupos" },
        { key: "t8_310", label: "Total de sesiones", group: "SESIONES EDUCATIVAS · Actividad física · Sesiones con grupos" },
      ],
    },
  ],
};
