// AUTO-GENERADO desde "MAYO 2026 LAB.xlsx". SEPS de Laboratorio (formato matricial:
// filas = examenes; columnas = RESULTADOS (suman "total") y PROCEDENCIA (suman "TOTAL").
import type { SepsTemplate } from "@/lib/seps-templates";

export const LABORATORIO_TEMPLATE: SepsTemplate = {
  serviceId: "laboratorio-clinico",
  establishment: "HOSPITAL NACIONAL EL SALVADOR",
  kind: "matrix",
  sections: [
    {
      title: "Hematología",
      exams: [
        { key: "h-5", code: "H-5", name: "RETICULOCITOS" },
        { key: "h-6", code: "H-6", name: "RECUENTO DE PLAQUETAS" },
        { key: "h-7", code: "H-7", name: "FROTIS DE SANGRE PERIFERICA" },
        { key: "h-8", code: "H-8", name: "VELOCIDAD DE ERITROSEDIMENTACION" },
        { key: "h-11", code: "H-11", name: "PRUEBA PARA DETERMINACION DE TIEMPO DE PROTOMBINA (TP) CON INDICE DE SENSIBILIDAD INTERNACIONAL DE (1.0 - 1.2), METODO AUTOMATIZADO." },
        { key: "h-12", code: "H-12", name: "PRUEBA PARA DETERMINACION DE TIEMPO DE TROMBOPLASTINA PARCIAL ACTIVADO (TTP), METODO AUTOMATIZADO." },
        { key: "h-13", code: "H-13", name: "PRUEBA PARA DETERMINACION DE TIEMPO DE TROMBINA (TT), METODO AUTOMATIZADO." },
        { key: "h-14", code: "H-14", name: "PRUEBA PARA LA DETERMINACION DE ANTITROMBINA III, METODO AUTOMATIZADO" },
        { key: "h-20", code: "H-20", name: "DETERMINACION DE FIBRINOGENO, METODO AUTOMATIZADO" },
        { key: "h-23", code: "H-23", name: "GOTA GRUESA PLASMODIUM" },
        { key: "h-50", code: "H-50", name: "PRUEBA PARA LA DETERMINACION DE ANTICOAGULANTE LUPICO (LA1), METODO AUTOMATIZADO" },
        { key: "h-51", code: "H-51", name: "PRUEBA PARA DETERMINACION DE DIMERO-D, METODO AUTOMATIZADO." },
      ],
    },
    {
      title: "Inmunología",
      exams: [
        { key: "i-5", code: "I-5", name: "ANTIESTREPTOLISINA \"O\"" },
        { key: "i-9", code: "I-9", name: "DETERMINACION DE HORMONA FOLICULO ESTIMULANTE (FSH), METODO AUTOMATIZADO" },
        { key: "i-10", code: "I-10", name: "PRUEBA RAPIDA PARA DETERMINACION DE GONADOTROPINA CORIONICA EN SANGRE U ORINA, SET DE 100 PRUEBAS" },
        { key: "i-11", code: "I-11", name: "GONADOTROPINA CORIONICA CUANTITATIVA (ßHCG), METODO AUTOMATIZADO" },
        { key: "i-14", code: "I-14", name: "PRUEBA PARA LA DETERMINACION DE PROTEINA C REACTIVA (PCR), METODO AUTOMATIZADO." },
        { key: "i-18", code: "I-18", name: "PRUEBA PARA DETERMINACION DE FACTOR REUMATOIDEO (RF), METODO AUTOMATIZADO." },
        { key: "i-19", code: "I-19", name: "ANTICUERPOS PARA TOXOPLASMA GONDII IgM" },
        { key: "i-20", code: "I-20", name: "PRUEBA PARA LA DETERMINACION DE PROLACTINA, METODO AUTOMATIZADO" },
        { key: "i-21", code: "I-21", name: "HORMONA LUTEINIZANTE (L.H.)" },
        { key: "i-25", code: "I-25", name: "T3 TOTAL" },
        { key: "i-26", code: "I-26", name: "T4 TOTAL" },
        { key: "i-27", code: "I-27", name: "ANTICUERPOS PARA TOXOPLASMA GONDII IgG" },
        { key: "i-28", code: "I-28", name: "PRUEBA PARA LA DETERMINACION DE LA HORMONA ESTIMULANTE DEL TIROIDES (TSH), METODO AUTOMATIZADO." },
        { key: "i-36", code: "I-36", name: "TESTOSTERONA" },
        { key: "i-42", code: "I-42", name: "PRUEBA PARA LA DETERMINACION DE MARCADOR TUMORAL, ANTIGENO CARCINOEMBRIONARIO (CEA)" },
        { key: "i-47", code: "I-47", name: "PRUEBA PARA DETERMINACION DE MARCADOR TUMORAL ANTIGENO PROSTATICO ESPECIFICO TOTAL (PSA), METODO AUTOMATIZADO." },
        { key: "i-49", code: "I-49", name: "PRUEBA PARA LA DETERMINACION DE MIOGLOBINA, METODO AUTOMATIZADO" },
        { key: "i-52", code: "I-52", name: "CITOMEGALOVIRUS (CMV) IgM" },
        { key: "i-55", code: "I-55", name: "TIROGLOBULINA" },
        { key: "i-56", code: "I-56", name: "PRUEBA PARA LA DETERMINACION DE ANCUERPOS ANTITIROGLOBULINA, METODO AUTOMATIZADO" },
        { key: "i-57", code: "I-57", name: "PRUEBA PARA LA DETERMINACION DE ANCUERPOS ANTIPEROXIDASA TIROIDEA, METODO AUTOMATIZADO" },
        { key: "i-54", code: "I-54", name: "PRUEBA PARA LA DETERMINACION DE ANTI DNA-NATIVO" },
        { key: "i-64", code: "I-64", name: "CITOMEGALOVIRUS (CMV) IgG" },
        { key: "i-65", code: "I-65", name: "PRUEBA PARA LA DETERMINACION DE CA 19-9, METODO AUTOMATIZADO." },
        { key: "i-66", code: "I-66", name: "PRUEBA PARA LA DETERMINACION DE CA 125, METODO AUTOMATIZADO" },
        { key: "i-67", code: "I-67", name: "PRUEBA PARA LA DETERMINACION DE CA 15-3, METODO AUTOMATIZADO" },
        { key: "i-71", code: "I-71", name: "HORMONA PARATIROIDEA (PTH)" },
        { key: "i-73", code: "I-73", name: "PRUEBA PARA DETERMINACION DE INTERLEUCINA 6" },
        { key: "i-77", code: "I-77", name: "PRUEBA RAPIDA PARA LA DETECCION CUALITATIVA DE ANTICUERPOS IgG ESPECIFICIOS DE HELICOBACTER PYLORI, METODO INMUNO" },
        { key: "i-79", code: "I-79", name: "PRUEBA RAPIDA PARA LA DETERMINACION DE Ag COVID-19" },
        { key: "i-80", code: "I-80", name: "PRUEBA DE PEPTIDOS NATRIURETICOS" },
        { key: "i-89", code: "I-89", name: "PRUEBA PARA LA DETERMINACION PROGESTERONA" },
        { key: "i-95", code: "I-95", name: "PRUEBA ANA SCREEN" },
        { key: "i-96", code: "I-96", name: "PRUEBA PARA LA DETERMINACION DE TETRAYODOTIRONINA LIBRE (T4), METODO AUTOMATIZADO." },
        { key: "i-97", code: "I-97", name: "PRUEBA PARA DETERMINACION DE TRIYODOTIRONINA LIBRE (T3), METODO AUTOMATIZADO" },
        { key: "i-99", code: "I-99", name: "PRUEBA PARA LA DETERMINACION DE NIVELES SERICOS DE VITAMINA D" },
        { key: "i-100", code: "I-100", name: "PRUEBA PARA LA DETERMINACION DE NIVELES SERICOS DE ERYTROPOYETINA" },
        { key: "i-101", code: "I-101", name: "PRUEBA PARA LA DETERMINACION DE HORMONAS ANTIMULLERIANA" },
        { key: "i-102", code: "I-102", name: "PRUEBA PARA LA DETERMINACION DE MARCADOR TUMORAL BETA 2 MICROGLOBULINAS" },
        { key: "i-103", code: "I-103", name: "PRUEBA RAPIDA PARA DENGUE, SIMULTANEA PARA ANTIGENO NS1 Y ANTICUERPO IgG/IgM" },
        { key: "i-105", code: "I-105", name: "ANTICARDIOLIPINA IGM" },
        { key: "i-106", code: "I-106", name: "ANTICARDIOLIPINA IGG" },
        { key: "i-110", code: "I-110", name: "PSA LIBRE" },
        { key: "i-111", code: "I-111", name: "INTERFERON GAMMA PARA TUBERCULOSIS" },
        { key: "i-112", code: "I-112", name: "EPSTEIN BARR IgM" },
        { key: "i-113", code: "I-113", name: "HEPATITIS B CONFIRMATORIA" },
      ],
    },
    {
      title: "Química",
      exams: [
        { key: "q-1", code: "Q-1", name: "PRUEBA PARA LA DETERMINACION DE GLUCOSA, METODO AUTOMATIZADO" },
        { key: "q-2", code: "Q-2", name: "PRUEBA PARA LA DETERMINACION DE GLUCOSA POST-PRANDIAL METODO AUTOMATIZADO" },
        { key: "q-4", code: "Q-4", name: "PRUEBA PARA LA DETERMINACION DE ACIDO URICO, METODO AUTOMATIZADO." },
        { key: "q-5", code: "Q-5", name: "PRUEBA PARA LA DETERMINACION DE CREATININA, METODO AUTOMATIZADO" },
        { key: "q-6", code: "Q-6", name: "PRUEBA PARA LA DETERMINACION DE UREA (NITROGENO UREICO), METODO AUTOMATIZADO." },
        { key: "q-15", code: "Q-15", name: "PRUEBA PARA LA DETERMINACION DE BILIRRUBINA TOTAL, METODO AUTOMATIZADO" },
        { key: "q-66", code: "Q-66", name: "PRUEBA PARA LA DETERMINACION DE BILIRRUBINA DIRECTA, METODO AUTOMATIZADO." },
        { key: "q-8", code: "Q-8", name: "PRUEBA PARA LA DETERMINACION DE PROTEINAS TOTALES, METODO AUTOMATIZADO." },
        { key: "q-9", code: "Q-9", name: "PRUEBA PARA LA DETERMINACION DE ALBUMINA, METODO AUTOMATIZADO" },
        { key: "q-10", code: "Q-10", name: "PRUEBA PARA LA DETERMINACION DE COLESTEROL TOTAL, METODO AUTOMATIZADO" },
        { key: "q-11", code: "Q-11", name: "PRUEBA PARA LA DETERMINACION DE COLESTEROL DE ALTA DENSIDAD (HDL), METODO AUTOMATIZADO." },
        { key: "q-12", code: "Q-12", name: "PRUEBA PARA LA DETERMINACION DE COLESTEROL DE BAJA DENSIDAD (LDL), METODO AUTOMATIZADO." },
        { key: "q-13", code: "Q-13", name: "PRUEBA PARA LA DETERMINACION DE TRIGLICERIDOS, METODO AUTOMATIZADO" },
        { key: "q-16", code: "Q-16", name: "PRUEBA PARA LA DETERMINACION DE HIERRO SERICO, METODO AUTOMATIZADO" },
        { key: "q-17", code: "Q-17", name: "DTERMINACION DE CAPACIDAD DE FIJACION DE HIERRO (IBCT), METODO AUTOMATIZADO" },
        { key: "q-21", code: "Q-21", name: "PRUEBA PARA DETERMINACION DE MAGNESIO, METODO AUTOMATIZADO" },
        { key: "q-22", code: "Q-22", name: "PRUEBA PARA DETERMINACION DE CALCIO, METODO AUTOMATIZADO." },
        { key: "q-23", code: "Q-23", name: "PRUEBA PARA LA DETERMINACION DE FOSFORO, METODO AUTOMATIZADO." },
        { key: "q-26", code: "Q-26", name: "PRUEBA PARA LA DETERMINACION DE ALANINA AMINOTRANSFERASA (ALAT) O TRANSAMINASA GLUTAMICA PIRUVICA, METODO AUTOMATIZADO" },
        { key: "q-27", code: "Q-27", name: "PRUEBA PARA LA DETERMINACION DE ASPARTATO AMINOTRANSFERASA (ASAT) O TRANSAMINASA GLUTAMICA OXALACETICA, METODO AUTOMATIZADO" },
        { key: "q-28", code: "Q-28", name: "PRUEBA PARA LA DETERMINACION DE FOSFATASA ALCALINA, METODO AUTOMATIZADO." },
        { key: "q-31", code: "Q-31", name: "PRUEBA PARA LA DETERMINACION DE DESHIDROGENASA LACTICA (LDH), METODO AUTOMATIZADO." },
        { key: "q-32", code: "Q-32", name: "PRUEBA PARA DETERMINACION DE CREATIN FOSFOQUINASA TOTAL (CPK) METODO AUTOMATIZADO." },
        { key: "q-33", code: "Q-33", name: "PRUEBA PARA LA DETERMINACION DE AMILASA, METODO AUTOMATIZADO." },
        { key: "q-71", code: "Q-71", name: "PRUEBA PARA LA DETERMINACION DE NIVELES SERICOS DE FENOBARBITAL, METODO AUTOMATIZADO" },
        { key: "q-72", code: "Q-72", name: "PRUEBA PARA LA DETERMINACION DE NIVELES SERICOS DE FENITOINA, METODO AUTOMATIZADO" },
        { key: "q-74", code: "Q-74", name: "PRUEBA PARA LA DETERMINACION DE CORTISOL, METODO AUTOMATIZADO" },
        { key: "q-75", code: "Q-75", name: "PRUEBA PARA LA DETERMINACION DE NIVELES SERICOS DE INSULINA, METODO AUTOMATIZADO" },
        { key: "q-78", code: "Q-78", name: "PRUEBA PARA LA DETERMINACION DE NIVELES SERICOS DE ACIDO VALPROICO, METODO AUTOMATIZADO" },
        { key: "q-79", code: "Q-79", name: "PRUEBA PARA LA DETERMINACION DE NIVELES DE DIGOXINA" },
        { key: "q-84", code: "Q-84", name: "LACTATO" },
        { key: "q-85", code: "Q-85", name: "PRUEBA PARA LA DETERMINACION DE NIVELES SERICOS DE FERRITINA, METODO AUTOMATIZADO." },
        { key: "q-86", code: "Q-86", name: "NIVELES SERICOS DE VITAMINA B-12" },
        { key: "q-87", code: "Q-87", name: "NIVELES SERICOS DE FOLATO" },
        { key: "q-90", code: "Q-90", name: "PRUEBA PARA LA DETERMINACION DE NIVELES SERICOS DE ESTRADIOL, METODO AUTOMATIZADO" },
        { key: "q-91", code: "Q-91", name: "PRUEBA PARA LA DETERMINACION DE NIVELES SERICOS DE CARBAPAZEPINA, METODO AUTOMATIZADO" },
        { key: "q-103", code: "Q-103", name: "PRUEBA PARA LA DETERMINACION DE ELECTROLITROS: SODIO (Na), POTASIO (K), CLORO (Cl) O CALCIO (Ca), METODO AUTOMATIZADO" },
        { key: "q-106", code: "Q-106", name: "PRUEBA PARA LA DETERMINACION DE AFP, METODO AUTOMATIZADO." },
        { key: "q-108", code: "Q-108", name: "PRUEBA PARA DETERMINACION DE HEMOGLOBINA GLICOSILADA (A1C), METODO AUTOMATIZADO" },
        { key: "q-111", code: "Q-111", name: "PRUEBA PARA DETERMINACION DE GAMMA GLUTAMIL TRANSFERASA (GGT), METODO AUTOMATIZADO" },
        { key: "q-112", code: "Q-112", name: "PRUEBA PARA DETERMINACION DE LIPASA, METODO AUTOMATIZADO." },
        { key: "q-113", code: "Q-113", name: "PRUEBA PARA DETERMINACION DE CREATIN QUINASA FRACCION (MB), METODO AUTOMATIZADO." },
        { key: "q-114", code: "Q-114", name: "PRUEBA PARA DETERMINACION DE TROPONINA I (PLACA), METODO AUTOMATIZADO." },
        { key: "q-118", code: "Q-118", name: "PRUEBA PARA LA DETERMINACION DE CISTATINA C" },
        { key: "q-120", code: "Q-120", name: "PRUEBA PARA LA DETERMINACION DE PROCALCITONINA, METODO AUTOMATIZADO" },
        { key: "q-121", code: "Q-121", name: "PRUEBA PARA LA DETERMINACION DE NIVELES SERICOS DE TRANSFERRINA, METODO AUTOMATIZADO" },
        { key: "q-133", code: "Q-133", name: "INSULINA POST- PRANDIAL" },
        { key: "q-96", code: "Q-96", name: "PRUEBA PARA LA DETERMINACION DE MICROPROTEINAS EN ORINA Y LIQUIDO CEFALORAQUIDEO (LCR), METODO AUTOMATIZADO" },
        { key: "q-40", code: "Q-40", name: "ACIDO URICO EN ORINA" },
        { key: "q-42", code: "Q-42", name: "CALCIO EN ORINA" },
        { key: "q-43", code: "Q-43", name: "FOSFORO EN ORINA" },
        { key: "q-44", code: "Q-44", name: "PROTEINAS EN ORINA DE 24 HORAS" },
        { key: "q-45", code: "Q-45", name: "DEPURACION DE CREATININA" },
        { key: "q-47", code: "Q-47", name: "GLUCOSA EN ORINA" },
        { key: "q-50", code: "Q-50", name: "LIQUIDO CEFALORRAQUIDEO (CITOQUIMICO)" },
        { key: "q-59", code: "Q-59", name: "CITOQUIMICIO LIQUIDO DERRAME (LIQ. PERITONEAL)" },
        { key: "q-65", code: "Q-65", name: "GLOBULINAS" },
        { key: "q-68", code: "Q-68", name: "Na EN ORINA" },
        { key: "q-69", code: "Q-69", name: "CREATININA EN ORINA" },
        { key: "q-70", code: "Q-70", name: "K EN ORINA" },
        { key: "q-93", code: "Q-93", name: "MAGNESIO EN ORINA" },
        { key: "q-94", code: "Q-94", name: "NITROGENO UREICO EN ORINA" },
        { key: "q-98", code: "Q-98", name: "NITROGENO UREICO EN ORINA DE 24 HORAS" },
        { key: "q-97", code: "Q-97", name: "CLORO EN ORINA" },
      ],
    },
    {
      title: "Uroanálisis",
      exams: [
        { key: "u-1", code: "U-1", name: "TIRA REACTIVA PARA LA DETERMINACION SIMULTANEA DE DIFERENTES S+USTANCIAS QUIMICAS EN ORINA, NO MENOR DE DIEZ PARAMETROS, EN EQUIPO AUTOMATIZADO, FRASCO 100 TIRAS" },
      ],
    },
    {
      title: "Microbiología",
      exams: [
        { key: "m-105", code: "M-105", name: "COLORACION PARA INVESTIGACION DE HONGOS" },
        { key: "m-107", code: "M-107", name: "PANEL SEPSIS" },
        { key: "m-108", code: "M-108", name: "PANEL MENINGITIS" },
        { key: "m-109", code: "M-109", name: "PANEL GASTROINTESTINAL" },
        { key: "m-110", code: "M-110", name: "PANEL NEUMONIA" },
        { key: "m-111", code: "M-111", name: "PANEL RESPIRATORIO" },
        { key: "m-13", code: "M-13", name: "CULTIVO EXUDADO, TRASUDADO EMPIEMA Y LAVADOS" },
        { key: "m-15", code: "M-15", name: "CULTIVO CONTROL DE CALIDAD INTERNO" },
        { key: "m-17", code: "M-17", name: "COPROCULTIVO" },
        { key: "m-18", code: "M-18", name: "UROCULTIVO" },
        { key: "m-19", code: "M-19", name: "FRASCO PARA HEMOCULTIVO PARA ADULTO DE TRIPTICASA SOYA CON POLIANETOL SULFONATO DE SODIO (SPS), BIOXIDO DE CARBONO ( CO2) AL VACIO, FRASCO CON (20 -90) MILILITROS DE MEDIO, COMPATIBLE CON EQUIPO AUTOMATIZADO" },
        { key: "m-22", code: "M-22", name: "COLORACION DE GRAM" },
        { key: "m-24", code: "M-24", name: "ANTIBIOGRAMA" },
        { key: "m-26", code: "M-26", name: "DIRECTO KOH" },
        { key: "m-28", code: "M-28", name: "DIRECTO TINTA CHINA" },
        { key: "m-35", code: "M-35", name: "CULTIVO OTRAS BACTERIAS" },
        { key: "m-3", code: "M-3", name: "CULTIVO PARA VIBRIO CHOLERAE" },
        { key: "m-5", code: "M-5", name: "CULTIVO DE LCR" },
        { key: "m-61", code: "M-61", name: "IDENTIFICACION HONGOS MICELIALES" },
        { key: "m-62", code: "M-62", name: "IDENTIFICACION HONGOS LEVADURIFORMES" },
        { key: "m-66", code: "M-66", name: "PRUEBAS BIOQUIMICAS" },
        { key: "m-67", code: "M-67", name: "Ph CULTIVOS" },
        { key: "m-68", code: "M-68", name: "CULTIVO CRITERIOS TECNICOS" },
        { key: "m-69", code: "M-69", name: "PRUEBA PARA DETECCION DE CARBAPENEMASAS EN BACTERIAS GRAM NEGATIVAS" },
        { key: "m-73", code: "M-73", name: "RESIEMBRA BACTERIANA" },
        { key: "m-8", code: "M-8", name: "CULTIVO DE SECRECIONES" },
        { key: "m-9", code: "M-9", name: "CULTIVO DE SECRECION uretral" },
        { key: "m-82", code: "M-82", name: "SUBCULTIVO CEPA ATCC" },
        { key: "m-99", code: "M-99", name: "PRUEBA DE DETECCION DE LIPOARABINOMANANO (TB LAM)" },
        { key: "m-47", code: "M-47", name: "CULTIVO DE HEMOCOMPONENTES" },
        { key: "m-40", code: "M-40", name: "BACILOSCOPIA 1a. MUESTRA" },
        { key: "m-42", code: "M-42", name: "BACILOSCOPIA SUB-SECUENTE" },
        { key: "m-116", code: "M-116", name: "CULTIVO DE MEDULA OSEA" },
      ],
    },
    {
      title: "Preparación",
      exams: [
        { key: "pr-2", code: "PR-2", name: "PLACAS PREPARADAS" },
        { key: "pr-7", code: "PR-7", name: "TUBOS PREPARADOS CON MEDIO" },
        { key: "pr-22", code: "PR-22", name: "LLENADO DE TARJETAS" },
      ],
    },
    {
      title: "Parasitología",
      exams: [
        { key: "p-1", code: "P-1", name: "EXAMEN GENERAL DE HECES" },
        { key: "p-8", code: "P-8", name: "PRUEBA DE AZUL DE METILENO" },
        { key: "p-3", code: "P-3", name: "SANGRE OCULTA EN HECES" },
        { key: "p-31", code: "P-31", name: "PRUEBA RÁPIDA DE VIRUS GASTROINTESTINALES" },
      ],
    },
    {
      title: "Molecular (TB)",
      exams: [
        { key: "bm-10", code: "BM-10", name: "Gen Xpert" },
      ],
    },
    {
      title: "Toma de muestras",
      exams: [
        { key: "t-2", code: "T-2", name: "TOMA DE MUESTRAS" },
      ],
    },
  ],
};
