// AUTO-GENERADO desde "Enfermeria seps.xlsx" (hoja MES ACTUAL) y ampliado
// con "seps enfermeria matriz.xlsx": 10 componentes de PROMOCION DE LA SALUD
// (hojas TAB PROM II a VII) y la hoja CONTINUOS (visita domiciliar).
// Tabulador SEPS de la División de Enfermería, servicio "enfermeria".
// Columnas = días del mes; Total por fila (única suma). Fiel al Excel.
import type { SepsTemplate } from "@/lib/seps-templates";

export const ENFERMERIA_TEMPLATE: SepsTemplate = {
  serviceId: "enfermeria",
  establishment: "HOSPITAL NACIONAL EL SALVADOR",
  tables: [
    {
      id: "enf_actividades",
      title: "SERVICIOS DE APOYO III (2do y 3er Nivel de Atención)",
      subtitle: "Actividades y Procedimientos",
      detailLabel: "Actividad",
      rows: [
        { key: "enf_cur_personas", label: "No. de personas", group: "Curaciones" },
        { key: "enf_cur_cantidad", label: "No. de curaciones", group: "Curaciones" },
        { key: "enf_iny_personas", label: "No. de personas", group: "Inyecciones" },
        { key: "enf_iny_cantidad", label: "No. de inyecciones", group: "Inyecciones" },
      ],
    },
    {
      id: "enf_endoscopia",
      title: "ENDOSCOPIA",
      subtitle: "Actividades y Procedimientos",
      detailLabel: "Actividad",
      rows: [
        { key: "enf_endo_digestiva", label: "Digestiva alta", group: "Endoscopia" },
        { key: "enf_endo_colonoscopia", label: "Colonoscopía", group: "Endoscopia" },
        { key: "enf_endo_otras", label: "Otras endoscopías", group: "Endoscopia" },
      ],
    },
    {
      id: "enf_hospitalizacion",
      title: "HOSPITALIZACIÓN DE PACIENTES AGUDOS E INTERCONSULTAS (I y II)",
      detailLabel: "Actividad",
      rows: [
        { key: "enf_disp_cateter_central", label: "Catéter central", group: "Días uso de dispositivos" },
        { key: "enf_disp_cateter_periferico", label: "Catéter periférico", group: "Días uso de dispositivos" },
        { key: "enf_disp_ventilador", label: "Ventilador mecánico", group: "Días uso de dispositivos" },
        { key: "enf_disp_sonda_vesical", label: "Sonda vesical", group: "Días uso de dispositivos" },
        { key: "enf_ic_medicina", label: "Medicina", group: "Interconsultas dentro del hospital" },
        { key: "enf_ic_cirugia", label: "Cirugía", group: "Interconsultas dentro del hospital" },
        { key: "enf_ref_medicina", label: "Medicina", group: "Paciente ingresado que se envía a interconsulta a otro hospital" },
        { key: "enf_ref_cirugia", label: "Cirugía", group: "Paciente ingresado que se envía a interconsulta a otro hospital" },
      ],
    },
    {
      id: "enf_detalle_medicina",
      title: "DETALLE - MEDICINA",
      detailLabel: "Actividad",
      rows: [
        { key: "enf_med_ingresos", label: "INGRESOS" },
        { key: "enf_med_dias_pacientes", label: "DIAS PACIENTES (SALDO)" },
        { key: "enf_med_dias_camas", label: "DIAS CAMAS DISPONIBLES" },
        { key: "enf_med_dotacion_camas", label: "DOTACION DE CAMAS" },
        { key: "enf_med_traslado_a", label: "TRASLADO A OTROS SERVICIOS" },
        { key: "enf_med_traslado_de", label: "TRASLADO DE OTROS SERVICIOS" },
      ],
    },
    {
      id: "enf_detalle_cirugia",
      title: "DETALLE - CIRUGÍA",
      detailLabel: "Actividad",
      rows: [
        { key: "enf_cir_ingresos", label: "INGRESOS" },
        { key: "enf_cir_dias_pacientes", label: "DIAS PACIENTES (SALDO)" },
        { key: "enf_cir_dias_camas", label: "DIAS CAMAS DISPONIBLES" },
        { key: "enf_cir_dotacion_camas", label: "DOTACION DE CAMAS" },
        { key: "enf_cir_traslado_a", label: "TRASLADO A OTROS SERVICIOS" },
        { key: "enf_cir_traslado_de", label: "TRASLADO DE OTROS SERVICIOS" },
      ],
    },
    {
      id: "enf_detalle_bienestar",
      title: "DETALLE - BIENESTAR MAGISTERIAL",
      detailLabel: "Actividad",
      rows: [
        { key: "enf_bien_ingresos", label: "INGRESOS" },
        { key: "enf_bien_dias_pacientes", label: "DIAS PACIENTES (SALDO)" },
        { key: "enf_bien_dias_camas", label: "DIAS CAMAS DISPONIBLES" },
        { key: "enf_bien_dotacion_camas", label: "DOTACION DE CAMAS" },
        { key: "enf_bien_traslado_a", label: "TRASLADO A OTROS SERVICIOS" },
        { key: "enf_bien_traslado_de", label: "TRASLADO DE OTROS SERVICIOS" },
      ],
    },
    {
      id: "enf_pr01",
      title: "PROMOCIÓN DE LA SALUD · HIPERTENSIÓN Y OTRAS ENFERMEDADES CARDIOVASCULARES",
      subtitle: "Sesiones educativas · TAB PROM II",
      detailLabel: "Grupo de atención",
      rows: [
        { key: "enf_pr01_01", label: "Mujeres", group: "0 - 7 años" },
        { key: "enf_pr01_02", label: "Hombres", group: "0 - 7 años" },
        { key: "enf_pr01_03", label: "Mujeres", group: "8 - 9 años" },
        { key: "enf_pr01_04", label: "Hombres", group: "8 - 9 años" },
        { key: "enf_pr01_05", label: "Mujeres", group: "10 - 11 años" },
        { key: "enf_pr01_06", label: "Hombres", group: "10 - 11 años" },
        { key: "enf_pr01_07", label: "Mujeres", group: "12 - 14 años" },
        { key: "enf_pr01_08", label: "Hombres", group: "12 - 14 años" },
        { key: "enf_pr01_09", label: "Mujeres", group: "15 - 17 años" },
        { key: "enf_pr01_10", label: "Hombres", group: "15 - 17 años" },
        { key: "enf_pr01_11", label: "Mujeres", group: "18 - 19 años" },
        { key: "enf_pr01_12", label: "Hombres", group: "18 - 19 años" },
        { key: "enf_pr01_13", label: "Mujeres", group: "20-59 años" },
        { key: "enf_pr01_14", label: "Hombres", group: "20-59 años" },
        { key: "enf_pr01_15", label: "Mujeres", group: "60 años y más" },
        { key: "enf_pr01_16", label: "Hombres", group: "60 años y más" },
        { key: "enf_pr01_17", label: "Salud Materna", group: "Sesiones con grupos" },
        { key: "enf_pr01_18", label: "Salud infantil", group: "Sesiones con grupos" },
        { key: "enf_pr01_19", label: "Adolescentes", group: "Sesiones con grupos" },
        { key: "enf_pr01_20", label: "Adultos mayores", group: "Sesiones con grupos" },
        { key: "enf_pr01_21", label: "Autoayuda de personas con enfermedades no transmisibles y factores de riesgo", group: "Sesiones con grupos" },
        { key: "enf_pr01_22", label: "Otro grupo organizado", group: "Sesiones con grupos" },
        { key: "enf_pr01_23", label: "Total de sesiones", group: "Sesiones con grupos" },
      ],
    },
    {
      id: "enf_pr02",
      title: "PROMOCIÓN DE LA SALUD · DIABETES MELLITUS Y OTRAS ENFERMEDADES ENDÓCRINAS",
      subtitle: "Sesiones educativas · TAB PROM II",
      detailLabel: "Grupo de atención",
      rows: [
        { key: "enf_pr02_01", label: "Mujeres", group: "0 - 7 años" },
        { key: "enf_pr02_02", label: "Hombres", group: "0 - 7 años" },
        { key: "enf_pr02_03", label: "Mujeres", group: "8 - 9 años" },
        { key: "enf_pr02_04", label: "Hombres", group: "8 - 9 años" },
        { key: "enf_pr02_05", label: "Mujeres", group: "10 - 11 años" },
        { key: "enf_pr02_06", label: "Hombres", group: "10 - 11 años" },
        { key: "enf_pr02_07", label: "Mujeres", group: "12 - 14 años" },
        { key: "enf_pr02_08", label: "Hombres", group: "12 - 14 años" },
        { key: "enf_pr02_09", label: "Mujeres", group: "15 - 17 años" },
        { key: "enf_pr02_10", label: "Hombres", group: "15 - 17 años" },
        { key: "enf_pr02_11", label: "Mujeres", group: "18 - 19 años" },
        { key: "enf_pr02_12", label: "Hombres", group: "18 - 19 años" },
        { key: "enf_pr02_13", label: "Mujeres", group: "20-59 años" },
        { key: "enf_pr02_14", label: "Hombres", group: "20-59 años" },
        { key: "enf_pr02_15", label: "Mujeres", group: "60 años y más" },
        { key: "enf_pr02_16", label: "Hombres", group: "60 años y más" },
        { key: "enf_pr02_17", label: "Salud Materna", group: "Sesiones con grupos" },
        { key: "enf_pr02_18", label: "Salud infantil", group: "Sesiones con grupos" },
        { key: "enf_pr02_19", label: "Adolescentes", group: "Sesiones con grupos" },
        { key: "enf_pr02_20", label: "Adultos mayores", group: "Sesiones con grupos" },
        { key: "enf_pr02_21", label: "Autoayuda de personas con enfermedades no transmisibles y factores de riesgo", group: "Sesiones con grupos" },
        { key: "enf_pr02_22", label: "Otro grupo organizado", group: "Sesiones con grupos" },
        { key: "enf_pr02_23", label: "Total de sesiones", group: "Sesiones con grupos" },
      ],
    },
    {
      id: "enf_pr03",
      title: "PROMOCIÓN DE LA SALUD · ENFERMEDAD RENAL CRÓNICA Y OTRAS ENFERMEDADES NEFROLÓGICAS",
      subtitle: "Sesiones educativas · TAB PROM III",
      detailLabel: "Grupo de atención",
      rows: [
        { key: "enf_pr03_01", label: "Mujeres", group: "0 - 7 años" },
        { key: "enf_pr03_02", label: "Hombres", group: "0 - 7 años" },
        { key: "enf_pr03_03", label: "Mujeres", group: "8 - 9 años" },
        { key: "enf_pr03_04", label: "Hombres", group: "8 - 9 años" },
        { key: "enf_pr03_05", label: "Mujeres", group: "10 - 11 años" },
        { key: "enf_pr03_06", label: "Hombres", group: "10 - 11 años" },
        { key: "enf_pr03_07", label: "Mujeres", group: "12 - 14 años" },
        { key: "enf_pr03_08", label: "Hombres", group: "12 - 14 años" },
        { key: "enf_pr03_09", label: "Mujeres", group: "15 - 17 años" },
        { key: "enf_pr03_10", label: "Hombres", group: "15 - 17 años" },
        { key: "enf_pr03_11", label: "Mujeres", group: "18 - 19 años" },
        { key: "enf_pr03_12", label: "Hombres", group: "18 - 19 años" },
        { key: "enf_pr03_13", label: "Mujeres", group: "20-59 años" },
        { key: "enf_pr03_14", label: "Hombres", group: "20-59 años" },
        { key: "enf_pr03_15", label: "Mujeres", group: "60 años y más" },
        { key: "enf_pr03_16", label: "Hombres", group: "60 años y más" },
        { key: "enf_pr03_17", label: "Salud Materna", group: "Sesiones con grupos" },
        { key: "enf_pr03_18", label: "Salud infantil", group: "Sesiones con grupos" },
        { key: "enf_pr03_19", label: "Adolescentes", group: "Sesiones con grupos" },
        { key: "enf_pr03_20", label: "Adultos mayores", group: "Sesiones con grupos" },
        { key: "enf_pr03_21", label: "Autoayuda de personas con enfermedades no transmisibles y factores de riesgo", group: "Sesiones con grupos" },
        { key: "enf_pr03_22", label: "Otro grupo organizado", group: "Sesiones con grupos" },
        { key: "enf_pr03_23", label: "Total de sesiones", group: "Sesiones con grupos" },
      ],
    },
    {
      id: "enf_pr04",
      title: "PROMOCIÓN DE LA SALUD · PREVENCIÓN DE CÁNCER",
      subtitle: "Sesiones educativas · TAB PROM III",
      detailLabel: "Grupo de atención",
      rows: [
        { key: "enf_pr04_01", label: "Mujeres", group: "0 - 7 años" },
        { key: "enf_pr04_02", label: "Hombres", group: "0 - 7 años" },
        { key: "enf_pr04_03", label: "Mujeres", group: "8 - 9 años" },
        { key: "enf_pr04_04", label: "Hombres", group: "8 - 9 años" },
        { key: "enf_pr04_05", label: "Mujeres", group: "10 - 11 años" },
        { key: "enf_pr04_06", label: "Hombres", group: "10 - 11 años" },
        { key: "enf_pr04_07", label: "Mujeres", group: "12 - 14 años" },
        { key: "enf_pr04_08", label: "Hombres", group: "12 - 14 años" },
        { key: "enf_pr04_09", label: "Mujeres", group: "15 - 17 años" },
        { key: "enf_pr04_10", label: "Hombres", group: "15 - 17 años" },
        { key: "enf_pr04_11", label: "Mujeres", group: "18 - 19 años" },
        { key: "enf_pr04_12", label: "Hombres", group: "18 - 19 años" },
        { key: "enf_pr04_13", label: "Mujeres", group: "20-59 años" },
        { key: "enf_pr04_14", label: "Hombres", group: "20-59 años" },
        { key: "enf_pr04_15", label: "Mujeres", group: "60 años y más" },
        { key: "enf_pr04_16", label: "Hombres", group: "60 años y más" },
        { key: "enf_pr04_17", label: "Salud Materna", group: "Sesiones con grupos" },
        { key: "enf_pr04_18", label: "Salud infantil", group: "Sesiones con grupos" },
        { key: "enf_pr04_19", label: "Adolescentes", group: "Sesiones con grupos" },
        { key: "enf_pr04_20", label: "Adultos mayores", group: "Sesiones con grupos" },
        { key: "enf_pr04_21", label: "Autoayuda de personas con enfermedades no transmisibles y factores de riesgo", group: "Sesiones con grupos" },
        { key: "enf_pr04_22", label: "Otro grupo organizado", group: "Sesiones con grupos" },
        { key: "enf_pr04_23", label: "Total de sesiones", group: "Sesiones con grupos" },
      ],
    },
    {
      id: "enf_pr05",
      title: "PROMOCIÓN DE LA SALUD · SALUD SEXUAL Y SALUD REPRODUCTIVA",
      subtitle: "Sesiones educativas · TAB PROM IV",
      detailLabel: "Grupo de atención",
      rows: [
        { key: "enf_pr05_01", label: "Mujeres", group: "0 - 7 años" },
        { key: "enf_pr05_02", label: "Hombres", group: "0 - 7 años" },
        { key: "enf_pr05_03", label: "Mujeres", group: "8 - 9 años" },
        { key: "enf_pr05_04", label: "Hombres", group: "8 - 9 años" },
        { key: "enf_pr05_05", label: "Mujeres", group: "10 - 11 años" },
        { key: "enf_pr05_06", label: "Hombres", group: "10 - 11 años" },
        { key: "enf_pr05_07", label: "Mujeres", group: "12 - 14 años" },
        { key: "enf_pr05_08", label: "Hombres", group: "12 - 14 años" },
        { key: "enf_pr05_09", label: "Mujeres", group: "15 - 17 años" },
        { key: "enf_pr05_10", label: "Hombres", group: "15 - 17 años" },
        { key: "enf_pr05_11", label: "Mujeres", group: "18 - 19 años" },
        { key: "enf_pr05_12", label: "Hombres", group: "18 - 19 años" },
        { key: "enf_pr05_13", label: "Mujeres", group: "20-59 años" },
        { key: "enf_pr05_14", label: "Hombres", group: "20-59 años" },
        { key: "enf_pr05_15", label: "Mujeres", group: "60 años y más" },
        { key: "enf_pr05_16", label: "Hombres", group: "60 años y más" },
        { key: "enf_pr05_17", label: "Salud Materna", group: "Sesiones con grupos" },
        { key: "enf_pr05_18", label: "Salud infantil", group: "Sesiones con grupos" },
        { key: "enf_pr05_19", label: "Adolescentes", group: "Sesiones con grupos" },
        { key: "enf_pr05_20", label: "Adultos mayores", group: "Sesiones con grupos" },
        { key: "enf_pr05_21", label: "Autoayuda de personas con enfermedades no transmisibles y factores de riesgo", group: "Sesiones con grupos" },
        { key: "enf_pr05_22", label: "Otro grupo organizado", group: "Sesiones con grupos" },
        { key: "enf_pr05_23", label: "Total de sesiones", group: "Sesiones con grupos" },
      ],
    },
    {
      id: "enf_pr06",
      title: "PROMOCIÓN DE LA SALUD · PREVENCIÓN DE CONSUMO DE TABACO, ALCOHOL Y OTRAS DROGAS",
      subtitle: "Sesiones educativas · TAB PROM IV",
      detailLabel: "Grupo de atención",
      rows: [
        { key: "enf_pr06_01", label: "Mujeres", group: "0 - 7 años" },
        { key: "enf_pr06_02", label: "Hombres", group: "0 - 7 años" },
        { key: "enf_pr06_03", label: "Mujeres", group: "8 - 9 años" },
        { key: "enf_pr06_04", label: "Hombres", group: "8 - 9 años" },
        { key: "enf_pr06_05", label: "Mujeres", group: "10 - 11 años" },
        { key: "enf_pr06_06", label: "Hombres", group: "10 - 11 años" },
        { key: "enf_pr06_07", label: "Mujeres", group: "12 - 14 años" },
        { key: "enf_pr06_08", label: "Hombres", group: "12 - 14 años" },
        { key: "enf_pr06_09", label: "Mujeres", group: "15 - 17 años" },
        { key: "enf_pr06_10", label: "Hombres", group: "15 - 17 años" },
        { key: "enf_pr06_11", label: "Mujeres", group: "18 - 19 años" },
        { key: "enf_pr06_12", label: "Hombres", group: "18 - 19 años" },
        { key: "enf_pr06_13", label: "Mujeres", group: "20-59 años" },
        { key: "enf_pr06_14", label: "Hombres", group: "20-59 años" },
        { key: "enf_pr06_15", label: "Mujeres", group: "60 años y más" },
        { key: "enf_pr06_16", label: "Hombres", group: "60 años y más" },
        { key: "enf_pr06_17", label: "Salud Materna", group: "Sesiones con grupos" },
        { key: "enf_pr06_18", label: "Salud infantil", group: "Sesiones con grupos" },
        { key: "enf_pr06_19", label: "Adolescentes", group: "Sesiones con grupos" },
        { key: "enf_pr06_20", label: "Adultos mayores", group: "Sesiones con grupos" },
        { key: "enf_pr06_21", label: "Autoayuda de personas con enfermedades no transmisibles y factores de riesgo", group: "Sesiones con grupos" },
        { key: "enf_pr06_22", label: "Otro grupo organizado", group: "Sesiones con grupos" },
        { key: "enf_pr06_23", label: "Total de sesiones", group: "Sesiones con grupos" },
      ],
    },
    {
      id: "enf_pr07",
      title: "PROMOCIÓN DE LA SALUD · PREVENCIÓN DE ACCIDENTES",
      subtitle: "Sesiones educativas · TAB PROM V",
      detailLabel: "Grupo de atención",
      rows: [
        { key: "enf_pr07_01", label: "Mujeres", group: "0 - 7 años" },
        { key: "enf_pr07_02", label: "Hombres", group: "0 - 7 años" },
        { key: "enf_pr07_03", label: "Mujeres", group: "8 - 9 años" },
        { key: "enf_pr07_04", label: "Hombres", group: "8 - 9 años" },
        { key: "enf_pr07_05", label: "Mujeres", group: "10 - 11 años" },
        { key: "enf_pr07_06", label: "Hombres", group: "10 - 11 años" },
        { key: "enf_pr07_07", label: "Mujeres", group: "12 - 14 años" },
        { key: "enf_pr07_08", label: "Hombres", group: "12 - 14 años" },
        { key: "enf_pr07_09", label: "Mujeres", group: "15 - 17 años" },
        { key: "enf_pr07_10", label: "Hombres", group: "15 - 17 años" },
        { key: "enf_pr07_11", label: "Mujeres", group: "18 - 19 años" },
        { key: "enf_pr07_12", label: "Hombres", group: "18 - 19 años" },
        { key: "enf_pr07_13", label: "Mujeres", group: "20-59 años" },
        { key: "enf_pr07_14", label: "Hombres", group: "20-59 años" },
        { key: "enf_pr07_15", label: "Mujeres", group: "60 años y más" },
        { key: "enf_pr07_16", label: "Hombres", group: "60 años y más" },
        { key: "enf_pr07_17", label: "Salud Materna", group: "Sesiones con grupos" },
        { key: "enf_pr07_18", label: "Salud infantil", group: "Sesiones con grupos" },
        { key: "enf_pr07_19", label: "Adolescentes", group: "Sesiones con grupos" },
        { key: "enf_pr07_20", label: "Adultos mayores", group: "Sesiones con grupos" },
        { key: "enf_pr07_21", label: "Autoayuda de personas con enfermedades no transmisibles y factores de riesgo", group: "Sesiones con grupos" },
        { key: "enf_pr07_22", label: "Otro grupo organizado", group: "Sesiones con grupos" },
        { key: "enf_pr07_23", label: "Total de sesiones", group: "Sesiones con grupos" },
      ],
    },
    {
      id: "enf_pr08",
      title: "PROMOCIÓN DE LA SALUD · SALUD BUCAL",
      subtitle: "Sesiones educativas · TAB PROM VI",
      detailLabel: "Grupo de atención",
      rows: [
        { key: "enf_pr08_01", label: "Mujeres", group: "0 - 7 años" },
        { key: "enf_pr08_02", label: "Hombres", group: "0 - 7 años" },
        { key: "enf_pr08_03", label: "Mujeres", group: "8 - 9 años" },
        { key: "enf_pr08_04", label: "Hombres", group: "8 - 9 años" },
        { key: "enf_pr08_05", label: "Mujeres", group: "10 - 11 años" },
        { key: "enf_pr08_06", label: "Hombres", group: "10 - 11 años" },
        { key: "enf_pr08_07", label: "Mujeres", group: "12 - 14 años" },
        { key: "enf_pr08_08", label: "Hombres", group: "12 - 14 años" },
        { key: "enf_pr08_09", label: "Mujeres", group: "15 - 17 años" },
        { key: "enf_pr08_10", label: "Hombres", group: "15 - 17 años" },
        { key: "enf_pr08_11", label: "Mujeres", group: "18 - 19 años" },
        { key: "enf_pr08_12", label: "Hombres", group: "18 - 19 años" },
        { key: "enf_pr08_13", label: "Mujeres", group: "20-59 años" },
        { key: "enf_pr08_14", label: "Hombres", group: "20-59 años" },
        { key: "enf_pr08_15", label: "Mujeres", group: "60 años y más" },
        { key: "enf_pr08_16", label: "Hombres", group: "60 años y más" },
        { key: "enf_pr08_17", label: "Salud Materna", group: "Sesiones con grupos" },
        { key: "enf_pr08_18", label: "Salud infantil", group: "Sesiones con grupos" },
        { key: "enf_pr08_19", label: "Adolescentes", group: "Sesiones con grupos" },
        { key: "enf_pr08_20", label: "Adultos mayores", group: "Sesiones con grupos" },
        { key: "enf_pr08_21", label: "Autoayuda de personas con enfermedades no transmisibles y factores de riesgo", group: "Sesiones con grupos" },
        { key: "enf_pr08_22", label: "Otro grupo organizado", group: "Sesiones con grupos" },
        { key: "enf_pr08_23", label: "Total de sesiones", group: "Sesiones con grupos" },
      ],
    },
    {
      id: "enf_pr09",
      title: "PROMOCIÓN DE LA SALUD · SALUD VISUAL",
      subtitle: "Sesiones educativas · TAB PROM VI",
      detailLabel: "Grupo de atención",
      rows: [
        { key: "enf_pr09_01", label: "Mujeres", group: "0 - 7 años" },
        { key: "enf_pr09_02", label: "Hombres", group: "0 - 7 años" },
        { key: "enf_pr09_03", label: "Mujeres", group: "8 - 9 años" },
        { key: "enf_pr09_04", label: "Hombres", group: "8 - 9 años" },
        { key: "enf_pr09_05", label: "Mujeres", group: "10 - 11 años" },
        { key: "enf_pr09_06", label: "Hombres", group: "10 - 11 años" },
        { key: "enf_pr09_07", label: "Mujeres", group: "12 - 14 años" },
        { key: "enf_pr09_08", label: "Hombres", group: "12 - 14 años" },
        { key: "enf_pr09_09", label: "Mujeres", group: "15 - 17 años" },
        { key: "enf_pr09_10", label: "Hombres", group: "15 - 17 años" },
        { key: "enf_pr09_11", label: "Mujeres", group: "18 - 19 años" },
        { key: "enf_pr09_12", label: "Hombres", group: "18 - 19 años" },
        { key: "enf_pr09_13", label: "Mujeres", group: "20-59 años" },
        { key: "enf_pr09_14", label: "Hombres", group: "20-59 años" },
        { key: "enf_pr09_15", label: "Mujeres", group: "60 años y más" },
        { key: "enf_pr09_16", label: "Hombres", group: "60 años y más" },
        { key: "enf_pr09_17", label: "Salud Materna", group: "Sesiones con grupos" },
        { key: "enf_pr09_18", label: "Salud infantil", group: "Sesiones con grupos" },
        { key: "enf_pr09_19", label: "Adolescentes", group: "Sesiones con grupos" },
        { key: "enf_pr09_20", label: "Adultos mayores", group: "Sesiones con grupos" },
        { key: "enf_pr09_21", label: "Autoayuda de personas con enfermedades no transmisibles y factores de riesgo", group: "Sesiones con grupos" },
        { key: "enf_pr09_22", label: "Otro grupo organizado", group: "Sesiones con grupos" },
        { key: "enf_pr09_23", label: "Total de sesiones", group: "Sesiones con grupos" },
      ],
    },
    {
      id: "enf_pr10",
      title: "PROMOCIÓN DE LA SALUD · PREVENCIÓN DE INTOXICACIONES POR PLAGUICIDAS",
      subtitle: "Sesiones educativas · TAB PROM VII",
      detailLabel: "Grupo de atención",
      rows: [
        { key: "enf_pr10_01", label: "Mujeres", group: "0 - 7 años" },
        { key: "enf_pr10_02", label: "Hombres", group: "0 - 7 años" },
        { key: "enf_pr10_03", label: "Mujeres", group: "8 - 9 años" },
        { key: "enf_pr10_04", label: "Hombres", group: "8 - 9 años" },
        { key: "enf_pr10_05", label: "Mujeres", group: "10 - 11 años" },
        { key: "enf_pr10_06", label: "Hombres", group: "10 - 11 años" },
        { key: "enf_pr10_07", label: "Mujeres", group: "12 - 14 años" },
        { key: "enf_pr10_08", label: "Hombres", group: "12 - 14 años" },
        { key: "enf_pr10_09", label: "Mujeres", group: "15 - 17 años" },
        { key: "enf_pr10_10", label: "Hombres", group: "15 - 17 años" },
        { key: "enf_pr10_11", label: "Mujeres", group: "18 - 19 años" },
        { key: "enf_pr10_12", label: "Hombres", group: "18 - 19 años" },
        { key: "enf_pr10_13", label: "Mujeres", group: "20-59 años" },
        { key: "enf_pr10_14", label: "Hombres", group: "20-59 años" },
        { key: "enf_pr10_15", label: "Mujeres", group: "60 años y más" },
        { key: "enf_pr10_16", label: "Hombres", group: "60 años y más" },
        { key: "enf_pr10_17", label: "Salud Materna", group: "Sesiones con grupos" },
        { key: "enf_pr10_18", label: "Salud infantil", group: "Sesiones con grupos" },
        { key: "enf_pr10_19", label: "Adolescentes", group: "Sesiones con grupos" },
        { key: "enf_pr10_20", label: "Adultos mayores", group: "Sesiones con grupos" },
        { key: "enf_pr10_21", label: "Autoayuda de personas con enfermedades no transmisibles y factores de riesgo", group: "Sesiones con grupos" },
        { key: "enf_pr10_22", label: "Otro grupo organizado", group: "Sesiones con grupos" },
        { key: "enf_pr10_23", label: "Total de sesiones", group: "Sesiones con grupos" },
      ],
    },
    {
      id: "enf_continuos",
      title: "VISITA DOMICILIAR Y CONTINUO DEL CUIDADO",
      subtitle: "Tabulador diario · CONTINUOS",
      detailLabel: "Actividad",
      rows: [
        { key: "enf_cont_01", label: "1. Enfermedades prevenibles por vacuna", group: "Total de visita familiar con criterio de riesgo (1a. Vez más subsecuente)" },
        { key: "enf_cont_02", label: "2. Infecciones de transmisión sexual VIH y SIDA", group: "Total de visita familiar con criterio de riesgo (1a. Vez más subsecuente)" },
        { key: "enf_cont_03", label: "3. Otras enfermedades de interés epidemiológico", group: "Total de visita familiar con criterio de riesgo (1a. Vez más subsecuente)" },
        { key: "enf_cont_04", label: "4. Desnutrición severa y moderada", group: "Total de visita familiar con criterio de riesgo (1a. Vez más subsecuente)" },
        { key: "enf_cont_05", label: "5. Embarazo de alto riesgo", group: "Total de visita familiar con criterio de riesgo (1a. Vez más subsecuente)" },
        { key: "enf_cont_06", label: "6. Puérperas", group: "Total de visita familiar con criterio de riesgo (1a. Vez más subsecuente)" },
        { key: "enf_cont_07", label: "7. Citologías positivas", group: "Total de visita familiar con criterio de riesgo (1a. Vez más subsecuente)" },
        { key: "enf_cont_08", label: "8. Tuberculosis", group: "Total de visita familiar con criterio de riesgo (1a. Vez más subsecuente)" },
        { key: "enf_cont_09", label: "1. Referencias de personas por enfermería", group: "Red para el Continuo del Cuidado de Enfermería" },
        { key: "enf_cont_10", label: "2. Seguimientos", group: "Red para el Continuo del Cuidado de Enfermería" },
        { key: "enf_cont_11", label: "3. Procesos de atencion de Enfermeria (PAE)", group: "Red para el Continuo del Cuidado de Enfermería" },
        { key: "enf_cont_12", label: "No. de visita familiar promocional" },
        { key: "enf_cont_13", label: "1. Institucional", group: "No. Tratamiento supervisado (TAES)" },
        { key: "enf_cont_14", label: "2. Hogar / comunidad", group: "No. Tratamiento supervisado (TAES)" },
        { key: "enf_cont_15", label: "Atenciones de Enfermería" },
        { key: "enf_cont_16", label: "No. de atenciones por morbilidad" },
        { key: "enf_cont_17", label: "1) Pacientes del MINSAL", group: "Emergencias atendidas (1+2)" },
        { key: "enf_cont_18", label: "2) Pacientes cotizantes del ISSS y otras instituciones", group: "Emergencias atendidas (1+2)" },
        { key: "enf_cont_19", label: "1- Partera Capacitada", group: "Total de supervisiones realizadas" },
        { key: "enf_cont_20", label: "2- Personal de Enfermería", group: "Total de supervisiones realizadas" },
        { key: "enf_cont_21", label: "3- Promotor(a) de salud", group: "Total de supervisiones realizadas" },
        { key: "enf_cont_22", label: "Toma de muestra de sangre" },
      ],
    },
  ],
};
