// AUTO-GENERADO desde "BANCO DE SANGRE 2026.xlsx" (hoja MES ACTUAL).
// Tabulador SEPS de Banco de Sangre, servicio "banco-de-sangre".
import type { SepsTemplate } from "@/lib/seps-templates";

export const BANCO_SANGRE_TEMPLATE: SepsTemplate = {
  serviceId: "banco-de-sangre",
  establishment: "HOSPITAL NACIONAL EL SALVADOR",
  tables: [
    {
      id: "bs1",
      title: "TABULADOR DIARIO DE ACTIVIDADES DE BANCO DE SANGRE I",
      subtitle: "PERSONAS DONANTES",
      detailLabel: "Detalle",
      rows: [
        { key: "bs1_8", label: "Masculino", groups: ["Sexo"] },
        { key: "bs1_9", label: "Femenino", groups: ["Sexo"] },
        { key: "bs1_10", label: "17 - 24 años", groups: ["Grupos de edad"] },
        { key: "bs1_11", label: "25 - 45 años", groups: ["Grupos de edad"] },
        { key: "bs1_12", label: "46 - 59 años", groups: ["Grupos de edad"] },
        { key: "bs1_13", label: "60 años y más", groups: ["Grupos de edad"] },
        { key: "bs1_14", label: "Urbana", groups: ["Área"] },
        { key: "bs1_15", label: "Rural", groups: ["Área"] },
        { key: "bs1_16", label: "Altruista", groups: ["Tipo de donante"] },
        { key: "bs1_17", label: "Altruista repetitivo", groups: ["Tipo de donante"] },
        { key: "bs1_18", label: "Reposición", groups: ["Tipo de donante"] },
        { key: "bs1_19", label: "Autólogos", groups: ["Tipo de donante"] },
        { key: "bs1_20", label: "Aféresis voluntario", groups: ["Tipo de donante"] },
        { key: "bs1_21", label: "Aféresis de reposición", groups: ["Tipo de donante"] },
        { key: "bs1_22", label: "Si", groups: ["Pre-selección", "Aceptado"] },
        { key: "bs1_23", label: "No", groups: ["Pre-selección", "Aceptado"] },
        { key: "bs1_24", label: "Temporal", groups: ["Pre-selección", "Diferido"] },
        { key: "bs1_25", label: "Permanente", groups: ["Pre-selección", "Diferido"] },
        { key: "bs1_26", label: "Unidad sangre recolectada completa" },
        { key: "bs1_27", label: "No. Glóbulos rojos", groups: ["Aféresis"] },
        { key: "bs1_28", label: "No. Plaquetas", groups: ["Aféresis"] },
        { key: "bs1_29", label: "No. Plasma fresco", groups: ["Aféresis"] },
        { key: "bs1_30", label: "Donación incompleta" },
      ],
    },
    {
      id: "bs2",
      title: "TABULADOR DIARIO DE ACTIVIDADES DE BANCO DE SANGRE III",
      subtitle: "TAMIZAJE SEROLÓGICO",
      detailLabel: "Detalle",
      rows: [
        { key: "bs2_39", label: "Tamizada", groups: ["Virus de Inmunodeficiencia Humana (VIH)"], readOnly: true, sumOf: ["bs2_40", "bs2_41", "bs2_42"], hideTotal: true },
        { key: "bs2_40", label: "Reactiva", groups: ["Virus de Inmunodeficiencia Humana (VIH)", "Resultado"] },
        { key: "bs2_41", label: "No reactiva", groups: ["Virus de Inmunodeficiencia Humana (VIH)", "Resultado"] },
        { key: "bs2_42", label: "Indeterminada", groups: ["Virus de Inmunodeficiencia Humana (VIH)", "Resultado"] },
        { key: "bs2_43", label: "Tamizada", groups: ["Antígeno de superficie hepatitis B (HBsAg)"], readOnly: true, sumOf: ["bs2_44", "bs2_45", "bs2_46"], hideTotal: true },
        { key: "bs2_44", label: "Reactiva", groups: ["Antígeno de superficie hepatitis B (HBsAg)", "Resultado"] },
        { key: "bs2_45", label: "No reactiva", groups: ["Antígeno de superficie hepatitis B (HBsAg)", "Resultado"] },
        { key: "bs2_46", label: "Indeterminada", groups: ["Antígeno de superficie hepatitis B (HBsAg)", "Resultado"] },
        { key: "bs2_47", label: "Tamizada", groups: ["Virus de hepatitis C (HCV)"], readOnly: true, sumOf: ["bs2_48", "bs2_49", "bs2_50"], hideTotal: true },
        { key: "bs2_48", label: "Reactiva", groups: ["Virus de hepatitis C (HCV)", "Resultado"] },
        { key: "bs2_49", label: "No reactiva", groups: ["Virus de hepatitis C (HCV)", "Resultado"] },
        { key: "bs2_50", label: "Indeterminada", groups: ["Virus de hepatitis C (HCV)", "Resultado"] },
        { key: "bs2_51", label: "Tamizada", groups: ["Chagas"], readOnly: true, sumOf: ["bs2_52", "bs2_53", "bs2_54"], hideTotal: true },
        { key: "bs2_52", label: "Reactiva", groups: ["Chagas", "Resultado"] },
        { key: "bs2_53", label: "No reactiva", groups: ["Chagas", "Resultado"] },
        { key: "bs2_54", label: "Indeterminada", groups: ["Chagas", "Resultado"] },
        { key: "bs2_55", label: "Tamizada", groups: ["Sífilis"], readOnly: true, sumOf: ["bs2_56", "bs2_57", "bs2_58"], hideTotal: true },
        { key: "bs2_56", label: "Reactiva", groups: ["Sífilis", "Resultado"] },
        { key: "bs2_57", label: "No reactiva", groups: ["Sífilis", "Resultado"] },
        { key: "bs2_58", label: "Indeterminada", groups: ["Sífilis", "Resultado"] },
        { key: "bs2_59", label: "Tamizada", groups: ["Citomegalovirus (CMV)"], readOnly: true, sumOf: ["bs2_60", "bs2_61", "bs2_62"], hideTotal: true },
        { key: "bs2_60", label: "Reactiva", groups: ["Citomegalovirus (CMV)", "Resultado"] },
        { key: "bs2_61", label: "No reactiva", groups: ["Citomegalovirus (CMV)", "Resultado"] },
        { key: "bs2_62", label: "Indeterminada", groups: ["Citomegalovirus (CMV)", "Resultado"] },
        { key: "bs2_63", label: "Tamizada", groups: ["Anticuerpo Hepatitis B Core (AntiHBc)"], readOnly: true, sumOf: ["bs2_64", "bs2_65", "bs2_66"], hideTotal: true },
        { key: "bs2_64", label: "Reactiva", groups: ["Anticuerpo Hepatitis B Core (AntiHBc)", "Resultado"] },
        { key: "bs2_65", label: "No reactiva", groups: ["Anticuerpo Hepatitis B Core (AntiHBc)", "Resultado"] },
        { key: "bs2_66", label: "Indeterminada", groups: ["Anticuerpo Hepatitis B Core (AntiHBc)", "Resultado"] },
        { key: "bs2_67", label: "No. de tipeos sanguíneos" },
        { key: "bs2_68", label: "No. de rastreos de anticuerpos irregulares" },
      ],
    },
    {
      id: "bs3",
      title: "TABULADOR DIARIO DE ACTIVIDADES DE BANCO DE SANGRE IV",
      subtitle: "PACIENTES TRANSFUNDIDOS",
      detailLabel: "Detalle",
      rows: [
        { key: "bs3_77", label: "No. de niños transfundidos", groups: ["Niño(a) menores de 10 años"] },
        { key: "bs3_78", label: "1. Consulta Externa", groups: ["Niño(a) menores de 10 años", "Servicio de procedencia"] },
        { key: "bs3_79", label: "2. Hospitalización", groups: ["Niño(a) menores de 10 años", "Servicio de procedencia"] },
        { key: "bs3_80", label: "3. Emergencia", groups: ["Niño(a) menores de 10 años", "Servicio de procedencia"] },
        { key: "bs3_81", label: "4. Hospital de día", groups: ["Niño(a) menores de 10 años", "Servicio de procedencia"] },
        { key: "bs3_82", label: "Sangre completa", groups: ["Niño(a) menores de 10 años"] },
        { key: "bs3_83", label: "Glóbulos rojos empacados", groups: ["Niño(a) menores de 10 años"] },
        { key: "bs3_84", label: "Plasma fresco congelado", groups: ["Niño(a) menores de 10 años"] },
        { key: "bs3_85", label: "Crioprecipitado", groups: ["Niño(a) menores de 10 años"] },
        { key: "bs3_86", label: "Concentrado plaquetario", groups: ["Niño(a) menores de 10 años"] },
        { key: "bs3_87", label: "Glóbulos rojos", groups: ["Niño(a) menores de 10 años", "Unidades de aféresis"] },
        { key: "bs3_88", label: "Plaquetas", groups: ["Niño(a) menores de 10 años", "Unidades de aféresis"] },
        { key: "bs3_89", label: "Plasma", groups: ["Niño(a) menores de 10 años", "Unidades de aféresis"] },
        { key: "bs3_90", label: "Plaquetaféresis", groups: ["Niño(a) menores de 10 años", "Procedimientos terapéuticos"] },
        { key: "bs3_91", label: "Plasmaféresis", groups: ["Niño(a) menores de 10 años", "Procedimientos terapéuticos"] },
        { key: "bs3_92", label: "Eritroaféresis", groups: ["Niño(a) menores de 10 años", "Procedimientos terapéuticos"] },
        { key: "bs3_93", label: "Recambio plasmático", groups: ["Niño(a) menores de 10 años", "Procedimientos terapéuticos"] },
        { key: "bs3_94", label: "Sangría", groups: ["Niño(a) menores de 10 años", "Procedimientos terapéuticos"] },
        { key: "bs3_95", label: "No. de personas transfundidas", groups: ["10 a 19 años"] },
        { key: "bs3_96", label: "1. Consulta Externa", groups: ["10 a 19 años", "Servicio de procedencia"] },
        { key: "bs3_97", label: "2. Hospitalización", groups: ["10 a 19 años", "Servicio de procedencia"] },
        { key: "bs3_98", label: "3. Emergencia", groups: ["10 a 19 años", "Servicio de procedencia"] },
        { key: "bs3_99", label: "4. Hospital de día", groups: ["10 a 19 años", "Servicio de procedencia"] },
        { key: "bs3_100", label: "Sangre completa", groups: ["10 a 19 años"] },
        { key: "bs3_101", label: "Glóbulos rojos empacados", groups: ["10 a 19 años"] },
        { key: "bs3_102", label: "Plasma fresco congelado", groups: ["10 a 19 años"] },
        { key: "bs3_103", label: "Crioprecipitado", groups: ["10 a 19 años"] },
        { key: "bs3_104", label: "Concentrado plaquetario", groups: ["10 a 19 años"] },
        { key: "bs3_105", label: "Glóbulos rojos", groups: ["10 a 19 años", "Unidades de aféresis"] },
        { key: "bs3_106", label: "Plaquetas", groups: ["10 a 19 años", "Unidades de aféresis"] },
        { key: "bs3_107", label: "Plasma PCC-19", groups: ["10 a 19 años", "Unidades de aféresis"] },
        { key: "bs3_108", label: "Plaquetaféresis", groups: ["10 a 19 años", "Procedimientos terapéuticos"] },
        { key: "bs3_109", label: "Plasmaféresis", groups: ["10 a 19 años", "Procedimientos terapéuticos"] },
        { key: "bs3_110", label: "Eritroaféresis", groups: ["10 a 19 años", "Procedimientos terapéuticos"] },
        { key: "bs3_111", label: "Recambio plasmático", groups: ["10 a 19 años", "Procedimientos terapéuticos"] },
        { key: "bs3_112", label: "Sangría", groups: ["10 a 19 años", "Procedimientos terapéuticos"] },
      ],
    },
    {
      id: "bs4",
      title: "TABULADOR DIARIO DE ACTIVIDADES DE BANCO DE SANGRE V",
      subtitle: "PACIENTES TRANSFUNDIDOS",
      detailLabel: "Detalle",
      rows: [
        { key: "bs4_122", label: "No. de personas transfundidas", groups: ["20 a 59 años"] },
        { key: "bs4_123", label: "1. Consulta Externa", groups: ["20 a 59 años", "Servicio de procedencia"] },
        { key: "bs4_124", label: "2. Hospitalización", groups: ["20 a 59 años", "Servicio de procedencia"] },
        { key: "bs4_125", label: "3. Emergencia", groups: ["20 a 59 años", "Servicio de procedencia"] },
        { key: "bs4_126", label: "4. Hospital de día", groups: ["20 a 59 años", "Servicio de procedencia"] },
        { key: "bs4_127", label: "Sangre completa", groups: ["20 a 59 años"] },
        { key: "bs4_128", label: "Glóbulos rojos empacados", groups: ["20 a 59 años"] },
        { key: "bs4_129", label: "Plasma fresco congelado", groups: ["20 a 59 años"] },
        { key: "bs4_130", label: "Crioprecipitado", groups: ["20 a 59 años"] },
        { key: "bs4_131", label: "Concentrado plaquetario", groups: ["20 a 59 años"] },
        { key: "bs4_132", label: "Glóbulos rojos", groups: ["20 a 59 años", "Unidades de aféresis"] },
        { key: "bs4_133", label: "Plaquetas", groups: ["20 a 59 años", "Unidades de aféresis"] },
        { key: "bs4_134", label: "Plasma", groups: ["20 a 59 años", "Unidades de aféresis"] },
        { key: "bs4_135", label: "Plaquetaféresis", groups: ["20 a 59 años", "Procedimientos terapéuticos"] },
        { key: "bs4_136", label: "Plasmaféresis", groups: ["20 a 59 años", "Procedimientos terapéuticos"] },
        { key: "bs4_137", label: "Eritroaféresis", groups: ["20 a 59 años", "Procedimientos terapéuticos"] },
        { key: "bs4_138", label: "Recambio plasmático", groups: ["20 a 59 años", "Procedimientos terapéuticos"] },
        { key: "bs4_139", label: "Sangría", groups: ["20 a 59 años", "Procedimientos terapéuticos"] },
        { key: "bs4_140", label: "No. de personas transfundidas", groups: ["60 años y más"] },
        { key: "bs4_141", label: "1. Consulta Externa", groups: ["60 años y más", "Servicio de procedencia"] },
        { key: "bs4_142", label: "2. Hospitalización", groups: ["60 años y más", "Servicio de procedencia"] },
        { key: "bs4_143", label: "3. Emergencia", groups: ["60 años y más", "Servicio de procedencia"] },
        { key: "bs4_144", label: "4. Hospital de día", groups: ["60 años y más", "Servicio de procedencia"] },
        { key: "bs4_145", label: "Sangre completa", groups: ["60 años y más"] },
        { key: "bs4_146", label: "Glóbulos rojos empacados", groups: ["60 años y más"] },
        { key: "bs4_147", label: "Plasma fresco congelado", groups: ["60 años y más"] },
        { key: "bs4_148", label: "Crioprecipitado", groups: ["60 años y más"] },
        { key: "bs4_149", label: "Concentrado plaquetario", groups: ["60 años y más"] },
        { key: "bs4_150", label: "Glóbulos rojos", groups: ["60 años y más", "Unidades de aféresis"] },
        { key: "bs4_151", label: "Plaquetas", groups: ["60 años y más", "Unidades de aféresis"] },
        { key: "bs4_152", label: "Plasma", groups: ["60 años y más", "Unidades de aféresis"] },
        { key: "bs4_153", label: "Plaquetaféresis", groups: ["60 años y más", "Procedimientos terapéuticos"] },
        { key: "bs4_154", label: "Plasmaféresis", groups: ["60 años y más", "Procedimientos terapéuticos"] },
        { key: "bs4_155", label: "Eritroaféresis", groups: ["60 años y más", "Procedimientos terapéuticos"] },
        { key: "bs4_156", label: "Recambio plasmático", groups: ["60 años y más", "Procedimientos terapéuticos"] },
        { key: "bs4_157", label: "Sangría", groups: ["60 años y más", "Procedimientos terapéuticos"] },
      ],
    },
    {
      id: "bs5",
      title: "TABULADOR DIARIO DE ACTIVIDADES DE BANCO DE SANGRE",
      subtitle: "EXISTENCIAS DIARIAS",
      detailLabel: "Detalle",
      rows: [
        { key: "bs5_167", label: "A RH (+)", groups: ["Grupo ll", "Glóbulo rojo empacados (Unidades)"] },
        { key: "bs5_168", label: "A Rh (-)", groups: ["Grupo ll", "Glóbulo rojo empacados (Unidades)"] },
        { key: "bs5_169", label: "B Rh (+)", groups: ["Grupo ll", "Glóbulo rojo empacados (Unidades)"] },
        { key: "bs5_170", label: "B Rh (-)", groups: ["Grupo ll", "Glóbulo rojo empacados (Unidades)"] },
        { key: "bs5_171", label: "AB Rh (+)", groups: ["Grupo ll", "Glóbulo rojo empacados (Unidades)"] },
        { key: "bs5_172", label: "AB Rh (-)", groups: ["Grupo ll", "Glóbulo rojo empacados (Unidades)"] },
        { key: "bs5_173", label: "O Rh (+)", groups: ["Grupo ll", "Glóbulo rojo empacados (Unidades)"] },
        { key: "bs5_174", label: "O Rh (-)", groups: ["Grupo ll", "Glóbulo rojo empacados (Unidades)"] },
        { key: "bs5_175", label: "A Rh (+)", groups: ["Grupo ll", "Concentrado de plaquetas (Unidades)"] },
        { key: "bs5_176", label: "A Rh (-)", groups: ["Grupo ll", "Concentrado de plaquetas (Unidades)"] },
        { key: "bs5_177", label: "B Rh (+)", groups: ["Grupo ll", "Concentrado de plaquetas (Unidades)"] },
        { key: "bs5_178", label: "B Rh (-)", groups: ["Grupo ll", "Concentrado de plaquetas (Unidades)"] },
        { key: "bs5_179", label: "AB Rh (+)", groups: ["Grupo ll", "Concentrado de plaquetas (Unidades)"] },
        { key: "bs5_180", label: "AB Rh (-)", groups: ["Grupo ll", "Concentrado de plaquetas (Unidades)"] },
        { key: "bs5_181", label: "O Rh (+)", groups: ["Grupo ll", "Concentrado de plaquetas (Unidades)"] },
        { key: "bs5_182", label: "O Rh (-)", groups: ["Grupo ll", "Concentrado de plaquetas (Unidades)"] },
        { key: "bs5_183", label: "Plasma fresco congelado", groups: ["Grupo ll", "Otros Hemocomponentes (Unidades)"] },
        { key: "bs5_184", label: "Plaqueta por aféresis", groups: ["Grupo ll", "Otros Hemocomponentes (Unidades)"] },
        { key: "bs5_185", label: "Crioprecipitado", groups: ["Grupo ll", "Otros Hemocomponentes (Unidades)"] },
        { key: "bs5_186", label: "Plasma por aférisis", groups: ["Grupo ll", "Otros Hemocomponentes (Unidades)"] },
      ],
    },
    {
      id: "bs6",
      title: "TABULADOR DIARIO DE ACTIVIDADES DE BANCO DE SANGRE",
      subtitle: "BANCO DE SANGRE II. HEMOCOMPONENTES",
      detailLabel: "Detalle",
      rows: [
        { key: "bs6_195", label: "1. Sangre completa no fraccionada", groups: ["Actividad", "Preparación de unidades de hemocomponentes"] },
        { key: "bs6_196", label: "2. Sangre total reconstituida", groups: ["Actividad", "Preparación de unidades de hemocomponentes"] },
        { key: "bs6_197", label: "3. Glóbulo rojo empacado", groups: ["Actividad", "Preparación de unidades de hemocomponentes"] },
        { key: "bs6_198", label: "4. Concentrado plaquetario", groups: ["Actividad", "Preparación de unidades de hemocomponentes"] },
        { key: "bs6_199", label: "5. Plasma fresco congelado", groups: ["Actividad", "Preparación de unidades de hemocomponentes"] },
        { key: "bs6_200", label: "6. Crioprecipitado", groups: ["Actividad", "Preparación de unidades de hemocomponentes"] },
        { key: "bs6_201", label: "7. Glóbulo rojo empacado leucorreducido buffy coat", groups: ["Actividad", "Preparación de unidades de hemocomponentes"] },
        { key: "bs6_202", label: "8. Glóbulo rojo empacado leucorreducido por filtro leucorreductor", groups: ["Actividad", "Preparación de unidades de hemocomponentes"] },
        { key: "bs6_203", label: "9. Concentrado plaquetario x filtro leucorreductor", groups: ["Actividad", "Preparación de unidades de hemocomponentes"] },
        { key: "bs6_204", label: "10. Concentrado plaquetario por aféresis", groups: ["Actividad", "Preparación de unidades de hemocomponentes"] },
        { key: "bs6_205", label: "11. Glóbulo rojo empacado por aféresis", groups: ["Actividad", "Preparación de unidades de hemocomponentes"] },
        { key: "bs6_206", label: "12. Plasma fresco por aféresis", groups: ["Actividad", "Preparación de unidades de hemocomponentes"] },
        { key: "bs6_207", label: "Vencimiento", groups: ["Descarte de unidades de hemocomponentes", "1. Sangre completa"] },
        { key: "bs6_208", label: "Desperfecto de bolsa", groups: ["Descarte de unidades de hemocomponentes", "1. Sangre completa"] },
        { key: "bs6_209", label: "Otras razones diferentes a agente infeccioso", groups: ["Descarte de unidades de hemocomponentes", "1. Sangre completa"] },
        { key: "bs6_210", label: "Tamizaje", groups: ["Descarte de unidades de hemocomponentes", "1. Sangre completa"] },
        { key: "bs6_211", label: "Vencimiento", groups: ["Descarte de unidades de hemocomponentes", "2. Glóbulos rojos"] },
        { key: "bs6_212", label: "Desperfecto de bolsa", groups: ["Descarte de unidades de hemocomponentes", "2. Glóbulos rojos"] },
        { key: "bs6_213", label: "Otras razones diferentes a agente infeccioso", groups: ["Descarte de unidades de hemocomponentes", "2. Glóbulos rojos"] },
        { key: "bs6_214", label: "Tamizaje", groups: ["Descarte de unidades de hemocomponentes", "2. Glóbulos rojos"] },
        { key: "bs6_215", label: "Vencimiento", groups: ["Descarte de unidades de hemocomponentes", "3. Plasma fresco congelado"] },
        { key: "bs6_216", label: "Desperfecto de bolsa", groups: ["Descarte de unidades de hemocomponentes", "3. Plasma fresco congelado"] },
        { key: "bs6_217", label: "Otras razones diferentes a agente infeccioso", groups: ["Descarte de unidades de hemocomponentes", "3. Plasma fresco congelado"] },
        { key: "bs6_218", label: "Tamizaje", groups: ["Descarte de unidades de hemocomponentes", "3. Plasma fresco congelado"] },
        { key: "bs6_219", label: "Vencimiento", groups: ["Descarte de unidades de hemocomponentes", "4. Crioprecipitado"] },
        { key: "bs6_220", label: "Desperfecto de bolsa", groups: ["Descarte de unidades de hemocomponentes", "4. Crioprecipitado"] },
        { key: "bs6_221", label: "Otras razones diferentes a agente infeccioso", groups: ["Descarte de unidades de hemocomponentes", "4. Crioprecipitado"] },
        { key: "bs6_222", label: "Tamizaje", groups: ["Descarte de unidades de hemocomponentes", "4. Crioprecipitado"] },
        { key: "bs6_223", label: "Vencimiento", groups: ["Descarte de unidades de hemocomponentes", "5. Concentrado plaquetario"] },
        { key: "bs6_224", label: "Desperfecto de bolsa", groups: ["Descarte de unidades de hemocomponentes", "5. Concentrado plaquetario"] },
        { key: "bs6_225", label: "Otras razones diferentes a agente infeccioso", groups: ["Descarte de unidades de hemocomponentes", "5. Concentrado plaquetario"] },
        { key: "bs6_226", label: "Tamizaje", groups: ["Descarte de unidades de hemocomponentes", "5. Concentrado plaquetario"] },
      ],
    },
  ],
};
