// AUTO-GENERADO desde "medio ambiente seps.xlsx" (hoja MES ACTUAL).
// Tabulador SEPS de Saneamiento Ambiental (Medio Ambiente), servicio "saneamiento-ambiental".
// 11 tablas; columnas = dias del mes; Total por fila (unica suma del Excel).
import type { SepsTemplate } from "@/lib/seps-templates";

export const SANEAMIENTO_AMBIENTAL_TEMPLATE: SepsTemplate = {
  serviceId: "saneamiento-ambiental",
  establishment: "HOSPITAL NACIONAL EL SALVADOR",
  tables: [
    {
      id: "ma1",
      title: "TABULADOR DIARIO DE SANEAMIENTO AMBIENTAL",
      subtitle: "I - Calidad de agua para consumo humano",
      detailLabel: "Actividad",
      rows: [
        { key: "ma1_1", label: "1. Sistemas de abastecimiento de agua en sus diferentes componentes", groups: ["I. Calidad de Agua para el Consumo Humano", "Inspecciones Integrales (1+2+3+4)"] },
        { key: "ma1_2", label: "2. A equipos para producción de Hipoclorito de Sodio (PURIAGUA)", groups: ["I. Calidad de Agua para el Consumo Humano", "Inspecciones Integrales (1+2+3+4)"] },
        { key: "ma1_3", label: "3. A fuentes de agua (pozos excavados, pozos perforados, manantiales, agua lluvia, fuente comunitaria)", groups: ["I. Calidad de Agua para el Consumo Humano", "Inspecciones Integrales (1+2+3+4)"] },
        { key: "ma1_4", label: "4. Toma y envío de muestras para análisis microbiológico del programa regular", groups: ["I. Calidad de Agua para el Consumo Humano", "Actividades (5+6+7+8+9+10+11+12)"] },
        { key: "ma1_5", label: "5. Toma y envío de muestras para análisis microbiológico a solicitud de entes privados", groups: ["I. Calidad de Agua para el Consumo Humano", "Actividades (5+6+7+8+9+10+11+12)"] },
        { key: "ma1_6", label: "6. Toma y envío de muestra para análisis físico - químico del programa regular", groups: ["I. Calidad de Agua para el Consumo Humano", "Actividades (5+6+7+8+9+10+11+12)"] },
        { key: "ma1_7", label: "7. Toma y envóo de muestra para análisis físico-químico a solicitud de entes privados", groups: ["I. Calidad de Agua para el Consumo Humano", "Actividades (5+6+7+8+9+10+11+12)"] },
        { key: "ma1_8", label: "8. Toma y envío de muestra para análisis de traza de metales", groups: ["I. Calidad de Agua para el Consumo Humano", "Actividades (5+6+7+8+9+10+11+12)"] },
        { key: "ma1_9", label: "9. Toma y envío de muestra para análisis microbiológico de pozos artesanales o mejorados del programa regular", groups: ["I. Calidad de Agua para el Consumo Humano", "Actividades (5+6+7+8+9+10+11+12)"] },
        { key: "ma1_10", label: "10. Toma y envío de muestras para análisis microbiológicos de puntos de uso del programa regular.", groups: ["I. Calidad de Agua para el Consumo Humano", "Actividades (5+6+7+8+9+10+11+12)"] },
        { key: "ma1_11", label: "11. Toma y envío de muestras de agua para análisis de plaguicidas del programa regular", groups: ["I. Calidad de Agua para el Consumo Humano", "Actividades (5+6+7+8+9+10+11+12)"] },
        { key: "ma1_12", label: "12. Lecturas de cloro residual", groups: ["I. Calidad de Agua para el Consumo Humano", "Actividades (5+6+7+8+9+10+11+12)"] },
        { key: "ma1_13", label: "13. Revisión y aprobación de Planes de Seguridad del Agua Resilientes al clima (PSA-RC)", groups: ["I. Calidad de Agua para el Consumo Humano", "Actividades (5+6+7+8+9+10+11+12)"] },
        { key: "ma1_14", label: "1. Para verificar factibilidad de instalación de letrinas sin arrastre de agua en viviendas", groups: ["II. Disposición de excretas", "Inspección (1+2)"] },
        { key: "ma1_15", label: "2. A letrinas sin arrastre de agua durante su instalación, uso y mantenimiento", groups: ["II. Disposición de excretas", "Inspección (1+2)"] },
        { key: "ma1_16", label: "3. Revisión de solicitudes para instalación de letrinas sin arrastre de agua en viviendas", groups: ["II. Disposición de excretas", "Actividad (3)"] },
      ],
    },
    {
      id: "ma2",
      title: "TABULADOR DIARIO DE SANEAMIENTO AMBIENTAL",
      subtitle: "III y IV - Aguas negras / superficiales",
      detailLabel: "Actividad",
      rows: [
        { key: "ma2_1", label: "1. Para verificar factibilidad de instalación de sistemas de tratamiento individual de aguas negras y grises con infiltración al suelo en vivienda individual y establecimientos", groups: ["III. Aguas negras y grises con infiltración al suelo", "Inspección (1+2+3+4)"] },
        { key: "ma2_2", label: "2. A sistema de tratamiento individual de aguas negras y grises con infiltración al suelo durante su ejecución", groups: ["III. Aguas negras y grises con infiltración al suelo", "Inspección (1+2+3+4)"] },
        { key: "ma2_3", label: "3. Para verificar factibilidad a sistemas de tratamiento individual de aguas negras y grises en proyectos habitacionales", groups: ["III. Aguas negras y grises con infiltración al suelo", "Inspección (1+2+3+4)"] },
        { key: "ma2_4", label: "4. Para verficar factibilidad a sistemas de tratamiento individual de aguas negras y grises en proyectos de agua y saneamiento", groups: ["III. Aguas negras y grises con infiltración al suelo", "Inspección (1+2+3+4)"] },
        { key: "ma2_5", label: "5. Revisión de solicitudes para instalación de sistemas de tratamiento individual de aguas negras y grises con infiltración al suelo", groups: ["III. Aguas negras y grises con infiltración al suelo", "Actividad (5)"] },
        { key: "ma2_6", label: "1. A cuerpos de aguas superficiales", groups: ["IV. Vigilancia sanitaria de aguas superficiales y piscinas", "Inspecciones"] },
        { key: "ma2_7", label: "2. A piscinas y balnearios", groups: ["IV. Vigilancia sanitaria de aguas superficiales y piscinas", "Inspecciones"] },
        { key: "ma2_8", label: "3. A establecimientos con piscinas y balnearios con solicitudes de permiso sanitario", groups: ["IV. Vigilancia sanitaria de aguas superficiales y piscinas", "Inspecciones"] },
        { key: "ma2_9", label: "4. Colocación de hisopo de Moore, toma y envío de muestra ambiental para Vibrio cholerae", groups: ["IV. Vigilancia sanitaria de aguas superficiales y piscinas", "Actividades (1+2+3+4+5)"] },
        { key: "ma2_10", label: "5.Toma y envío de muestra para análisis microbiológico en aguas superficiales", groups: ["IV. Vigilancia sanitaria de aguas superficiales y piscinas", "Actividades (1+2+3+4+5)"] },
        { key: "ma2_11", label: "6. Toma y envío de muestra para análisis microbiológico en aguas de piscinas", groups: ["IV. Vigilancia sanitaria de aguas superficiales y piscinas", "Actividades (1+2+3+4+5)"] },
        { key: "ma2_12", label: "7. Toma y envío de muestra para análisis físico-químico en aguas de piscinas", groups: ["IV. Vigilancia sanitaria de aguas superficiales y piscinas", "Actividades (1+2+3+4+5)"] },
        { key: "ma2_13", label: "8. Lectura de cloro residual en agua de piscinas", groups: ["IV. Vigilancia sanitaria de aguas superficiales y piscinas", "Actividades (1+2+3+4+5)"] },
        { key: "ma2_14", label: "1. Establecimientos públicos generadores de desechos bioinfecciosos", groups: ["V. Desechos bioinfecciosos", "Inspección (1+2+3+4+5+6)"] },
        { key: "ma2_15", label: "2. Hospitales nacionales generadores de desechos bioinfecciosos", groups: ["V. Desechos bioinfecciosos", "Inspección (1+2+3+4+5+6)"] },
        { key: "ma2_16", label: "3. Establecimientos privados generadores de desechos bioinfecciosos sin hospitalización", groups: ["V. Desechos bioinfecciosos", "Inspección (1+2+3+4+5+6)"] },
        { key: "ma2_17", label: "4. Establecimientos privados generadores de desechos bioinfecciosos con hospitalización y otros generadores", groups: ["V. Desechos bioinfecciosos", "Inspección (1+2+3+4+5+6)"] },
        { key: "ma2_18", label: "5. A instalaciones físicas y sanitarias de establecimientos que prestan servicios de recolección y transporte de desechos bioinfecciosos", groups: ["V. Desechos bioinfecciosos", "Inspección (1+2+3+4+5+6)"] },
        { key: "ma2_19", label: "6. Instalaciones físicas y sanitarias de establecimientos que tratan desechos bioinfecciosos", groups: ["V. Desechos bioinfecciosos", "Inspección (1+2+3+4+5+6)"] },
        { key: "ma2_20", label: "7. Revisión de planes de manejo de desechos bioinfecciosos", groups: ["V. Desechos bioinfecciosos", "Actividad (7)"] },
        { key: "ma2_21", label: "1. A instalaciones física y sanitaria de casas mortuorias o funerales, funerarias y sala de venta de ataúdes", groups: ["VI. Instalaciones donde se manejan cadavares y restos humanos y otras actividades", "Inspección a instalaciones físicas (1+2+3+4+5)"] },
        { key: "ma2_22", label: "2. A instalaciones física y sanitaria de Cementerios públicos y privados", groups: ["VI. Instalaciones donde se manejan cadavares y restos humanos y otras actividades", "Inspección a instalaciones físicas (1+2+3+4+5)"] },
        { key: "ma2_23", label: "3. A instalaciones física y sanitaria de Crematorios", groups: ["VI. Instalaciones donde se manejan cadavares y restos humanos y otras actividades", "Inspección a instalaciones físicas (1+2+3+4+5)"] },
        { key: "ma2_24", label: "4. Instalaciones físicas en hospitales nacionales donde se manejan cadáveres y restos humanos", groups: ["VI. Instalaciones donde se manejan cadavares y restos humanos y otras actividades", "Inspección a instalaciones físicas (1+2+3+4+5)"] },
        { key: "ma2_25", label: "5. A vehículos que trasladan cadáveres dentro del país", groups: ["VI. Instalaciones donde se manejan cadavares y restos humanos y otras actividades", "Inspección a instalaciones físicas (1+2+3+4+5)"] },
        { key: "ma2_26", label: "1. Verificar condiciones de salubridad en la exhumación, sellado y entrega de cadáveres y restos humanos", groups: ["VI. Instalaciones donde se manejan cadavares y restos humanos y otras actividades", "Manejo de Cadáveres y restos humanos, otras actividades (1+2+3+4)"] },
        { key: "ma2_27", label: "2. Verificar condiciones de salubridad en la cremación de cadáveres y restos humanos", groups: ["VI. Instalaciones donde se manejan cadavares y restos humanos y otras actividades", "Manejo de Cadáveres y restos humanos, otras actividades (1+2+3+4)"] },
        { key: "ma2_28", label: "3. Relacionados al manejo de cadáveres y restos humanos", groups: ["VI. Instalaciones donde se manejan cadavares y restos humanos y otras actividades", "Manejo de Cadáveres y restos humanos, otras actividades (1+2+3+4)"] },
        { key: "ma2_29", label: "4. Relacionados al manejo de cadáveres y restos humanos dentro de hospitales nacionales", groups: ["VI. Instalaciones donde se manejan cadavares y restos humanos y otras actividades", "Manejo de Cadáveres y restos humanos, otras actividades (1+2+3+4)"] },
      ],
    },
    {
      id: "ma3",
      title: "TABULADOR DIARIO DE SANEAMIENTO AMBIENTAL",
      subtitle: "VII y VIII - Residuos / establecimientos",
      detailLabel: "Actividad",
      rows: [
        { key: "ma3_1", label: "1. A sitios de transferencia", groups: ["VII. Residuos municipales", "Inspección (1+2+3)"] },
        { key: "ma3_2", label: "2. A composteras", groups: ["VII. Residuos municipales", "Inspección (1+2+3)"] },
        { key: "ma3_3", label: "3. A rellenos sanitarios", groups: ["VII. Residuos municipales", "Inspección (1+2+3)"] },
        { key: "ma3_4", label: "1. Otros establecimientos comerciales industriales y agroindustriales", groups: ["VIII. Establecimientos comerciales, servicios, industriales y agroindustriales", "Inspección (1+2+3+4+5+6+7+8)"] },
        { key: "ma3_5", label: "2. Granjas avícolas y porcinas", groups: ["VIII. Establecimientos comerciales, servicios, industriales y agroindustriales", "Inspección (1+2+3+4+5+6+7+8)"] },
        { key: "ma3_6", label: "3. Plantas de sacrificio de animales con valor económico (mataderos)", groups: ["VIII. Establecimientos comerciales, servicios, industriales y agroindustriales", "Inspección (1+2+3+4+5+6+7+8)"] },
        { key: "ma3_7", label: "4. Beneficios de café y recibideros de café", groups: ["VIII. Establecimientos comerciales, servicios, industriales y agroindustriales", "Inspección (1+2+3+4+5+6+7+8)"] },
        { key: "ma3_8", label: "5. vehículos que transportan pulpa de café", groups: ["VIII. Establecimientos comerciales, servicios, industriales y agroindustriales", "Inspección (1+2+3+4+5+6+7+8)"] },
        { key: "ma3_9", label: "6. Ingenios azucareros.", groups: ["VIII. Establecimientos comerciales, servicios, industriales y agroindustriales", "Inspección (1+2+3+4+5+6+7+8)"] },
        { key: "ma3_10", label: "7. Empresas controladoras de insectos y roedores", groups: ["VIII. Establecimientos comerciales, servicios, industriales y agroindustriales", "Inspección (1+2+3+4+5+6+7+8)"] },
        { key: "ma3_11", label: "8. Establecimientos que generan emisiones atmosféricas por fuentes fijas por vigilancia", groups: ["VIII. Establecimientos comerciales, servicios, industriales y agroindustriales", "Inspección (1+2+3+4+5+6+7+8)"] },
        { key: "ma3_12", label: "1. A hoteles, moteles, pensiones, hostales y casas de huéspedes por vigilancia o denuncia", groups: ["IX. Establecimientos de hospedaje", "Inspección (1+2)"] },
        { key: "ma3_13", label: "2. A hoteles, moteles, pensiones, hostales y casas de huéspedes por solicitud de trámite de permiso sanitario", groups: ["IX. Establecimientos de hospedaje", "Inspección (1+2)"] },
        { key: "ma3_14", label: "1. A salones de belleza, peluquerías, sauna y/o masajes, estudios de tatuaje y/o perforaciones por vigilancia o denuncia", groups: ["X. Establecimientos de salones de belleza, peluquerías, sauna y masajes, estudios de tatuaje y/o perforaciones", "Inspección (1+2)"] },
        { key: "ma3_15", label: "2. A salones de belleza, peluquerías, sauna y/o masajes, estudios de tatuaje y/o perforaciones por solicitud de trámite de permiso sanitario", groups: ["X. Establecimientos de salones de belleza, peluquerías, sauna y masajes, estudios de tatuaje y/o perforaciones", "Inspección (1+2)"] },
        { key: "ma3_16", label: "1. Moluscos bivalvos crudos.", groups: ["XI. Vigilancia de niveles de saxitoxinas", "Muestras para identificación de tóxinas (1)"] },
        { key: "ma3_17", label: "1. Inspecciones a viviendas.", groups: ["XII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Arbovirosis (1+2+3+4+5)"] },
        { key: "ma3_18", label: "2. Inspecciones a centros colectivos", groups: ["XII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Arbovirosis (1+2+3+4+5)"] },
        { key: "ma3_19", label: "3. Viviendas inspeccionadas por control de calidad", groups: ["XII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Arbovirosis (1+2+3+4+5)"] },
        { key: "ma3_20", label: "4. Viviendas inspeccionadas por encuesta entomológica", groups: ["XII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Arbovirosis (1+2+3+4+5)"] },
        { key: "ma3_21", label: "5. Atención a lugares donde se ubican casos sospechosos (viviendas visitadas por control de foco)", groups: ["XII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Arbovirosis (1+2+3+4+5)"] },
        { key: "ma3_22", label: "1. Inspecciones a viviendas", groups: ["XII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria (1+2+3+4+5+6+7+8)"] },
        { key: "ma3_23", label: "2. Control de criaderos de mosquitos", groups: ["XII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria (1+2+3+4+5+6+7+8)"] },
        { key: "ma3_24", label: "3. Supervisiones en campo", groups: ["XII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria (1+2+3+4+5+6+7+8)"] },
        { key: "ma3_25", label: "4. Inspecciones a obras físicas revestidas", groups: ["XII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria (1+2+3+4+5+6+7+8)"] },
        { key: "ma3_26", label: "5. Inspecciones a obras físicas artesanales", groups: ["XII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria (1+2+3+4+5+6+7+8)"] },
        { key: "ma3_27", label: "6. Limpieza de cuerpo hídrico", groups: ["XII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria (1+2+3+4+5+6+7+8)"] },
        { key: "ma3_28", label: "7. Organización y fundación de colaboradores voluntarios", groups: ["XII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria (1+2+3+4+5+6+7+8)"] },
        { key: "ma3_29", label: "8. Vigilancia a inmigrantes", groups: ["XII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria (1+2+3+4+5+6+7+8)"] },
        { key: "ma3_30", label: "1. Localidades inspeccionadas", groups: ["XII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Chagas (1+2+3+4)"] },
        { key: "ma3_31", label: "2. Viviendas inspeccionadas", groups: ["XII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Chagas (1+2+3+4)"] },
        { key: "ma3_32", label: "3. No. de notificaciones o denuncias por chinches", groups: ["XII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Chagas (1+2+3+4)"] },
        { key: "ma3_33", label: "4. No. de chinches examinadas", groups: ["XII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Chagas (1+2+3+4)"] },
        { key: "ma3_34", label: "1. Viviendas inspeccionadas", groups: ["XII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Leishmaniasis (1+2)"] },
        { key: "ma3_35", label: "2. No. Localidades investigadas por flebótomos", groups: ["XII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Leishmaniasis (1+2)"] },
      ],
    },
    {
      id: "ma4",
      title: "TABULADOR DIARIO DE SANEAMIENTO AMBIENTAL",
      subtitle: "XIII y XIV - Zoonosis / educacion",
      detailLabel: "Actividad",
      rows: [
        { key: "ma4_1", label: "1. Viviendas inspeccionadas para el control de roedores", groups: ["XIII. Zoonosis", "Inspecciones (1+2+3)"] },
        { key: "ma4_2", label: "2. Establecimientos inspeccionados para control de roedores", groups: ["XIII. Zoonosis", "Inspecciones (1+2+3)"] },
        { key: "ma4_3", label: "3. Observaciones a perros y gatos agresores.", groups: ["XIII. Zoonosis", "Inspecciones (1+2+3)"] },
        { key: "ma4_4", label: "1. No. de perros vacunados", groups: ["XIII. Zoonosis", "Vacunación antirrábica (1+2)"] },
        { key: "ma4_5", label: "2. No. de gatos vacunados", groups: ["XIII. Zoonosis", "Vacunación antirrábica (1+2)"] },
        { key: "ma4_6", label: "1. Rabia", groups: ["XIII. Zoonosis", "Muestras tomadas para diagnóstico"] },
        { key: "ma4_7", label: "1. Investigación de otras enfermedades zoonóticas", groups: ["XIII. Zoonosis", "Otras zoonosis"] },
        { key: "ma4_8", label: "1. Capacitaciones impartidas y recibidas", groups: ["XIV. Actividades de educación sanitaria y ambiental (1+2+3+4+5)", "Actividades de Educación"] },
        { key: "ma4_9", label: "2. Reuniones y coordinaciones", groups: ["XIV. Actividades de educación sanitaria y ambiental (1+2+3+4+5)", "Actividades de Educación"] },
        { key: "ma4_10", label: "3. Organización de grupos comunitarios", groups: ["XIV. Actividades de educación sanitaria y ambiental (1+2+3+4+5)", "Actividades de Educación"] },
        { key: "ma4_11", label: "4. Campañas", groups: ["XIV. Actividades de educación sanitaria y ambiental (1+2+3+4+5)", "Actividades de Educación"] },
        { key: "ma4_12", label: "5. Técnicas educativas sanitarias", groups: ["XIV. Actividades de educación sanitaria y ambiental (1+2+3+4+5)", "Actividades de Educación"] },
        { key: "ma4_13", label: "1. A establecimientos educativos públicos", groups: ["XV. Inspecciones a establecimientos educativos y centros de atención a primera infancia (1+2+3+4)", "Inspecciones"] },
        { key: "ma4_14", label: "2. A establecimientos educativos privados", groups: ["XV. Inspecciones a establecimientos educativos y centros de atención a primera infancia (1+2+3+4)", "Inspecciones"] },
        { key: "ma4_15", label: "3. A centros de atención a primera infancia y otros tipos de atención infantil", groups: ["XV. Inspecciones a establecimientos educativos y centros de atención a primera infancia (1+2+3+4)", "Inspecciones"] },
        { key: "ma4_16", label: "4. A establecimientos de educación no formal", groups: ["XV. Inspecciones a establecimientos educativos y centros de atención a primera infancia (1+2+3+4)", "Inspecciones"] },
        { key: "ma4_17", label: "1. Inspecciones a sitios de alta concurrencia", groups: ["XVI. Otras actividades de Salud Ambiental (1+2+3)", "Otras Actividades"] },
        { key: "ma4_18", label: "2. Atención a denuncias", groups: ["XVI. Otras actividades de Salud Ambiental (1+2+3)", "Otras Actividades"] },
        { key: "ma4_19", label: "3. Atención de solicitudes", groups: ["XVI. Otras actividades de Salud Ambiental (1+2+3)", "Otras Actividades"] },
        { key: "ma4_20", label: "1. Revisión de resultados de análisis de aguas residuales de tipo especial y ordinario en hospitales nacionales en cumplimiento al marco legal ambiental", groups: ["XVII. Gestión Ambiental Institucional", "Actividades (1+2+3+4)"] },
        { key: "ma4_21", label: "2. Revisión de resultados de análisis de emisiones atmosféricas de calderas, en hospitales nacionales, en cumplimiento al marco legal", groups: ["XVII. Gestión Ambiental Institucional", "Actividades (1+2+3+4)"] },
        { key: "ma4_22", label: "3. Generación de información para el cumplimiento de indicadores de gestión ambiental", groups: ["XVII. Gestión Ambiental Institucional", "Actividades (1+2+3+4)"] },
        { key: "ma4_23", label: "4. Actividades de verificación para el cumplimiento de la política ambiental institucional", groups: ["XVII. Gestión Ambiental Institucional", "Actividades (1+2+3+4)"] },
      ],
    },
    {
      id: "ma5",
      title: "TABULADOR DIARIO DE SANEAMIENTO AMBIENTAL",
      subtitle: "Resultados I - Calidad de agua",
      detailLabel: "Actividad",
      rows: [
        { key: "ma5_1", label: "1. Sistemas de abastecimiento de agua funcionando sanitariamente", groups: ["I. Calidad de agua para consumo humano"] },
        { key: "ma5_2", label: "2. Equipos productores de hipoclorito de sodio funcionando", groups: ["I. Calidad de agua para consumo humano"] },
        { key: "ma5_3", label: "2.1 Litros de hipoclorito de sodio producidos", groups: ["I. Calidad de agua para consumo humano"] },
        { key: "ma5_4", label: "2.2 Litros de hipoclorito de sodio distribuidos", groups: ["I. Calidad de agua para consumo humano"] },
        { key: "ma5_5", label: "2.3 Litros de hipoclorito de sodio entregados (establecimientos de salud, ongs y otros)", groups: ["I. Calidad de agua para consumo humano"] },
        { key: "ma5_6", label: "2.4 Viviendas y establecimientos usando hipoclorito de sodio", groups: ["I. Calidad de agua para consumo humano"] },
        { key: "ma5_7", label: "3. No. de fuentes de agua mejoradas (pozos excabados, pozos perforados, manantiales, agua lluvia, fuente comunitaria)", groups: ["I. Calidad de agua para consumo humano"] },
        { key: "ma5_8", label: "4. Muestras de análisis microbiológico dentro de los límites máximos permisibles (programa regular)", groups: ["I. Calidad de agua para consumo humano"] },
        { key: "ma5_9", label: "5. Muestras para análisis físico-químico dentro de los límites máximos permisibles (programa regular)", groups: ["I. Calidad de agua para consumo humano"] },
        { key: "ma5_10", label: "6. Muestra para análisis de trazas de metales dentro de los límites máximos permisibles (programa regular)", groups: ["I. Calidad de agua para consumo humano"] },
        { key: "ma5_11", label: "7. Resultados obtenidos de muestras de análisis microbiológico de agua de pozos artesanales o mejorados (programa regular)", groups: ["I. Calidad de agua para consumo humano"] },
        { key: "ma5_12", label: "8. Muestras para análisis microbiológico de puntos de uso dentro de los límites máximos permisibles (programa regular)", groups: ["I. Calidad de agua para consumo humano"] },
        { key: "ma5_13", label: "9. Muestras de agua para análisis de plaguicidas dentro de los límites máximos permisibles (programa regular)", groups: ["I. Calidad de agua para consumo humano"] },
        { key: "ma5_14", label: "10. Lecturas de cloro residual dentro de los límites máximos permisibles", groups: ["I. Calidad de agua para consumo humano"] },
        { key: "ma5_15", label: "11. No. de Planes de seguridad del agua resilientes al clima aprobados", groups: ["I. Calidad de agua para consumo humano"] },
      ],
    },
    {
      id: "ma6",
      title: "TABULADOR DIARIO DE SANEAMIENTO AMBIENTAL",
      subtitle: "Resultados II y III - Excretas / aguas",
      detailLabel: "Actividad",
      rows: [
        { key: "ma6_1", label: "1. No. de solicitudes para instalación de letrinas sin arrastre de agua cumpliendo requisitos administrativos", groups: ["II. Disposición de excretas"] },
        { key: "ma6_2", label: "2. No. de letrinas sin arrastre de agua construidas con base a normativa", groups: ["II. Disposición de excretas"] },
        { key: "ma6_3", label: "3. No. de letrinas sin arrastre de agua con uso y mantenimiento sanitario", groups: ["II. Disposición de excretas"] },
        { key: "ma6_4", label: "1. No. de solicitudes para instalación de sistemas de tratamiento aguas negras y grises cumpliendo requisitos administrativos", groups: ["III. Aguas negras y grises con infiltración al suelo"] },
        { key: "ma6_5", label: "2. No. de factibilidades de instalación de sistemas de tratamiento de aguas negras y grises con infiltración al suelo extendidas a viviendas y establecimientos", groups: ["III. Aguas negras y grises con infiltración al suelo"] },
        { key: "ma6_6", label: "3. No. de autorizaciones de sistemas de tratamiento de aguas negras y grises con infiltración al suelo extendidas a viviendas y establecimientos", groups: ["III. Aguas negras y grises con infiltración al suelo"] },
        { key: "ma6_7", label: "4. No. Sistemas de tratamiento individual de aguas negras y grises con infiltración al suelo, cumpliendo condiciones sanitarias", groups: ["III. Aguas negras y grises con infiltración al suelo"] },
        { key: "ma6_8", label: "5. No. sistemas de tratamiento individual de aguas negras y grises en proyectos habitacionales autorizados", groups: ["III. Aguas negras y grises con infiltración al suelo"] },
        { key: "ma6_9", label: "6. No. sistemas de tratamiento individual de aguas negras y grises en proyectos de agua y saneamiento autorizados", groups: ["III. Aguas negras y grises con infiltración al suelo"] },
        { key: "ma6_10", label: "1. No. de Establecimientos con piscinas y balnearios autorizados", groups: ["IV. Vigilancia sanitaria de aguas superficiales y piscinas"] },
        { key: "ma6_11", label: "2. No. de resultados obtenidos de muestras ambientales para análisis de Vibrio cholerae", groups: ["IV. Vigilancia sanitaria de aguas superficiales y piscinas"] },
        { key: "ma6_12", label: "3. No. de resultados obtenidos de muestras para análisis microbiológicos en aguas superficiales", groups: ["IV. Vigilancia sanitaria de aguas superficiales y piscinas"] },
        { key: "ma6_13", label: "4. No. de resultados obtenidos de muestras para análisis microbiológicos en piscina dentro de los valores permisibles", groups: ["IV. Vigilancia sanitaria de aguas superficiales y piscinas"] },
        { key: "ma6_14", label: "5. No. de muestras para análisis físico-químico en piscina dentro de los valores permisibles", groups: ["IV. Vigilancia sanitaria de aguas superficiales y piscinas"] },
        { key: "ma6_15", label: "6. No. de lecturas de cloro residual en piscina dentro de los valores permisibles", groups: ["IV. Vigilancia sanitaria de aguas superficiales y piscinas"] },
        { key: "ma6_16", label: "1. Establecimientos públicos generadores de desechos bioinfecciosos con manejo sanitario cumpliendo con reglamento", groups: ["V. Desechos bioinfecciosos"] },
        { key: "ma6_17", label: "2. Hospitales nacionales generadores de desechos bioinfecciosos, cumpliendo con reglamento", groups: ["V. Desechos bioinfecciosos"] },
        { key: "ma6_18", label: "3. Establecimientos privados generadores de desechos bioinfecciosos sin hospitalización, cumpliendo con reglamento", groups: ["V. Desechos bioinfecciosos"] },
        { key: "ma6_19", label: "4. Establecimientos privados generadores de desechos bioinfecciosos con hospitalización y otros generadores, cumpliendo con reglamento", groups: ["V. Desechos bioinfecciosos"] },
        { key: "ma6_20", label: "5. Instalaciones fisicas y sanitarias de establecimientos que recolectan y transportan desechos bioinfecciosos que cumplen con requerimientos de reglamento", groups: ["V. Desechos bioinfecciosos"] },
        { key: "ma6_21", label: "6. Instalaciones físicas y sanitarias de establecimientos que tratan desechos bioinfecciosos que cumplen con requerimientos de reglamento", groups: ["V. Desechos bioinfecciosos"] },
        { key: "ma6_22", label: "7. No. de visto bueno de planes de manejo de desechos bioinfecciosos", groups: ["V. Desechos bioinfecciosos"] },
      ],
    },
    {
      id: "ma7",
      title: "TABULADOR DIARIO DE SANEAMIENTO AMBIENTAL",
      subtitle: "Resultados VI y VII - Cadaveres",
      detailLabel: "Actividad",
      rows: [
        { key: "ma7_1", label: "1. Casas mortuorias o funerales, funerarias y sala de ventas de ataúdes, cumple con requerimientos de la norma", groups: ["VI. Manejo de cadáveres y restos humanos y otras actividades"] },
        { key: "ma7_2", label: "2. Cementerios públicos y privados, cumple con requerimientos de la norma", groups: ["VI. Manejo de cadáveres y restos humanos y otras actividades"] },
        { key: "ma7_3", label: "3. Crematorio, cumple con requerimientos de la norma", groups: ["VI. Manejo de cadáveres y restos humanos y otras actividades"] },
        { key: "ma7_4", label: "4. No. de instalaciones física en hospitales nacionales donde se manejan cadáveres y restos humanos, cumpliendo requerimientos de la Norma", groups: ["VI. Manejo de cadáveres y restos humanos y otras actividades"] },
        { key: "ma7_5", label: "5. No. vehículos que trasladan cadáveres cumpliendo con Norma", groups: ["VI. Manejo de cadáveres y restos humanos y otras actividades"] },
        { key: "ma7_6", label: "1. Exhumación, sellado y entrega de cadáveres y restos humanos, cumpliendo con requerimientos de la Norma", groups: ["VII. Instalaciones donde se manejan cadáveres y restos humanos y otras actividades"] },
        { key: "ma7_7", label: "2. Cremación de cadáveres y restos humanos, cumpliendo con Norma", groups: ["VII. Instalaciones donde se manejan cadáveres y restos humanos y otras actividades"] },
        { key: "ma7_8", label: "3. Otras actividades relacionados al manejo de cadáveres y restos humanos, que cumple con condiciones sanitarias", groups: ["VII. Instalaciones donde se manejan cadáveres y restos humanos y otras actividades"] },
        { key: "ma7_9", label: "4. Otras actividades relacionados al manejo de cadáveres y restos humanos dentro de hospitales nacionales, cumple con condiciones sanitarias", groups: ["VII. Instalaciones donde se manejan cadáveres y restos humanos y otras actividades"] },
        { key: "ma7_10", label: "1. Sitios de transferencia, cumplen condiciones de saneamiento de acuerdo a lineamiento técnico del MINSAL", groups: ["VIII. Residuos municipales"] },
        { key: "ma7_11", label: "2. Composteras, cumplen condiciones de saneamiento de acuerdo a lineamiento técnico del MINSAL", groups: ["VIII. Residuos municipales"] },
        { key: "ma7_12", label: "3. Rellenos sanitarios, cumplen condiciones de saneamiento de acuerdo a lineamiento técnico del MINSAL", groups: ["VIII. Residuos municipales"] },
        { key: "ma7_13", label: "1. Otros establecimientos comerciales, industriales y agroindustriales con vigilancia sanitaria", groups: ["IX. Establecimientos comerciales, servicios, industriales y agroindustriales"] },
        { key: "ma7_14", label: "2. Granjas avícolas y porcinas funcionando sanitariamente de acuerdo a normativa", groups: ["IX. Establecimientos comerciales, servicios, industriales y agroindustriales"] },
        { key: "ma7_15", label: "3. Plantas de sacrificio de animales con valor económico cumpliendo normativa (mataderos)", groups: ["IX. Establecimientos comerciales, servicios, industriales y agroindustriales"] },
        { key: "ma7_16", label: "4. Beneficios de café y recibideros de café funcionando sanitariamente de acuerdo a normativa", groups: ["IX. Establecimientos comerciales, servicios, industriales y agroindustriales"] },
        { key: "ma7_17", label: "5. No. de vehículos que transportan pulpa de café autorizados", groups: ["IX. Establecimientos comerciales, servicios, industriales y agroindustriales"] },
        { key: "ma7_18", label: "6. Ingenios azucareros funcionando sanitariamente de acuerdo a normativa", groups: ["IX. Establecimientos comerciales, servicios, industriales y agroindustriales"] },
        { key: "ma7_19", label: "7. No. de empresas de control de insectos y roedores cumpliendo con el reglamento", groups: ["IX. Establecimientos comerciales, servicios, industriales y agroindustriales"] },
        { key: "ma7_20", label: "8. Establecimientos que generan emisiones atmosféricas por fuentes fijas cumpliendo la normativa", groups: ["IX. Establecimientos comerciales, servicios, industriales y agroindustriales"] },
        { key: "ma7_21", label: "1. No. de hoteles, moteles, pensiones, hostales y casas de huéspedes, funcionando sanitariamente", groups: ["X. Establecimientos de hospedaje"] },
        { key: "ma7_22", label: "2. No. de permisos sanitarios otorgados a hoteles, moteles, pensiones, hostales y casas de huéspedes", groups: ["X. Establecimientos de hospedaje"] },
        { key: "ma7_23", label: "1. No. de salones de belleza, peluquerías, sauna y/o masajes, estudios de tatuaje y/o perforaciones, funcionando sanitariamente", groups: ["XI. Establecimientos de salones de belleza, peluquerias, sauna y/o masajes, estudios de tatuaje y/o perforaciones"] },
        { key: "ma7_24", label: "2. No. de permisos sanitarios otorgados a salones de belleza, peluquerías, sauna y/o masajes, estudios de tatuaje y/o perforaciones", groups: ["XI. Establecimientos de salones de belleza, peluquerias, sauna y/o masajes, estudios de tatuaje y/o perforaciones"] },
        { key: "ma7_25", label: "1. Muestras de moluscos bivalvos crudos dentro de norma", groups: ["XII. Vigilancia de niveles de saxitoxinas"] },
        { key: "ma7_26", label: "2. Muestras de moluscos bivalvos crudos fuera de norma", groups: ["XII. Vigilancia de niveles de saxitoxinas"] },
      ],
    },
    {
      id: "ma8",
      title: "TABULADOR DIARIO DE SANEAMIENTO AMBIENTAL",
      subtitle: "Resultados XIII - Arbovirosis",
      detailLabel: "Actividad",
      rows: [
        { key: "ma8_1", label: "1.1 Viviendas donde se aplicó larvicida al 1%", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Arbovirosis"] },
        { key: "ma8_2", label: "1.2. Viviendas termonebulizada con equipo portátil", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Arbovirosis"] },
        { key: "ma8_3", label: "1.3 Viviendas con aplicación de equipo pesado ULV", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Arbovirosis"] },
        { key: "ma8_4", label: "1.4 Vivienda termonebulizada con equipo pesado térmico", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Arbovirosis"] },
        { key: "ma8_5", label: "1.5 Criaderos de zancudos tratados", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Arbovirosis"] },
        { key: "ma8_6", label: "1.6 Criaderos de zancudos eliminados", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Arbovirosis"] },
        { key: "ma8_7", label: "2. Centros colectivos positivos", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Arbovirosis"] },
        { key: "ma8_8", label: "2.1. Centros colectivos donde se aplicó larvicida al 1%", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Arbovirosis"] },
        { key: "ma8_9", label: "2.2. Centros colectivos termonebulizado con equipo portátil", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Arbovirosis"] },
        { key: "ma8_10", label: "2.3. Centros colectivos termonebulizado con equipo pesado", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Arbovirosis"] },
        { key: "ma8_11", label: "3. No. de control de calidad realizados", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Arbovirosis"] },
        { key: "ma8_12", label: "3.1 No. de control de calidad con índices entomológicos bajo norma", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Arbovirosis"] },
        { key: "ma8_13", label: "4.1 Encuesta entomológica", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Arbovirosis"] },
        { key: "ma8_14", label: "4.2 No. de clasificaciones taxonómicas", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Arbovirosis"] },
        { key: "ma8_15", label: "5. Control de foco realizado", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Arbovirosis"] },
        { key: "ma8_16", label: "1.1 Localidades positivas a chinches", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Chagas"] },
        { key: "ma8_17", label: "1.2 Viviendas rociadas con producto residual", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Chagas"] },
        { key: "ma8_18", label: "1.3 No. de chinches examinadas", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Chagas"] },
        { key: "ma8_19", label: "1.4. No. de chinches positivas T. cruzi", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Chagas"] },
        { key: "ma8_20", label: "2.1 No. de viviendas positivas a chinchas", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Chagas"] },
        { key: "ma8_21", label: "2.2 No. de controles de foco realizados", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Chagas"] },
        { key: "ma8_22", label: "2.3 Notificación de resultados de chinches examinadas", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Chagas"] },
        { key: "ma8_23", label: "2.4 Coordinación de actividades realizadas", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Chagas"] },
        { key: "ma8_24", label: "3. No. de investigaciones entomológicas realizadas por notificación o denuncia", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Chagas"] },
        { key: "ma8_25", label: "3.1 No. de notificaciones de triatominos atendidas", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Chagas"] },
        { key: "ma8_26", label: "1.1 Viviendas termonebulizadas con equipo portátil", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Leishmaniasis"] },
        { key: "ma8_27", label: "1.2 Viviendas rociadas con producto residual", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Leishmaniasis"] },
        { key: "ma8_28", label: "1.3 No. de encuestas entomológica realizadas con trampas luz", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Leishmaniasis"] },
        { key: "ma8_29", label: "2.1 No. de localidades investigadas por flebótomo", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Leishmaniasis"] },
        { key: "ma8_30", label: "2.2 N° de localidades positivas por flebótomo", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Leishmaniasis"] },
        { key: "ma8_31", label: "2.3 No. de localidades fumigadas con equipo ULV pesado", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Leishmaniasis"] },
        { key: "ma8_32", label: "2.4 Encuestas entomológicas con otros métodos", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Leishmaniasis"] },
      ],
    },
    {
      id: "ma9",
      title: "TABULADOR DIARIO DE SANEAMIENTO AMBIENTAL",
      subtitle: "Resultados XIII - Malaria",
      detailLabel: "Actividad",
      rows: [
        { key: "ma9_1", label: "1.1 Gotas gruesas tomadas", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria"] },
        { key: "ma9_2", label: "1.2 Tratamientos antimalárico curativos administrados", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria"] },
        { key: "ma9_3", label: "1.3 Investigaciones epidemiológicas de caso", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria"] },
        { key: "ma9_4", label: "1.4 Viviendas positivas a Anopheles", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria"] },
        { key: "ma9_5", label: "1.5 Viviendas rociadas con producto residual", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria"] },
        { key: "ma9_6", label: "1.6 Viviendas fumigadas con equipo portátil térmico", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria"] },
        { key: "ma9_7", label: "1.7 Viviendas fumigadas con equipo pesado ULV", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria"] },
        { key: "ma9_8", label: "1.8 Viviendas fumigadas con equipo térmico pesado", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria"] },
        { key: "ma9_9", label: "2.1 Criaderos de zancudos rociados con larvicida", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria"] },
        { key: "ma9_10", label: "2.2 Metros cuadrados rociados con larvicida", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria"] },
        { key: "ma9_11", label: "2.3 Pesquisa larvaria del zancudo Anopheles", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria"] },
        { key: "ma9_12", label: "2.4 Captura de zancudo adulto Anopheles", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria"] },
        { key: "ma9_13", label: "2.5 Clasificación taxonómica", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria"] },
        { key: "ma9_14", label: "2.6 Bioensayos - pruebas", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria"] },
        { key: "ma9_15", label: "3.1 Supervisión a la red de notificación", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria"] },
        { key: "ma9_16", label: "3.2 Supervisión al personal de campo", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria"] },
        { key: "ma9_17", label: "4. Coordinación y mantenimiento de obras físicas revestidas", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria"] },
        { key: "ma9_18", label: "5. Coordinación y mantenimiento de obras físicas artesanales", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria"] },
        { key: "ma9_19", label: "6. Metros cuadrados de cuerpo hídrico en mantenimiento", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria"] },
        { key: "ma9_20", label: "7. No. de colaboradores voluntarios organizados", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria"] },
        { key: "ma9_21", label: "8. No. de inmigrantes identificados en puntos fronterizos y centros de trabajo", groups: ["XIII. Vigilancia y control de arbovirosis, malaria, chagas y leishmaniasis", "Malaria"] },
      ],
    },
    {
      id: "ma10",
      title: "TABULADOR DIARIO DE SANEAMIENTO AMBIENTAL",
      subtitle: "Resultados XIV - Zoonosis",
      detailLabel: "Actividad",
      rows: [
        { key: "ma10_1", label: "1.1 Viviendas tratadas para control de roedores", groups: ["XIV. Zoonosis", "Zoonosis"] },
        { key: "ma10_2", label: "2.1 Establecimientos tratados para control de roedores", groups: ["XIV. Zoonosis", "Zoonosis"] },
        { key: "ma10_3", label: "2.2 No. de controles de foco para leptospirosis", groups: ["XIV. Zoonosis", "Zoonosis"] },
        { key: "ma10_4", label: "2.3 Kilogramos de rodenticida utilizados en viviendas y establecimientos tratados", groups: ["XIV. Zoonosis", "Zoonosis"] },
        { key: "ma10_5", label: "3.1 No. de perros y gatos agresores observados", groups: ["XIV. Zoonosis", "Zoonosis"] },
        { key: "ma10_6", label: "3.2 Muestras positivas a rabia", groups: ["XIV. Zoonosis", "Zoonosis"] },
        { key: "ma10_7", label: "3.3 No. de controles de foco rábico realizados", groups: ["XIV. Zoonosis", "Zoonosis"] },
        { key: "ma10_8", label: "3.4 No. total de dosis de vacuna aplicada", groups: ["XIV. Zoonosis", "Zoonosis"] },
        { key: "ma10_9", label: "4.1 No. de investigaciones realizadas", groups: ["XIV. Zoonosis", "Zoonosis"] },
        { key: "ma10_10", label: "1.1 No. de capacitaciones impartidas y recibidas", groups: ["XV. Actividades de educación sanitaria y ambiental", "Actividades"] },
        { key: "ma10_11", label: "1.2 No. de personas capacitadas", groups: ["XV. Actividades de educación sanitaria y ambiental", "Actividades"] },
        { key: "ma10_12", label: "2.1 No. de reuniones de trabajo", groups: ["XV. Actividades de educación sanitaria y ambiental", "Actividades"] },
        { key: "ma10_13", label: "2.2 No. de coordinaciones", groups: ["XV. Actividades de educación sanitaria y ambiental", "Actividades"] },
        { key: "ma10_14", label: "3. No. de comités organizados", groups: ["XV. Actividades de educación sanitaria y ambiental", "Actividades"] },
        { key: "ma10_15", label: "4.1 No. de campañas realizadas", groups: ["XV. Actividades de educación sanitaria y ambiental", "Actividades"] },
        { key: "ma10_16", label: "4.2 No. de participantes en campañas realizadas", groups: ["XV. Actividades de educación sanitaria y ambiental", "Actividades"] },
        { key: "ma10_17", label: "4.3 Horas de perifoneo en campañas", groups: ["XV. Actividades de educación sanitaria y ambiental", "Actividades"] },
        { key: "ma10_18", label: "4.4 No. de actividades de promoción de campañas", groups: ["XV. Actividades de educación sanitaria y ambiental", "Actividades"] },
        { key: "ma10_19", label: "5.1 No. de charlas impartidas", groups: ["XV. Actividades de educación sanitaria y ambiental", "Actividades"] },
        { key: "ma10_20", label: "5.2. No. de sesiones educativas", groups: ["XV. Actividades de educación sanitaria y ambiental", "Actividades"] },
        { key: "ma10_21", label: "5.3 No. de demostraciones", groups: ["XV. Actividades de educación sanitaria y ambiental", "Actividades"] },
      ],
    },
    {
      id: "ma11",
      title: "TABULADOR DIARIO DE SANEAMIENTO AMBIENTAL",
      subtitle: "Resultados XVI-XVIII",
      detailLabel: "Actividad",
      rows: [
        { key: "ma11_1", label: "1. No. de establecimientos educativos públicos y privados con permiso sanitario y cumpliendo con el marco normativo vigente", groups: ["Resultados", "XVI. Establecimientos educativos y centros de atención a primera infancia"] },
        { key: "ma11_2", label: "2. No. de centros de atención a primera infancia y otros tipos de atención infantil, cumpliendo con el marco normativo vigente", groups: ["Resultados", "XVI. Establecimientos educativos y centros de atención a primera infancia"] },
        { key: "ma11_3", label: "3. No. de establecimientos de educación no formal con permiso sanitario y cumpliendo con el marco normativo vigente", groups: ["Resultados", "XVI. Establecimientos educativos y centros de atención a primera infancia"] },
        { key: "ma11_4", label: "1. No. de sitios de alta concurrencia con vigilancia sanitaria", groups: ["Resultados", "XVII. Otras actividades de Salud Ambiental"] },
        { key: "ma11_5", label: "2. No. de denuncias resueltas", groups: ["Resultados", "XVII. Otras actividades de Salud Ambiental"] },
        { key: "ma11_6", label: "3. No. de solicitudes resueltas", groups: ["Resultados", "XVII. Otras actividades de Salud Ambiental"] },
        { key: "ma11_7", label: "1. Número de actividades para la realización de análisis de aguas residuales de tipo especial y ordinario en hospitales nacionales en cumplimiento al marco legal ambiental", groups: ["Resultados", "XVIII. Gestión Ambiental Institucional"] },
        { key: "ma11_8", label: "2. Número de actividades para la realización de análisis de emisiones atmosféricas de calderas, en hospitales nacionales, como cumplimiento al marco legal", groups: ["Resultados", "XVIII. Gestión Ambiental Institucional"] },
        { key: "ma11_9", label: "3. Número de productos obtenidos para la generación de información referente al cumplimiento de indicadores de gestión ambiental", groups: ["Resultados", "XVIII. Gestión Ambiental Institucional"] },
        { key: "ma11_10", label: "4. Número de actividades de verificación para el cumplimiento de la política ambiental institucional", groups: ["Resultados", "XVIII. Gestión Ambiental Institucional"] },
      ],
    },
  ],
};
