// AUTO-GENERADO desde "BANCO DE SANGRE 2026.xlsx" (hoja MES ACTUAL).
// Tabulador SEPS de Banco de Sangre, servicio "banco-de-sangre".
import type { SepsTemplate } from "@/lib/seps-templates";

export const BANCO_SANGRE_TEMPLATE: SepsTemplate = {
  serviceId: "banco-de-sangre",
  establishment: "HOSPITAL NACIONAL EL SALVADOR",
  tables: [
    {
      id: "bs1",
      title: "TABULADOR DIARIO DE ACTIVIDADES DE BANCO DE SANGRE I",
      subtitle: "PERSONAS DONANTES",
      detailLabel: "Detalle",
      rows: [
        { key: "bs1_8", label: "Masculino", group: "Sexo" },
        { key: "bs1_9", label: "Femenino", group: "Sexo" },
        { key: "bs1_10", label: "17 - 24 años", group: "Grupos de edad" },
        { key: "bs1_11", label: "25 - 45 años", group: "Grupos de edad" },
        { key: "bs1_12", label: "46 - 59 años", group: "Grupos de edad" },
        { key: "bs1_13", label: "60 años y más", group: "Grupos de edad" },
        { key: "bs1_14", label: "Urbana", group: "Área" },
        { key: "bs1_15", label: "Rural", group: "Área" },
        { key: "bs1_16", label: "Altruista", group: "Tipo de donante" },
        { key: "bs1_17", label: "Altruista repetitivo", group: "Tipo de donante" },
        { key: "bs1_18", label: "Reposición", group: "Tipo de donante" },
        { key: "bs1_19", label: "Autólogos", group: "Tipo de donante" },
        { key: "bs1_20", label: "Aféresis voluntario", group: "Tipo de donante" },
        { key: "bs1_21", label: "Aféresis de reposición", group: "Tipo de donante" },
        { key: "bs1_22", label: "Si", group: "Pre-selección · Aceptado" },
        { key: "bs1_23", label: "No", group: "Pre-selección · Aceptado" },
        { key: "bs1_24", label: "Temporal", group: "Pre-selección · Diferido" },
        { key: "bs1_25", label: "Permanente", group: "Pre-selección · Diferido" },
        { key: "bs1_27", label: "No. Glóbulos rojos", group: "Aféresis" },
        { key: "bs1_28", label: "No. Plaquetas", group: "Aféresis" },
        { key: "bs1_29", label: "No. Plasma fresco", group: "Aféresis" },
        { key: "bs1_30", label: "Donación incompleta" },
      ],
    },
    {
      id: "bs2",
      title: "TABULADOR DIARIO DE ACTIVIDADES DE BANCO DE SANGRE III",
      subtitle: "TAMIZAJE SEROLÓGICO",
      detailLabel: "Detalle",
      rows: [
        { key: "bs2_39", label: "Tamizada", group: "Virus de Inmunodeficiencia Humana (VIH)" },
        { key: "bs2_40", label: "Reactiva", group: "Virus de Inmunodeficiencia Humana (VIH) · Resultado" },
        { key: "bs2_41", label: "No reactiva", group: "Virus de Inmunodeficiencia Humana (VIH) · Resultado" },
        { key: "bs2_42", label: "Indeterminada", group: "Virus de Inmunodeficiencia Humana (VIH) · Resultado" },
        { key: "bs2_43", label: "Tamizada", group: "Antígeno de superficie hepatitis B (HBsAg)" },
        { key: "bs2_44", label: "Reactiva", group: "Antígeno de superficie hepatitis B (HBsAg) · Resultado" },
        { key: "bs2_45", label: "No reactiva", group: "Antígeno de superficie hepatitis B (HBsAg) · Resultado" },
        { key: "bs2_46", label: "Indeterminada", group: "Antígeno de superficie hepatitis B (HBsAg) · Resultado" },
        { key: "bs2_47", label: "Tamizada", group: "Virus de hepatitis C (HCV)" },
        { key: "bs2_48", label: "Reactiva", group: "Virus de hepatitis C (HCV) · Resultado" },
        { key: "bs2_49", label: "No reactiva", group: "Virus de hepatitis C (HCV) · Resultado" },
        { key: "bs2_50", label: "Indeterminada", group: "Virus de hepatitis C (HCV) · Resultado" },
        { key: "bs2_51", label: "Tamizada", group: "Chagas" },
        { key: "bs2_52", label: "Reactiva", group: "Chagas · Resultado" },
        { key: "bs2_53", label: "No reactiva", group: "Chagas · Resultado" },
        { key: "bs2_54", label: "Indeterminada", group: "Chagas · Resultado" },
        { key: "bs2_55", label: "Tamizada", group: "Sífilis" },
        { key: "bs2_56", label: "Reactiva", group: "Sífilis · Resultado" },
        { key: "bs2_57", label: "No reactiva", group: "Sífilis · Resultado" },
        { key: "bs2_58", label: "Indeterminada", group: "Sífilis · Resultado" },
        { key: "bs2_59", label: "Tamizada", group: "Citomegalovirus (CMV)" },
        { key: "bs2_60", label: "Reactiva", group: "Citomegalovirus (CMV) · Resultado" },
        { key: "bs2_61", label: "No reactiva", group: "Citomegalovirus (CMV) · Resultado" },
        { key: "bs2_62", label: "Indeterminada", group: "Citomegalovirus (CMV) · Resultado" },
        { key: "bs2_63", label: "Tamizada", group: "Anticuerpo Hepatitis B Core (AntiHBc)" },
        { key: "bs2_64", label: "Reactiva", group: "Anticuerpo Hepatitis B Core (AntiHBc) · Resultado" },
        { key: "bs2_65", label: "No reactiva", group: "Anticuerpo Hepatitis B Core (AntiHBc) · Resultado" },
        { key: "bs2_66", label: "Indeterminada", group: "Anticuerpo Hepatitis B Core (AntiHBc) · Resultado" },
        { key: "bs2_67", label: "No. de tipeos sanguíneos" },
        { key: "bs2_68", label: "No. de rastreos de anticuerpos irregulares" },
      ],
    },
    {
      id: "bs3",
      title: "TABULADOR DIARIO DE ACTIVIDADES DE BANCO DE SANGRE IV",
      subtitle: "PACIENTES TRANSFUNDIDOS",
      detailLabel: "Detalle",
      rows: [
        { key: "bs3_77", label: "No. de niños transfundidos", group: "Niño(a) menores de 10 años" },
        { key: "bs3_78", label: "1. Consulta Externa", group: "Niño(a) menores de 10 años · Servicio de procedencia" },
        { key: "bs3_79", label: "2. Hospitalización", group: "Niño(a) menores de 10 años · Servicio de procedencia" },
        { key: "bs3_80", label: "3. Emergencia", group: "Niño(a) menores de 10 años · Servicio de procedencia" },
        { key: "bs3_81", label: "4. Hospital de día", group: "Niño(a) menores de 10 años · Servicio de procedencia" },
        { key: "bs3_82", label: "Sangre completa", group: "Niño(a) menores de 10 años" },
        { key: "bs3_83", label: "Glóbulos rojos empacados", group: "Niño(a) menores de 10 años" },
        { key: "bs3_84", label: "Plasma fresco congelado", group: "Niño(a) menores de 10 años" },
        { key: "bs3_85", label: "Crioprecipitado", group: "Niño(a) menores de 10 años" },
        { key: "bs3_86", label: "Concentrado plaquetario", group: "Niño(a) menores de 10 años" },
        { key: "bs3_87", label: "Glóbulos rojos", group: "Niño(a) menores de 10 años · Unidades de aféresis" },
        { key: "bs3_88", label: "Plaquetas", group: "Niño(a) menores de 10 años · Unidades de aféresis" },
        { key: "bs3_89", label: "Plasma", group: "Niño(a) menores de 10 años · Unidades de aféresis" },
        { key: "bs3_90", label: "Plaquetaféresis", group: "Niño(a) menores de 10 años · Procedimientos terapéuticos" },
        { key: "bs3_91", label: "Plasmaféresis", group: "Niño(a) menores de 10 años · Procedimientos terapéuticos" },
        { key: "bs3_92", label: "Eritroaféresis", group: "Niño(a) menores de 10 años · Procedimientos terapéuticos" },
        { key: "bs3_93", label: "Recambio plasmático", group: "Niño(a) menores de 10 años · Procedimientos terapéuticos" },
        { key: "bs3_94", label: "Sangría", group: "Niño(a) menores de 10 años · Procedimientos terapéuticos" },
        { key: "bs3_95", label: "No. de personas transfundidas", group: "10 a 19 años" },
        { key: "bs3_96", label: "1. Consulta Externa", group: "10 a 19 años · Servicio de procedencia" },
        { key: "bs3_97", label: "2. Hospitalización", group: "10 a 19 años · Servicio de procedencia" },
        { key: "bs3_98", label: "3. Emergencia", group: "10 a 19 años · Servicio de procedencia" },
        { key: "bs3_99", label: "4. Hospital de día", group: "10 a 19 años · Servicio de procedencia" },
        { key: "bs3_100", label: "Sangre completa", group: "10 a 19 años" },
        { key: "bs3_101", label: "Glóbulos rojos empacados", group: "10 a 19 años" },
        { key: "bs3_102", label: "Plasma fresco congelado", group: "10 a 19 años" },
        { key: "bs3_103", label: "Crioprecipitado", group: "10 a 19 años" },
        { key: "bs3_104", label: "Concentrado plaquetario", group: "10 a 19 años" },
        { key: "bs3_105", label: "Glóbulos rojos", group: "10 a 19 años · Unidades de aféresis" },
        { key: "bs3_106", label: "Plaquetas", group: "10 a 19 años · Unidades de aféresis" },
        { key: "bs3_107", label: "Plasma PCC-19", group: "10 a 19 años · Unidades de aféresis" },
        { key: "bs3_108", label: "Plaquetaféresis", group: "10 a 19 años · Procedimientos terapéuticos" },
        { key: "bs3_109", label: "Plasmaféresis", group: "10 a 19 años · Procedimientos terapéuticos" },
        { key: "bs3_110", label: "Eritroaféresis", group: "10 a 19 años · Procedimientos terapéuticos" },
        { key: "bs3_111", label: "Recambio plasmático", group: "10 a 19 años · Procedimientos terapéuticos" },
        { key: "bs3_112", label: "Sangría", group: "10 a 19 años · Procedimientos terapéuticos" },
      ],
    },
    {
      id: "bs4",
      title: "TABULADOR DIARIO DE ACTIVIDADES DE BANCO DE SANGRE V",
      subtitle: "PACIENTES TRANSFUNDIDOS",
      detailLabel: "Detalle",
      rows: [
        { key: "bs4_122", label: "No. de personas transfundidas", group: "20 a 59 años" },
        { key: "bs4_123", label: "1. Consulta Externa", group: "20 a 59 años · Servicio de procedencia" },
        { key: "bs4_124", label: "2. Hospitalización", group: "20 a 59 años · Servicio de procedencia" },
        { key: "bs4_125", label: "3. Emergencia", group: "20 a 59 años · Servicio de procedencia" },
        { key: "bs4_126", label: "4. Hospital de día", group: "20 a 59 años · Servicio de procedencia" },
        { key: "bs4_127", label: "Sangre completa", group: "20 a 59 años" },
        { key: "bs4_128", label: "Glóbulos rojos empacados", group: "20 a 59 años" },
        { key: "bs4_129", label: "Plasma fresco congelado", group: "20 a 59 años" },
        { key: "bs4_130", label: "Crioprecipitado", group: "20 a 59 años" },
        { key: "bs4_131", label: "Concentrado plaquetario", group: "20 a 59 años" },
        { key: "bs4_132", label: "Glóbulos rojos", group: "20 a 59 años · Unidades de aféresis" },
        { key: "bs4_133", label: "Plaquetas", group: "20 a 59 años · Unidades de aféresis" },
        { key: "bs4_134", label: "Plasma", group: "20 a 59 años · Unidades de aféresis" },
        { key: "bs4_135", label: "Plaquetaféresis", group: "20 a 59 años · Procedimientos terapéuticos" },
        { key: "bs4_136", label: "Plasmaféresis", group: "20 a 59 años · Procedimientos terapéuticos" },
        { key: "bs4_137", label: "Eritroaféresis", group: "20 a 59 años · Procedimientos terapéuticos" },
        { key: "bs4_138", label: "Recambio plasmático", group: "20 a 59 años · Procedimientos terapéuticos" },
        { key: "bs4_139", label: "Sangría", group: "20 a 59 años · Procedimientos terapéuticos" },
        { key: "bs4_140", label: "No. de personas transfundidas", group: "60 años y más" },
        { key: "bs4_141", label: "1. Consulta Externa", group: "60 años y más · Servicio de procedencia" },
        { key: "bs4_142", label: "2. Hospitalización", group: "60 años y más · Servicio de procedencia" },
        { key: "bs4_143", label: "3. Emergencia", group: "60 años y más · Servicio de procedencia" },
        { key: "bs4_144", label: "4. Hospital de día", group: "60 años y más · Servicio de procedencia" },
        { key: "bs4_145", label: "Sangre completa", group: "60 años y más" },
        { key: "bs4_146", label: "Glóbulos rojos empacados", group: "60 años y más" },
        { key: "bs4_147", label: "Plasma fresco congelado", group: "60 años y más" },
        { key: "bs4_148", label: "Crioprecipitado", group: "60 años y más" },
        { key: "bs4_149", label: "Concentrado plaquetario", group: "60 años y más" },
        { key: "bs4_150", label: "Glóbulos rojos", group: "60 años y más · Unidades de aféresis" },
        { key: "bs4_151", label: "Plaquetas", group: "60 años y más · Unidades de aféresis" },
        { key: "bs4_152", label: "Plasma", group: "60 años y más · Unidades de aféresis" },
        { key: "bs4_153", label: "Plaquetaféresis", group: "60 años y más · Procedimientos terapéuticos" },
        { key: "bs4_154", label: "Plasmaféresis", group: "60 años y más · Procedimientos terapéuticos" },
        { key: "bs4_155", label: "Eritroaféresis", group: "60 años y más · Procedimientos terapéuticos" },
        { key: "bs4_156", label: "Recambio plasmático", group: "60 años y más · Procedimientos terapéuticos" },
        { key: "bs4_157", label: "Sangría", group: "60 años y más · Procedimientos terapéuticos" },
      ],
    },
    {
      id: "bs5",
      title: "TABULADOR DIARIO DE ACTIVIDADES DE BANCO DE SANGRE",
      subtitle: "EXISTENCIAS DIARIAS",
      detailLabel: "Detalle",
      rows: [
        { key: "bs5_167", label: "A RH (+)", group: "Grupo ll · Glóbulo rojo empacados (Unidades)" },
        { key: "bs5_168", label: "A Rh (-)", group: "Grupo ll · Glóbulo rojo empacados (Unidades)" },
        { key: "bs5_169", label: "B Rh (+)", group: "Grupo ll · Glóbulo rojo empacados (Unidades)" },
        { key: "bs5_170", label: "B Rh (-)", group: "Grupo ll · Glóbulo rojo empacados (Unidades)" },
        { key: "bs5_171", label: "AB Rh (+)", group: "Grupo ll · Glóbulo rojo empacados (Unidades)" },
        { key: "bs5_172", label: "AB Rh (-)", group: "Grupo ll · Glóbulo rojo empacados (Unidades)" },
        { key: "bs5_173", label: "O Rh (+)", group: "Grupo ll · Glóbulo rojo empacados (Unidades)" },
        { key: "bs5_174", label: "O Rh (-)", group: "Grupo ll · Glóbulo rojo empacados (Unidades)" },
        { key: "bs5_175", label: "A Rh (+)", group: "Grupo ll · Concentrado de plaquetas (Unidades)" },
        { key: "bs5_176", label: "A Rh (-)", group: "Grupo ll · Concentrado de plaquetas (Unidades)" },
        { key: "bs5_177", label: "B Rh (+)", group: "Grupo ll · Concentrado de plaquetas (Unidades)" },
        { key: "bs5_178", label: "B Rh (-)", group: "Grupo ll · Concentrado de plaquetas (Unidades)" },
        { key: "bs5_179", label: "AB Rh (+)", group: "Grupo ll · Concentrado de plaquetas (Unidades)" },
        { key: "bs5_180", label: "AB Rh (-)", group: "Grupo ll · Concentrado de plaquetas (Unidades)" },
        { key: "bs5_181", label: "O Rh (+)", group: "Grupo ll · Concentrado de plaquetas (Unidades)" },
        { key: "bs5_182", label: "O Rh (-)", group: "Grupo ll · Concentrado de plaquetas (Unidades)" },
        { key: "bs5_183", label: "Plasma fresco congelado", group: "Grupo ll · Otros Hemocomponentes (Unidades)" },
        { key: "bs5_184", label: "Plaqueta por aféresis", group: "Grupo ll · Otros Hemocomponentes (Unidades)" },
        { key: "bs5_185", label: "Crioprecipitado", group: "Grupo ll · Otros Hemocomponentes (Unidades)" },
        { key: "bs5_186", label: "Plasma por aférisis", group: "Grupo ll · Otros Hemocomponentes (Unidades)" },
      ],
    },
    {
      id: "bs6",
      title: "TABULADOR DIARIO DE ACTIVIDADES DE BANCO DE SANGRE",
      subtitle: "BANCO DE SANGRE II. HEMOCOMPONENTES",
      detailLabel: "Detalle",
      rows: [
        { key: "bs6_195", label: "1. Sangre completa no fraccionada", group: "Preparación de unidades de hemocomponentes" },
        { key: "bs6_196", label: "2. Sangre total reconstituida", group: "Preparación de unidades de hemocomponentes" },
        { key: "bs6_197", label: "3. Glóbulo rojo empacado", group: "Preparación de unidades de hemocomponentes" },
        { key: "bs6_198", label: "4. Concentrado plaquetario", group: "Preparación de unidades de hemocomponentes" },
        { key: "bs6_199", label: "5. Plasma fresco congelado", group: "Preparación de unidades de hemocomponentes" },
        { key: "bs6_200", label: "6. Crioprecipitado", group: "Preparación de unidades de hemocomponentes" },
        { key: "bs6_201", label: "7. Glóbulo rojo empacado leucorreducido buffy coat", group: "Preparación de unidades de hemocomponentes" },
        { key: "bs6_202", label: "8. Glóbulo rojo empacado leucorreducido por filtro leucorreductor", group: "Preparación de unidades de hemocomponentes" },
        { key: "bs6_203", label: "9. Concentrado plaquetario x filtro leucorreductor", group: "Preparación de unidades de hemocomponentes" },
        { key: "bs6_204", label: "10. Concentrado plaquetario por aféresis", group: "Preparación de unidades de hemocomponentes" },
        { key: "bs6_205", label: "11. Glóbulo rojo empacado por aféresis", group: "Preparación de unidades de hemocomponentes" },
        { key: "bs6_206", label: "12. Plasma fresco por aféresis", group: "Preparación de unidades de hemocomponentes" },
        { key: "bs6_207", label: "Vencimiento", group: "Descarte de unidades de hemocomponentes · 1. Sangre completa" },
        { key: "bs6_208", label: "Desperfecto de bolsa", group: "Descarte de unidades de hemocomponentes · 1. Sangre completa" },
        { key: "bs6_209", label: "Otras razones diferentes a agente infeccioso", group: "Descarte de unidades de hemocomponentes · 1. Sangre completa" },
        { key: "bs6_210", label: "Tamizaje", group: "Descarte de unidades de hemocomponentes · 1. Sangre completa" },
        { key: "bs6_211", label: "Vencimiento", group: "Descarte de unidades de hemocomponentes · 2. Glóbulos rojos" },
        { key: "bs6_212", label: "Desperfecto de bolsa", group: "Descarte de unidades de hemocomponentes · 2. Glóbulos rojos" },
        { key: "bs6_213", label: "Otras razones diferentes a agente infeccioso", group: "Descarte de unidades de hemocomponentes · 2. Glóbulos rojos" },
        { key: "bs6_214", label: "Tamizaje", group: "Descarte de unidades de hemocomponentes · 2. Glóbulos rojos" },
        { key: "bs6_215", label: "Vencimiento", group: "Descarte de unidades de hemocomponentes · 3. Plasma fresco congelado" },
        { key: "bs6_216", label: "Desperfecto de bolsa", group: "Descarte de unidades de hemocomponentes · 3. Plasma fresco congelado" },
        { key: "bs6_217", label: "Otras razones diferentes a agente infeccioso", group: "Descarte de unidades de hemocomponentes · 3. Plasma fresco congelado" },
        { key: "bs6_218", label: "Tamizaje", group: "Descarte de unidades de hemocomponentes · 3. Plasma fresco congelado" },
        { key: "bs6_219", label: "Vencimiento", group: "Descarte de unidades de hemocomponentes · 4. Crioprecipitado" },
        { key: "bs6_220", label: "Desperfecto de bolsa", group: "Descarte de unidades de hemocomponentes · 4. Crioprecipitado" },
        { key: "bs6_221", label: "Otras razones diferentes a agente infeccioso", group: "Descarte de unidades de hemocomponentes · 4. Crioprecipitado" },
        { key: "bs6_222", label: "Tamizaje", group: "Descarte de unidades de hemocomponentes · 4. Crioprecipitado" },
        { key: "bs6_223", label: "Vencimiento", group: "Descarte de unidades de hemocomponentes · 5. Concentrado plaquetario" },
        { key: "bs6_224", label: "Desperfecto de bolsa", group: "Descarte de unidades de hemocomponentes · 5. Concentrado plaquetario" },
        { key: "bs6_225", label: "Otras razones diferentes a agente infeccioso", group: "Descarte de unidades de hemocomponentes · 5. Concentrado plaquetario" },
        { key: "bs6_226", label: "Tamizaje", group: "Descarte de unidades de hemocomponentes · 5. Concentrado plaquetario" },
      ],
    },
  ],
};
