// AUTO-GENERADO: catálogo LNR (secciones + pruebas) del sistema real de Laboratorio.
// Alimenta los desplegables Sección -> Prueba del nuevo formato SEPS de Laboratorio.
export type LabTest = { code: string; name: string };
export type LabSection = { code: string; name: string; tests: LabTest[] };

export const LAB_SECTIONS: LabSection[] = [
  { code: "H", name: "Hematología", tests: [
    { code: "H1", name: "Hematócrito" },
    { code: "H2", name: "Hemoglobina" },
    { code: "H3", name: "Leucograma" },
    { code: "H5", name: "Reticulocitos" },
    { code: "H6", name: "Recuento de Plaquetas" },
    { code: "H7", name: "Frotis de Sangre Periférica" },
    { code: "H8", name: "Eritrosedimentación" },
    { code: "H9", name: "Tiempo de Sangramiento" },
    { code: "H10", name: "Tiempo de Coagulación" },
    { code: "H11", name: "Tiempo y valor de Protrombina" },
    { code: "H12", name: "Tiempo de Tromboplastina parcial" },
    { code: "H13", name: "Tiempo de Trombina" },
    { code: "H14", name: "Antitrombina" },
    { code: "H15", name: "Corrección y Dilución TP, TTP, TT" },
    { code: "H16", name: "Factor VIII" },
    { code: "H17", name: "Retracción del Coágulo" },
    { code: "H18", name: "Células L.E." },
    { code: "H20", name: "Fibrinógeno" },
    { code: "H21", name: "Prueba de Anoxia (Células Falciformes)" },
    { code: "H22", name: "Lisis Euglobulina" },
    { code: "H23", name: "Gota Gruesa Plasmodium (Malaria)" },
    { code: "H24", name: "Gota Gruesa Tripanosoma cruzi (Chagas)" },
    { code: "H25", name: "Concentrado Strout" },
    { code: "H26", name: "Fragilidad osmótica globular" },
    { code: "H27", name: "Productos de Degradación del Fibrinógeno" },
    { code: "H28", name: "Coloración de Hemosiderina" },
    { code: "H29", name: "Coloración de Peroxidasa" },
    { code: "H30", name: "Recuento de Eosinófilos en secreción nasal" },
    { code: "H31", name: "Hemoglobina Fetal" },
    { code: "H32", name: "Hemoglobina por Electroforesis" },
    { code: "H33", name: "Ácido Fólico" },
    { code: "H34", name: "Médula Ósea, recuento diferencial" },
    { code: "H35", name: "Espermograma" },
    { code: "H36", name: "Factor IX" },
    { code: "H37", name: "Factor XIII" },
    { code: "H38", name: "Factor XI" },
    { code: "H40", name: "Factor V" },
    { code: "H42", name: "Recuento Linfocitos CD4/CD8" },
    { code: "H43", name: "Hemoglobina A2" },
    { code: "H44", name: "Factor XII" },
    { code: "H45", name: "Factor X" },
    { code: "H46", name: "Factor VII" },
    { code: "H47", name: "Factor II" },
    { code: "H48", name: "Proteína S (coagulación)" },
    { code: "H49", name: "Proteína C coagulación" },
    { code: "H50", name: "Anticoagulante Lúpico" },
    { code: "H51", name: "Dímero D" },
    { code: "H52", name: "Plasminógeno" },
    { code: "H53", name: "Factor von Willebrand (Co-Factor de Ristocetina)" },
    { code: "H54", name: "Inhibidor al Factor VIII" },
    { code: "H55", name: "Inhibidor al Factor IX" },
    { code: "H56", name: "Cariotipo en sangre periférica para X frágil" },
    { code: "H57", name: "Cariotipo en sangre periférica" },
    { code: "H58", name: "Hemograma automatizado" },
    { code: "H59", name: "Gota fresca para T. cruzi" },
    { code: "H60", name: "Hemograma para embarazadas automatizados" },
    { code: "H61", name: "Microhematócrito para T. cruzi" },
    { code: "H62", name: "Control de calidad externo Hematología" },
    { code: "H64", name: "Factor Von Willebrand AG (Parte Antigénica)" },
    { code: "H65", name: "Factor VIII Cromogénico" },
    { code: "H66", name: "Resistencia a la proteína C Activada" },
    { code: "H67", name: "HT para embarazada (manual)" },
    { code: "H68", name: "HB para embarazada (manual)" },
    { code: "H69", name: "Control de Calidad indirecto Gota Gruesa (Plasmodium)" },
    { code: "H70", name: "Control de Calidad indirecto Trypanosoma cruzi" },
    { code: "H71", name: "Control de Calidad Externo de Gota Gruesa (Plasmodium)" },
    { code: "H72", name: "Control de Calidad Externo Trypanosoma cruzi" },
    { code: "H73", name: "Leucograma para embarazadas (Manual)" },
    { code: "H74", name: "Plaquetas para embarazadas (Manual)" },
    { code: "H75", name: "HT 1 perfil prenatal (manual)" },
    { code: "H76", name: "HB 1 perfil prenatal (manual)" },
    { code: "H77", name: "Leucograma 1 perfil prenatal (manual)" },
    { code: "H78", name: "Recuento de plaquetas 1 perfil prenatal (manual)" },
    { code: "H79", name: "Hemograma automatizado 1 perfil prenatal" },
    { code: "H80", name: "HT 2 perfil prenatal (manual)" },
    { code: "H81", name: "HB 2 perfil prenatal (manual)" },
    { code: "H82", name: "Leucograma 2 perfil prenatal (manual)" },
    { code: "H83", name: "Recuento de plaquetas 2 perfil prenatal (manual)" },
    { code: "H84", name: "Hemograma automatizado 2 perfil prenatal" },
    { code: "H85", name: "HT 3 perfil prenatal (manual)" },
    { code: "H86", name: "HB 3 perfil prenatal (manual)" },
    { code: "H87", name: "Leucograma 3 perfil prenatal (manual)" },
    { code: "H88", name: "Recuento de plaquetas 3 perfil prenatal (manual)" },
    { code: "H89", name: "Hemograma automatizado 3 perfil prenatal" },
    { code: "H90", name: "Neutrófilo en banda" },
    { code: "H91", name: "Citometría de Flujo para Inmunofenotipo de leucemias" },
    { code: "H92", name: "BCR ABL para leucemias" },
  ] },
  { code: "I", name: "Inmunología", tests: [
    { code: "I2", name: "Anticuerpos Antinucleares (ANA)" },
    { code: "I3", name: "Antígenos Febriles" },
    { code: "I4", name: "Anticuerpos heterófilos (Monotest Paul Bunnel)" },
    { code: "I5", name: "Antiestreptolisinas \"O\"" },
    { code: "I6", name: "Anticuerpos Streptococos hemolíticos" },
    { code: "I7", name: "Factor Reumatoideo" },
    { code: "I8", name: "Anticuerpos Treponema pallidum" },
    { code: "I9", name: "Hormona folículo estimulante (FSH)" },
    { code: "I10", name: "Gonadotropina coriónica cualitativa (sangre)" },
    { code: "I11", name: "Gonadotropina coriónica cuantitativa (sangre)" },
    { code: "I12", name: "Prueba de Microaglutinación (MAT-Leptospirosis)" },
    { code: "I13", name: "Proteína C reactiva" },
    { code: "I14", name: "Proteína C reactiva cuantitativa" },
    { code: "I15", name: "Gonadotropina coriónica cualitativa (orina)" },
    { code: "I17", name: "Tamizaje IFI Influenza" },
    { code: "I18", name: "Factor reumatoideo (Látex cuantitativo)" },
    { code: "I19", name: "Anticuerpos para Toxoplasma (IgM)" },
    { code: "I20", name: "Prolactina" },
    { code: "I21", name: "Hormona Luteinizante (LH)" },
    { code: "I22", name: "Serología, Sífilis donantes" },
    { code: "I23", name: "Prueba rápida de serología para sífilis otros grupos" },
    { code: "I24", name: "Prueba rápida de serología para sífilis cuantitativa" },
    { code: "I25", name: "Triyodotironina (T3)" },
    { code: "I26", name: "Tiroxina (T4)" },
    { code: "I27", name: "Anticuerpos para Toxoplasma (IgG)" },
    { code: "I28", name: "Hormona estimulante de la tiroides (TSH)" },
    { code: "I29", name: "Inmunofluorescencia para Chagas" },
    { code: "I30", name: "Anticuerpos Ehrlichia chaffeensis" },
    { code: "I31", name: "Anticuerpos Rickettsia typhi" },
    { code: "I32", name: "Anticuerpos Rickettsia rickettsii" },
    { code: "I33", name: "Prueba biológica Rabia" },
    { code: "I34", name: "Prueba rápida de serología para sífilis embarazada 1 perfil prenatal" },
    { code: "I35", name: "Anticuerpos IgE" },
    { code: "I36", name: "Testosterona" },
    { code: "I37", name: "Control de calidad externo Serología de Sífilis" },
    { code: "I38", name: "Control de calidad interno serología de sífilis" },
    { code: "I39", name: "Prueba de Leptospirosis IgM" },
    { code: "I40", name: "Fracción C3 del Complemento" },
    { code: "I42", name: "Antígeno CEA" },
    { code: "I43", name: "Anticuerpos IgM Hepatitis A" },
    { code: "I45", name: "Prueba rápida de serología para sífilis embarazada 2 perfil prenatal" },
    { code: "I46", name: "Fracción C4 del Complemento" },
    { code: "I47", name: "Antígenos prostáticos específico" },
    { code: "I48", name: "Anti CCP" },
    { code: "I49", name: "Mioglobina" },
    { code: "I50", name: "TSH Tamizaje neonatal" },
    { code: "I52", name: "Citomegalovirus (IgM)" },
    { code: "I53", name: "Pneumocystis carinii" },
    { code: "I54", name: "Anti DNA nativo" },
    { code: "I55", name: "Tiroglobulina" },
    { code: "I56", name: "Anticuerpos Anti tiroglobulina" },
    { code: "I57", name: "Anticuerpos Anti Peroxidasa" },
    { code: "I58", name: "Ac. Histoplasma capsulatum" },
    { code: "I59", name: "Control de calidad indirecto de sífilis" },
    { code: "I60", name: "Confirmación Ac. Treponema pallidum (Prueba Rápida)" },
    { code: "I62", name: "Confirmación Ac. IgM Treponema pallidum (ELISA)" },
    { code: "I63", name: "Confirmación Serología Sífilis (RPR/VDRL)" },
    { code: "I64", name: "Anticuerpos IgG Citomegalovirus" },
    { code: "I65", name: "Antígeno Carbohidratado 19-9 (CA 19-9)" },
    { code: "I66", name: "Antígeno 125 del Cáncer (CA 125)" },
    { code: "I67", name: "Marcador Tumoral CA 15-3 Ag." },
    { code: "I68", name: "Prueba para Detección del Papiloma Humano" },
    { code: "I69", name: "Serología para sífilis cualitativa" },
    { code: "I71", name: "Hormona Paratiroidea (PTH)" },
    { code: "I72", name: "Sífilis seguimiento" },
    { code: "I73", name: "Interleucina 6" },
    { code: "I74", name: "Prueba rápida para identificación de Ag y/o Ac para virus respiratorio SARS-CoV" },
    { code: "I75", name: "Anticuerpos IgG para SARS-CoV" },
    { code: "I76", name: "Anticuerpos IgM para SARS-CoV" },
    { code: "I77", name: "Helicobacter pylori Antígeno" },
    { code: "I78", name: "Helicobacter pylori Anticuerpo" },
    { code: "I79", name: "Antígeno para SARS-CoV-2" },
    { code: "I80", name: "Péptidos Natriuréticos" },
    { code: "I82", name: "Anticardiolipina" },
    { code: "I83", name: "Serología Sífilis en usuarios VICTS" },
    { code: "I84", name: "Prueba rápida de serología para sífilis embarazada 3 perfil prenatal" },
    { code: "I85", name: "Antígeno Salmonella typhi" },
    { code: "I86", name: "Antígeno Salmonella paratyphi" },
    { code: "I87", name: "IRT Determinación de Tripsina Inmunoreactiva" },
    { code: "I88", name: "PKU Determinación fenilalanina" },
    { code: "I89", name: "17-OH Determinación de progesterona" },
    { code: "I90", name: "LEU/ISO Determinación de aminoácidos para diagnóstico de enfermedad jarabe de arce" },
    { code: "I91", name: "Valina Determinación de aminoácidos para diagnóstico de enfermedad jarabe de arce" },
    { code: "I92", name: "Prueba B2 Glicoproteína 1" },
    { code: "I93", name: "Prueba anticuerpos Anticitoplásmicos del Neutrófilo" },
    { code: "I94", name: "Prueba Anticuerpos ANTI SSA (ENAS)" },
    { code: "I95", name: "Prueba ANA SCREEN" },
    { code: "I96", name: "Tetrayodotironina libre (T4)" },
    { code: "I97", name: "Triyodotironina libre (T3)" },
    { code: "I98", name: "Prueba rápida de Antígeno para Salmonella Typhi/Paratyphi" },
    { code: "I99", name: "Vitamina D" },
    { code: "I100", name: "Eritropoyetina" },
    { code: "I101", name: "Antimulleriana" },
    { code: "I102", name: "Beta 2-Microglobulina" },
    { code: "I103", name: "Dengue" },
    { code: "I104", name: "Anti Smith" },
    { code: "I105", name: "Anticardiolipina IgM" },
    { code: "I106", name: "Anticardiolipina IgG" },
    { code: "I107", name: "Péptido C" },
    { code: "I108", name: "Prueba rápida de Chagas" },
    { code: "I109", name: "Prueba rápida de Chagas en mujeres embarazadas" },
    { code: "I110", name: "Determinación de marcador tumoral antígeno prostático específico libre (PSAI), método automatizado" },
    { code: "I111", name: "Determinación de Interferón GAMMA para Tuberculosis" },
    { code: "I112", name: "Determinación del virus Epstein-Barr, método automatizado (Ac IgM e IgG)" },
    { code: "I113", name: "Prueba confirmativa para Hepatitis B, Neutralizador de anticuerpos" },
    { code: "I114", name: "Prueba rápida Streptococo B en mujeres embarazadas" },
    { code: "I115", name: "Prueba rápida de malaria" },
  ] },
  { code: "M", name: "Bacteriología", tests: [
    { code: "M1", name: "Cultivo de secreción vaginal" },
    { code: "M2", name: "Secreción Uretral (Directo)" },
    { code: "M3", name: "Cultivo de Vibrio cholerae (TCBS, APA)" },
    { code: "M4", name: "Directo al Fresco" },
    { code: "M5", name: "Cultivo L.C.R." },
    { code: "M6", name: "Cultivo de semen" },
    { code: "M8", name: "Cultivo secreciones" },
    { code: "M9", name: "Cultivo secreción uretral" },
    { code: "M10", name: "Cultivo Haemophilus" },
    { code: "M11", name: "Cultivo Salmonella" },
    { code: "M12", name: "Cultivo Shigella" },
    { code: "M13", name: "Cultivo Bronquiales" },
    { code: "M14", name: "Cultivo nosocomial" },
    { code: "M15", name: "Cultivo control de calidad interno" },
    { code: "M16", name: "Cultivo líquido de derrame" },
    { code: "M17", name: "Coprocultivo" },
    { code: "M18", name: "Urocultivo" },
    { code: "M19", name: "Hemocultivo" },
    { code: "M20", name: "Cultivo de Exudado Faríngeo" },
    { code: "M22", name: "Coloración de Gram" },
    { code: "M24", name: "Antibiograma" },
    { code: "M26", name: "Directo de KOH" },
    { code: "M27", name: "Directo Giemsa (Histoplasma capsulatum)" },
    { code: "M28", name: "Directo Tinta China (Cryptococcus neoformans)" },
    { code: "M29", name: "Tipeo Salmonella" },
    { code: "M30", name: "Tipeo Shigella" },
    { code: "M31", name: "Tipeo Vibrio cholerae" },
    { code: "M32", name: "Prueba de ADA para TB" },
    { code: "M34", name: "Cultivo Campilobacter spp" },
    { code: "M35", name: "Cultivo otras bacterias" },
    { code: "M36", name: "Tipificación de TB" },
    { code: "M37", name: "Cultivo Micológico" },
    { code: "M38", name: "Cultivo Diagnóstico TBC" },
    { code: "M39", name: "Cultivo control TBC" },
    { code: "M40", name: "Baciloscopía 1a. Muestra SR" },
    { code: "M41", name: "Baciloscopía Control de tratamiento 1ra. Muestra" },
    { code: "M42", name: "Baciloscopía subsecuente segunda y tercera SR" },
    { code: "M43", name: "Búsqueda de espermatozoides" },
    { code: "M45", name: "Cultivo TBC diagnóstico extrapulmonar" },
    { code: "M46", name: "Cultivo LCR para TBC" },
    { code: "M47", name: "Pruebas de inocuidad a componentes sanguíneos" },
    { code: "M48", name: "Prueba sensibilidad TB" },
    { code: "M49", name: "Tipeo Neisseria meningitidis" },
    { code: "M50", name: "Control de Calidad indirecto de Baciloscopía (TBC)" },
    { code: "M51", name: "Baciloscopía para detección de Lepra (primera vez)" },
    { code: "M52", name: "Cultivo de Bordetella pertussis" },
    { code: "M54", name: "Prueba de Látex Bacteriológica" },
    { code: "M55", name: "Cultivo de Anaerobios" },
    { code: "M56", name: "Baciloscopía de control a pacientes de lepra" },
    { code: "M57", name: "Baciloscopía de lepra a contactos" },
    { code: "M58", name: "Control de calidad indirecto lepra" },
    { code: "M59", name: "Control de calidad externo micología/lepra" },
    { code: "M60", name: "Control de calidad Externo Bacteriología" },
    { code: "M61", name: "Identificación de Hongos Miceliales" },
    { code: "M62", name: "Identificación de Hongos Levaduriformes" },
    { code: "M63", name: "Tipeo de Haemophilus influenzae" },
    { code: "M64", name: "Tipeo de Bordetella pertussis" },
    { code: "M65", name: "Tipeo E. coli O157:H7" },
    { code: "M66", name: "Pruebas bioquímicas" },
    { code: "M67", name: "pH cultivos" },
    { code: "M68", name: "Cultivos Criterios Técnicos" },
    { code: "M69", name: "Detección mecanismos de resistencia" },
    { code: "M70", name: "Cultivo Neisseria meningitidis" },
    { code: "M71", name: "Cultivo Neisseria gonorrhoeae" },
    { code: "M72", name: "Cultivo Streptococcus pneumoniae" },
    { code: "M73", name: "Resiembra Bacteriana" },
    { code: "M74", name: "Control de calidad externo tuberculosis" },
    { code: "M75", name: "Control de calidad indirecto Vibrio cholerae" },
    { code: "M76", name: "Control de Calidad de Coloración de Baciloscopía" },
    { code: "M77", name: "Control de calidad a medios preparados TB" },
    { code: "M78", name: "Control de Calidad a Colorantes Preparados -TB" },
    { code: "M79", name: "Lectura de Tubos de Sensibilidad-TB" },
    { code: "M80", name: "Lectura de Control de Calidad -TB" },
    { code: "M81", name: "Lectura de Cultivos e Informe de Resultados-TB" },
    { code: "M82", name: "Subcultivos Cepas ATCC" },
    { code: "M83", name: "Subcultivos Cepas Leptospira" },
    { code: "M84", name: "Lectura (Campo Oscuro) de Subcultivos Leptospira" },
    { code: "M85", name: "Serotificación de Streptococcus pneumoniae" },
    { code: "M86", name: "Cultivo Escherichia coli O157:H7" },
    { code: "M87", name: "Cultivo Otros Vibrios" },
    { code: "M88", name: "Cultivo Aeromonas/Plesiomonas" },
    { code: "M89", name: "Cultivo Staphylococcus SSP" },
    { code: "M90", name: "Cultivo Otros Streptococcus" },
    { code: "M91", name: "Cultivo Brucella spp" },
    { code: "M92", name: "Cultivo Bacillus anthracis" },
    { code: "M93", name: "Cultivo Corynebacterium diphtheriae" },
    { code: "M94", name: "Cultivo Cromobacterium SSP" },
    { code: "M96", name: "Cultivo Cryptococcus sp" },
    { code: "M97", name: "Vaginosis Bacteriana" },
    { code: "M98", name: "Prueba rápida para detección de antígeno de Cryptococcus en líquidos biológicos" },
    { code: "M99", name: "Prueba rápida para la detección de antígenos de Micobacterias en muestras biológicas" },
    { code: "M100", name: "Coloración Ziehl-Neelsen - Micobacterias" },
    { code: "M101", name: "Resiembra - Micobacterias" },
    { code: "M102", name: "Cultivo Líquido - Micobacterias" },
    { code: "M103", name: "Resiembra de Hongos" },
    { code: "M104", name: "Pruebas especiales para Identificación de Hongos" },
    { code: "M105", name: "Coloración para Investigación de Hongos" },
    { code: "M106", name: "Baciloscopía Control de Calidad Indirecto Micobacterias" },
    { code: "M107", name: "Panel de Sepsis" },
    { code: "M108", name: "Panel de Sistema Nervioso Central" },
    { code: "M109", name: "Panel gastrointestinal" },
    { code: "M110", name: "Panel de Neumonía" },
    { code: "M111", name: "Panel Respiratorio (virus)" },
    { code: "M112", name: "Prueba rápida para detección de antígeno de Histoplasma capsulatum en líquido biológicos" },
    { code: "M113", name: "Prueba ELISA para detección de antígeno de Histoplasma capsulatum en líquidos biológicos" },
    { code: "M114", name: "Control de calidad Histoplasma capsulatum" },
    { code: "M115", name: "Control de calidad Cryptococcus sp." },
    { code: "M116", name: "Cultivo de aspirado de médula ósea" },
    { code: "M117", name: "Cultivo de tejido" },
    { code: "M118", name: "Cultivo de hueso" },
    { code: "M119", name: "Baciloscopía control de tratamiento 2da. muestra" },
    { code: "M120", name: "Cultivo de secreción vaginal" },
    { code: "M121", name: "Prueba de sensibilidad en medio líquido TB" },
  ] },
  { code: "P", name: "Parasitología", tests: [
    { code: "P1", name: "General de Heces" },
    { code: "P2", name: "Concentrado de Heces" },
    { code: "P3", name: "Sangre oculta en Heces" },
    { code: "P8", name: "Prueba de azul de metileno" },
    { code: "P9", name: "Cultivo Tripanosoma cruzi" },
    { code: "P10", name: "Cultivo Leishmania" },
    { code: "P11", name: "Directo Leishmania" },
    { code: "P12", name: "Recuento de huevos (Kato Katz)" },
    { code: "P13", name: "Coloración de Ziehl-Neelsen para Coccidios" },
    { code: "P14", name: "Sustancias reductoras en Heces" },
    { code: "P15", name: "pH en Heces" },
    { code: "P16", name: "Tinción tricrómica de Wheatley" },
    { code: "P17", name: "Directo de Heces en Chinches" },
    { code: "P18", name: "Control de Calidad indirecto Coccidios" },
    { code: "P20", name: "Control de Calidad Indirecto Gota Gruesa T. cruzi" },
    { code: "P21", name: "Control de Calidad PAM" },
    { code: "P22", name: "Control de Calidad externo Coprología" },
    { code: "P23", name: "Prueba de Montenegro" },
    { code: "P24", name: "Preservación y fijación de muestras fecales" },
    { code: "P28", name: "General de heces 1 perfil prenatal" },
    { code: "P29", name: "Control de calidad Internacional Parasitología" },
    { code: "P30", name: "Control indirecto de Leishmania spp - parasitología" },
    { code: "P31", name: "Prueba Rápida de Virus Gastrointestinales" },
  ] },
  { code: "Q", name: "Bioquímica", tests: [
    { code: "Q1", name: "Glucosa" },
    { code: "Q2", name: "Glucosa Post-Prandial" },
    { code: "Q3", name: "Curva de Tolerancia a la Glucosa" },
    { code: "Q4", name: "Ácido Úrico" },
    { code: "Q5", name: "Creatinina" },
    { code: "Q6", name: "Nitrógeno Uréico" },
    { code: "Q8", name: "Proteínas Totales" },
    { code: "Q9", name: "Albúmina" },
    { code: "Q10", name: "Colesterol" },
    { code: "Q11", name: "Colesterol Alta Densidad (HDL)" },
    { code: "Q12", name: "Colesterol Baja Densidad (LDL)" },
    { code: "Q13", name: "Triglicéridos" },
    { code: "Q15", name: "Bilirrubina Total" },
    { code: "Q16", name: "Hierro Sérico" },
    { code: "Q17", name: "Fijación y Captación de Hierro" },
    { code: "Q18", name: "Sodio" },
    { code: "Q19", name: "Potasio" },
    { code: "Q20", name: "Cloro" },
    { code: "Q21", name: "Magnesio" },
    { code: "Q22", name: "Calcio en Sangre" },
    { code: "Q23", name: "Fósforo en Sangre" },
    { code: "Q24", name: "Amoníaco" },
    { code: "Q26", name: "Transaminasa Glutámica Pirúvica (TGP)" },
    { code: "Q27", name: "Transaminasa Glutámica Oxalacética (TGO)" },
    { code: "Q28", name: "Fosfatasa Alcalina" },
    { code: "Q29", name: "Fosfatasa Alcalina Diferencial" },
    { code: "Q31", name: "Deshidrogenasa Láctica (LDH)" },
    { code: "Q32", name: "Creatinfosfoquinasa (CPK)" },
    { code: "Q33", name: "Amilasa en Sangre" },
    { code: "Q34", name: "Glucosa 6 Fosfatos Deshidrogenasa" },
    { code: "Q40", name: "Ácido Úrico en Orina" },
    { code: "Q41", name: "Amilasa en Orina" },
    { code: "Q42", name: "Calcio en Orina" },
    { code: "Q43", name: "Fósforo en Orina" },
    { code: "Q44", name: "Proteínas en Orina de 24 Horas" },
    { code: "Q45", name: "Depuración de Creatinina" },
    { code: "Q47", name: "Glucosa en Orina" },
    { code: "Q50", name: "Líquido Cefalorraquídeo (Citoquímico)" },
    { code: "Q51", name: "Líquido Amniótico" },
    { code: "Q52", name: "Proteínas en líquido de derrame" },
    { code: "Q53", name: "Electroforesis de proteínas" },
    { code: "Q57", name: "Test de APT/Hemoglobina fetal" },
    { code: "Q59", name: "Citoquímico líquido de derrame (líquido peritoneal)" },
    { code: "Q60", name: "Cristalización de helechos" },
    { code: "Q61", name: "Gases sanguíneos (arteriales)" },
    { code: "Q64", name: "Electrolitos en sudor" },
    { code: "Q65", name: "Globulinas" },
    { code: "Q66", name: "Bilirrubina directa" },
    { code: "Q68", name: "Na en Orina" },
    { code: "Q69", name: "Creatinina en Orina" },
    { code: "Q70", name: "K en Orina" },
    { code: "Q71", name: "Dosificación de Fenobarbital" },
    { code: "Q72", name: "Dosificación de Fenitoína" },
    { code: "Q73", name: "Dosificación de Teofilina" },
    { code: "Q74", name: "Dosificación de Cortisol" },
    { code: "Q75", name: "Insulina" },
    { code: "Q78", name: "Ácido Valproico" },
    { code: "Q79", name: "Digoxina" },
    { code: "Q82", name: "Control de Calidad Externo Química Clínica" },
    { code: "Q84", name: "Lactato" },
    { code: "Q85", name: "Ferritina" },
    { code: "Q86", name: "Vitamina B-12" },
    { code: "Q87", name: "Folatos" },
    { code: "Q88", name: "Ciclosporina" },
    { code: "Q89", name: "Hormona del Crecimiento" },
    { code: "Q90", name: "Estradiol" },
    { code: "Q91", name: "Carbamazepina" },
    { code: "Q92", name: "Fósforo en Orina de 24 Horas" },
    { code: "Q93", name: "Magnesio en Orina" },
    { code: "Q94", name: "Nitrógeno Uréico en Orina" },
    { code: "Q95", name: "Proteínas en Orina de 12 Horas" },
    { code: "Q96", name: "Microproteína" },
    { code: "Q97", name: "Cloro en Orina" },
    { code: "Q98", name: "Nitrógeno Uréico en Orina de 24 Horas" },
    { code: "Q99", name: "Calcio en Orina de 24 Horas" },
    { code: "Q100", name: "Proteínas en Orina" },
    { code: "Q101", name: "Sodio en Orina de 24 Horas" },
    { code: "Q102", name: "Potasio en Orina de 24 Horas" },
    { code: "Q103", name: "Electrolitos Na, K, Cl" },
    { code: "Q105", name: "CA 125" },
    { code: "Q106", name: "Alfa Feto Proteínas" },
    { code: "Q107", name: "Test SULIBAN (Tamizaje en glucosa)" },
    { code: "Q108", name: "Hemoglobina Glicosilada" },
    { code: "Q109", name: "Creatinina en Orina de 24 Horas" },
    { code: "Q110", name: "Creatinina en Orina de 12 Horas" },
    { code: "Q111", name: "Gamma Glutamil Transferasa" },
    { code: "Q112", name: "Lipasa" },
    { code: "Q113", name: "CK-MB" },
    { code: "Q114", name: "Troponina (Medición Nivel Cardíaco)" },
    { code: "Q115", name: "Glucosa para embarazada" },
    { code: "Q116", name: "Colinesterasa sérica" },
    { code: "Q117", name: "Prueba de Litio" },
    { code: "Q118", name: "Cistatina C" },
    { code: "Q119", name: "Propéptido Natriurético de tipo beta N-Terminal (proBNP/NT-proBNP)" },
    { code: "Q120", name: "Procalcitonina" },
    { code: "Q121", name: "Transferrina" },
    { code: "Q122", name: "Deshidrogenasa Láctica (LDH) en otros fluidos" },
    { code: "Q123", name: "Glucosa otros líquidos" },
    { code: "Q124", name: "Proteína otros líquidos" },
    { code: "Q125", name: "Cloro en Orina de 24 Horas" },
    { code: "Q126", name: "Magnesio en Orina de 24 Horas" },
    { code: "Q127", name: "Ácido Úrico en Orina de 24 Horas" },
    { code: "Q128", name: "Glucosa 1 perfil prenatal" },
    { code: "Q129", name: "Glucosa 2 perfil prenatal" },
    { code: "Q130", name: "Test o SULLIVAN perfil prenatal" },
    { code: "Q131", name: "Glucosa 3 perfil prenatal" },
    { code: "Q132", name: "Curva de Tolerancia a la Insulina" },
    { code: "Q133", name: "Insulina Post Prandial" },
    { code: "Q134", name: "Tacrolimus" },
    { code: "Q135", name: "Colesterol en Líquidos" },
    { code: "Q136", name: "Triglicéridos en Líquidos" },
    { code: "Q137", name: "Microalbúmina en Orina de 24 Horas" },
    { code: "Q138", name: "Magnesio en Orina de 12 Horas" },
    { code: "Q139", name: "Creatinina en Líquidos" },
    { code: "Q140", name: "Electrolitos en Líquidos (Na, K, Cl)" },
    { code: "Q141", name: "Deshidrogenasa Láctica (LDH) en Líquidos de 12 Horas" },
    { code: "Q142", name: "Deshidrogenasa Láctica (LDH) en Líquidos de 24 Horas" },
    { code: "Q143", name: "Citoquímico de Líquido Ascítico" },
    { code: "Q144", name: "Citoquímico de Líquido Pleural" },
    { code: "Q145", name: "Citoquímico de Líquido Sinovial" },
    { code: "Q146", name: "Glucosa Post Almuerzo" },
    { code: "Q147", name: "Análisis de Líquidos de Diálisis Peritoneal" },
    { code: "Q148", name: "Panel de Biomarcadores Rápidos Código Infarto" },
    { code: "Q153", name: "Prueba para la Determinación de Niveles de Vancomicina" },
    { code: "Q154", name: "Hemoglobina Glicosilada y Variantes Patológicas (HPLC)" },
  ] },
  { code: "S", name: "Banco de Sangre", tests: [
    { code: "S1", name: "Clasificación del Grupo Sanguíneo y Rh" },
    { code: "S4", name: "Coombs Directo" },
    { code: "S5", name: "Coombs Indirecto" },
    { code: "S6", name: "Prueba Cruzada" },
    { code: "S7", name: "Prueba Du" },
    { code: "S8", name: "Aglutinación en Frío (Crioaglutininas)" },
    { code: "S10", name: "Aglutininas Anti Rh" },
    { code: "S12", name: "Prueba rápida de Hepatitis B otros grupos" },
    { code: "S15", name: "Prueba rápida de VIH otros grupos A1" },
    { code: "S21", name: "Hepatitis C Donantes" },
    { code: "S22", name: "Prueba rápida de Hepatitis C otros grupos" },
    { code: "S29", name: "Hepatitis B donantes" },
    { code: "S33", name: "Identificación de Anticuerpos Irregulares" },
    { code: "S34", name: "Fenotipo a Glóbulos Rojos" },
    { code: "S35", name: "Concentrado de Plaquetas Desplasmatizadas" },
    { code: "S36", name: "Crioprecipitados Desplasmatizados" },
    { code: "S41", name: "Prueba rápida de VIH 3 perfil prenatal" },
    { code: "S42", name: "VIH en Pacientes TB" },
    { code: "S43", name: "Hepatitis aguda tipo A (Pacientes)" },
    { code: "S44", name: "Control de Calidad indirecto de Hepatitis B" },
    { code: "S45", name: "Control de calidad indirecto de Hepatitis C" },
    { code: "S46", name: "Prueba confirmatoria Hepatitis B" },
    { code: "S47", name: "Prueba confirmatoria Hepatitis C" },
    { code: "S48", name: "Control de calidad indirecto Chagas (BS)" },
    { code: "S49", name: "Chagas otros grupos" },
    { code: "S50", name: "Confirmación VIH" },
    { code: "S51", name: "Pruebas serológicas para evaluación de kit comercial" },
    { code: "S52", name: "Control de calidad externo Hepatitis B" },
    { code: "S53", name: "Control de calidad externo Hepatitis C" },
    { code: "S54", name: "Control de calidad externo Chagas (BS)" },
    { code: "S55", name: "Control de calidad externo VIH" },
    { code: "S56", name: "Clasificación grupo sanguíneo y Rh para embarazada" },
    { code: "S57", name: "Prueba rápida de VIH 1 perfil prenatal" },
    { code: "S58", name: "Prueba rápida de VIH 2 perfil prenatal" },
    { code: "S59", name: "Control de calidad indirecto de VIH" },
    { code: "S60", name: "Control de Calidad Internacional Inmunohematología" },
    { code: "S61", name: "Control de Calidad Interno de Hepatitis B" },
    { code: "S62", name: "Control de Calidad Interno de Hepatitis C" },
    { code: "S63", name: "Control de Calidad Interno de T. cruzi" },
    { code: "S64", name: "Control de Calidad Interno VIH" },
    { code: "S65", name: "Prueba de incidencia de VIH" },
    { code: "S66", name: "Prueba Rápida Hepatitis B Embarazada (sospecha clínica)" },
    { code: "S67", name: "Prueba Rápida Hepatitis C Embarazada (sospecha clínica)" },
    { code: "S68", name: "Prueba rápida Hepatitis B en usuarios VICTS" },
    { code: "S69", name: "Prueba rápida Hepatitis C en usuarios VICTS" },
    { code: "S70", name: "Clasificación grupo sanguíneo 1 perfil prenatal (manual)" },
    { code: "S71", name: "Clasificación grupo sanguíneo automatizado 1 perfil prenatal" },
    { code: "S72", name: "Hemograma automatizado para donantes" },
    { code: "S73", name: "Clasificación grupo sanguíneo y Rh automatizado" },
    { code: "S74", name: "Prueba rápida de VIH confirmación A2" },
    { code: "S75", name: "Prueba rápida de VIH confirmación A3" },
    { code: "S76", name: "Prueba rápida Dual VIH/Sífilis" },
    { code: "S77", name: "Retesteo diagnóstico de VIH" },
    { code: "S78", name: "Prueba Cuádruple para la Detección de Sífilis y Virus de VIH, Hepatitis B y Hepatitis C" },
    { code: "S79", name: "Prueba confirmatoria Chagas en embarazada" },
  ] },
  { code: "U", name: "Urianálisis", tests: [
    { code: "U1", name: "General de orina" },
    { code: "U2", name: "Concentración, dilución de orina" },
    { code: "U3", name: "Proteínas en orina (cualitativa)" },
    { code: "U4", name: "Albúmina en orina" },
    { code: "U5", name: "Investigación de Gramoxone" },
    { code: "U6", name: "pH urinario" },
    { code: "U7", name: "Células naranja" },
    { code: "U8", name: "Orinas criterios técnicos" },
    { code: "U9", name: "Proteína de Bence Jones" },
    { code: "U10", name: "General de orina para embarazada" },
    { code: "U11", name: "Prueba rápida para detección cualitativa de múltiples drogas y sus metabolitos en muestras biológicas" },
    { code: "U12", name: "General de orina 1 perfil prenatal" },
    { code: "U13", name: "General de orina 2 perfil prenatal" },
    { code: "U14", name: "General de orina 3 perfil prenatal" },
  ] },
  { code: "T", name: "Toma de Muestra", tests: [
    { code: "T1", name: "Toma de Muestra Dengue" },
    { code: "T2", name: "Toma de Muestra Hisopado IRAS" },
    { code: "T3", name: "Toma de Muestra Leptospirosis" },
    { code: "T4", name: "Toma de Muestra Rubéola" },
    { code: "T5", name: "Toma de Muestra Sarampión" },
    { code: "T6", name: "Toma de Muestra Plomo" },
    { code: "T7", name: "Toma de Muestra Vitamina A" },
    { code: "T8", name: "Toma de Muestra Carga Viral" },
    { code: "T9", name: "Toma de Muestra CD4 - CD8" },
    { code: "T10", name: "Toma de Muestra Chagas Crónico" },
    { code: "T11", name: "Toma de Muestra Hepatitis B" },
    { code: "T12", name: "Toma de Muestra Hepatitis C" },
    { code: "T13", name: "Toma de Muestra para Laboratorio Clínico" },
    { code: "T14", name: "Toma de Muestra Tosferina" },
    { code: "T15", name: "Toma de Muestra Bacteriológica" },
    { code: "T16", name: "Toma de Muestra Hisopado Rectal" },
    { code: "T17", name: "Toma de Muestra de Saliva para Evaluación de Composición Corporal por Técnicas Isotópicas" },
    { code: "T18", name: "Número de Personas Atendidas en Laboratorio" },
    { code: "T19", name: "Toma de Muestras Hisopado COVID" },
    { code: "T20", name: "Toma de Muestra Micología" },
    { code: "T21", name: "Toma de Muestra Parasitología" },
    { code: "T22", name: "Toma de Muestra Histoplasma capsulatum" },
    { code: "T23", name: "Toma de Muestra Cryptococcus sp." },
    { code: "T24", name: "Toma de Muestra Carga Viral VIH DBS" },
    { code: "T25", name: "Toma de Muestra Carga Viral VIH PPT" },
    { code: "T26", name: "Toma de Muestra PCR para ITS Neisseria gonorrhoeae, Virus del Papiloma Humano y Herpes Simple." },
  ] },
  { code: "BM", name: "Biología Molecular", tests: [
    { code: "BM1", name: "Subtipificación Dengue" },
    { code: "BM2", name: "Subtipificación Influenza" },
    { code: "BM3", name: "Genotipificación Rotavirus" },
    { code: "BM4", name: "Identificación Leptospira" },
    { code: "BM5", name: "Genotipificación Norovirus" },
    { code: "BM6", name: "Identificación Leishmania" },
    { code: "BM7", name: "Carga Viral VIH" },
    { code: "BM8", name: "RT-PCR Rubéola" },
    { code: "BM9", name: "RT-PCR Sarampión" },
    { code: "BM10", name: "PCR Tiempo Real TB Gene X Pert MTB/Rif" },
    { code: "BM11", name: "Extracción Ácidos Nucleicos - Bacter" },
    { code: "BM12", name: "Preparación Mezcla/Amplificación - Bacter" },
    { code: "BM13", name: "Preparación y Carga del Gel - Bacter" },
    { code: "BM14", name: "Extracción Ácidos Nucleicos - Flu/Den" },
    { code: "BM15", name: "Preparación Mezcla Amplificación - Flu/Den" },
    { code: "BM16", name: "Preparación y Carga del Gel - Flu/Den" },
    { code: "BM17", name: "Extracción Ácidos Nucleicos S/R-Lepto" },
    { code: "BM18", name: "Preparación Mezcla/Amplificación S/R-Lepto" },
    { code: "BM19", name: "Preparación y Carga del Gel S/R-Lepto" },
    { code: "BM20", name: "Identificación Bordetella pertussis" },
    { code: "BM21", name: "Tipificación Virus Polio" },
    { code: "BM22", name: "Genotipificación VIH" },
    { code: "BM23", name: "Identificación de Vibrio cholerae" },
    { code: "BM24", name: "RT-PCR VCHIK" },
    { code: "BM25", name: "Ensayo PCR para la detección de ADN para Virus Herpes 1/2 (PCR)" },
    { code: "BM26", name: "Ensayo de PCR para Chlamydia trachomatis" },
    { code: "BM27", name: "Ensayo de PCR para Neisseria gonorrhoeae" },
    { code: "BM28", name: "Ensayo de hibridación para Virus del Papiloma Humano (VPH)" },
    { code: "BM29", name: "RT-PCR VZIKA" },
    { code: "BM30", name: "RT-PCR Virus Respiratorio No Flu" },
    { code: "BM31", name: "RT-PCR Dengue" },
    { code: "BM32", name: "Carga Viral Hepatitis B" },
    { code: "BM33", name: "Carga Viral Hepatitis C" },
    { code: "BM34", name: "RT-PCR SARS-CoV-2" },
    { code: "BM35", name: "Extracción de Ácidos Nucleicos Micología" },
    { code: "BM36", name: "Preparación de Mezclas Micología" },
    { code: "BM37", name: "Amplificación de Ácidos Nucleicos - Micología" },
    { code: "BM38", name: "Identificación de Candida auris" },
    { code: "BM39", name: "Ensayo de PCR para Virus del Papiloma Humano (VPH)" },
    { code: "BM40", name: "Prueba de PCR para Viruela Símica" },
    { code: "BM41", name: "Secuenciación de SARS-CoV-2" },
    { code: "BM42", name: "Secuenciación de Dengue" },
    { code: "BM43", name: "Secuenciación de Influenza" },
    { code: "BM44", name: "Proceso de preparación de librerías en secuenciación por muestra preparada" },
    { code: "BM45", name: "Asignación de código de identificación de secuencia" },
    { code: "BM46", name: "Determinación de concentración de ácidos nucleicos y macromoléculas" },
    { code: "BM47", name: "Lavado químico pre, post y durante el proceso de secuenciación" },
    { code: "BM48", name: "Ingreso de datos a sistemas digitales" },
    { code: "BM49", name: "Control de calidad de secuencias genómicas FASTQ o similar" },
    { code: "BM50", name: "Determinación de mutaciones genómicas" },
    { code: "BM51", name: "Análisis filogenético" },
    { code: "BM52", name: "PCR Tiempo Real TB XPERT/XDR" },
    { code: "BM53", name: "PCR de Shigella spp / E. coli Enteroinvasiva (EIEC)" },
    { code: "BM54", name: "PCR de Campylobacter spp" },
    { code: "BM55", name: "PCR de Yersinia enterocolitica" },
    { code: "BM56", name: "PCR de Vibrio spp" },
    { code: "BM57", name: "PCR de Clostridium difficile toxina B" },
    { code: "BM58", name: "PCR de Aeromonas spp" },
    { code: "BM59", name: "PCR de Salmonella spp" },
    { code: "BM60", name: "PCR de Rotavirus A" },
    { code: "BM61", name: "PCR de Norovirus" },
    { code: "BM62", name: "PCR de Adenovirus F Humano" },
    { code: "BM63", name: "PCR de Sapovirus" },
    { code: "BM64", name: "PCR de Astrovirus" },
    { code: "BM65", name: "Carga Viral Xpert HIV-1" },
    { code: "BM66", name: "ARN Cualitativo VIH" },
    { code: "BM67", name: "Enteroagregativo E. coli (EAEC)" },
    { code: "BM68", name: "Enteropatogénico E. coli (EPEC)" },
    { code: "BM69", name: "Enterotoxigénico E. coli (ETEC) lt/st" },
    { code: "BM70", name: "Shiga-like toxin-producing E. coli (STEC) stx1/stx2" },
    { code: "BM71", name: "E. coli O157" },
    { code: "BM72", name: "Plesiomonas shigelloides" },
    { code: "BM73", name: "Cryptosporidium" },
    { code: "BM74", name: "Cyclospora cayetanensis" },
    { code: "BM75", name: "Entamoeba histolytica" },
    { code: "BM76", name: "Giardia lamblia" },
  ] },
  { code: "V", name: "Virología", tests: [
    { code: "V1", name: "Cultivo Virus Respiratorios" },
    { code: "V2", name: "Cultivo Virus Dengue" },
    { code: "V3", name: "IFA Indirecta Dengue" },
    { code: "V4", name: "IFA Directa Dengue" },
    { code: "V5", name: "IFA Virus Respiratorios" },
    { code: "V6", name: "IFA Encefalitis Equina Venezolana" },
    { code: "V7", name: "Anticuerpos Virus del Nilo" },
    { code: "V8", name: "ELISA Captura Fiebre Amarilla" },
    { code: "V9", name: "Anticuerpos IgG Sarampión" },
    { code: "V10", name: "Anticuerpos IgM Rubéola" },
    { code: "V11", name: "Anticuerpos IgG Rubéola" },
    { code: "V12", name: "ELISA Rotavirus" },
    { code: "V13", name: "ADN Proviral VIH" },
    { code: "V14", name: "Anticuerpos para Dengue IgM" },
    { code: "V15", name: "Anticuerpos para Sarampión IgM" },
    { code: "V16", name: "Inmunofluorescencia Rabia" },
    { code: "V17", name: "Prueba rápida Influenza A y B" },
    { code: "V18", name: "Inoculación Intracraneal en Ratones" },
    { code: "V20", name: "Lectura Láminas Control Rabia" },
    { code: "V21", name: "Lectura de Spot IFI-Flu" },
    { code: "V22", name: "Subcultivos Línea Celular-Flu" },
    { code: "V23", name: "Prueba Rápida Adenovirus" },
    { code: "V24", name: "Anticuerpos IgM Parvovirus Humano B19" },
    { code: "V25", name: "Controles Internos Sarampión" },
    { code: "V26", name: "Controles Internos Rubéola" },
    { code: "V27", name: "Cultivo Virus Polio" },
    { code: "V28", name: "Prueba Rápida Detección Antígeno Dengue NS1" },
    { code: "V29", name: "Prueba Rápida Anticuerpos IgM Dengue" },
    { code: "V30", name: "Prueba Rápida Anticuerpos IgG Dengue" },
    { code: "V31", name: "ELISA IgM V-CHIK" },
    { code: "V32", name: "ELISA Captura IgM V-CHIK" },
    { code: "V33", name: "ELISA IgM V-ZIKA" },
    { code: "V34", name: "Mantenimiento de línea celular virus respiratorios" },
  ] },
  { code: "PR", name: "LNR - Preparaduría", tests: [
    { code: "PR1", name: "Preparación de Láminas con Antígeno - T. cruzi" },
    { code: "PR2", name: "Placas Preparadas con Medio Cultivo - Bacter" },
    { code: "PR3", name: "Preparación de Láminas con Polilisina - Flu" },
    { code: "PR4", name: "Tubos Preparados con Mtv - Flu" },
    { code: "PR5", name: "Tubos Preparados con Medio Cultivo - Flu" },
    { code: "PR6", name: "Tubos Preparados de Medio de Cultivo con y Sin Droga - TB" },
    { code: "PR7", name: "Tubos Preparados con Medio Cultivo - Bacter" },
    { code: "PR8", name: "Tubos Preparados Cary Blair - Bacter" },
    { code: "PR9", name: "Tubos Preparados con Medio Cultivo - Parasitología" },
    { code: "PR10", name: "Tubos Preparados con Medio Cultivo EMJH - S/R" },
    { code: "PR11", name: "Tubos Preparados con Mtv - Rotavirus" },
    { code: "PR12", name: "Tubos Preparados con Mtv - S/R-Lepto" },
    { code: "PR13", name: "Tubos Preparados con Medio Cultivo - Micología" },
    { code: "PR14", name: "Preparación Reactivos/Buffers Flu-Dengue" },
    { code: "PR15", name: "Preparación de Soluciones, Sales - TB" },
    { code: "PR16", name: "Preparación de Reactivos - Buffer S/R-Lepto" },
    { code: "PR17", name: "Preparación Suplemento AFAS - S/R-Lepto" },
    { code: "PR18", name: "Preparación de Colorantes - Preparaduría" },
    { code: "PR19", name: "Preparación de Soluciones Porcentuales - Preparaduría" },
    { code: "PR20", name: "Preparación Buffer - Preparaduría" },
    { code: "PR21", name: "Llenado Galerías Miniaturizadas" },
    { code: "PR22", name: "Llenado Tarjetas Automatizadas" },
    { code: "PR23", name: "Montaje de Muestras (Diluciones en Microplaca) - Leptospira" },
    { code: "PR24", name: "Identificación, registro y alicuotamiento de sueros - Den/Flu" },
    { code: "PR25", name: "Identificación, registro y alicuotamiento de sueros - S/R-Lepto" },
    { code: "PR26", name: "Identificación, registro y alicuotamiento de sueros - Serología" },
    { code: "PR27", name: "Identificación, registro y alicuotamiento de sueros - VIH" },
    { code: "PR28", name: "Identificación, registro y alicuotamiento de sueros - Banco de Sangre" },
    { code: "PR29", name: "Identificación, registro y alicuotamiento de muestras - Rotavirus" },
    { code: "PR30", name: "Identificación, registro y alicuotamiento de cepas bacterianas" },
    { code: "PR31", name: "Identificación, registro y alicuotamiento de muestras de hongos" },
    { code: "PR32", name: "Identificación, registro, desembalaje y alicuotamiento de muestras - Parasitología" },
    { code: "PR33", name: "Preparación de Láminas Control - Rabia" },
    { code: "PR34", name: "Preparación de Reactivos - Rabia" },
    { code: "PR35", name: "Producción de Reactivos - Bacter" },
    { code: "PR36", name: "Preparación de Reactivos - Micología (KOH)" },
    { code: "PR37", name: "Preparación patrón Escala McFarland" },
    { code: "PR38", name: "Preparación de Panel de Proficiencia - Micobacterias" },
    { code: "PR39", name: "Preparación de Panel de Control de Calidad - Parasitología" },
    { code: "PR40", name: "Preparación de Panel de Control de Calidad - Bacteriología" },
    { code: "PR41", name: "Identificación, Registro y Alicuotamiento de Muestras - Micobacterias" },
    { code: "PR42", name: "Placas preparadas con medio de cultivo - Micología" },
  ] },
];

// Filas fijas del tabulador de resultados (mismas para toda prueba).
export const LAB_RESULTADO_ROWS: string[] = ["1. Normal", "2. Negativo", "3. Anormal", "4. Positivo", "5. Muestra Inadecuada", "6. Otros", "7. Reactivo", "8. Indeterminado", "9. No Reactivo"];
export const LAB_PROCEDENCIA_ROWS: string[] = ["1. Consulta Externa", "2. Hospitalización", "3. Emergencia", "4. Referido", "5. Otros"];
