// AUTO-GENERADO desde "TABULADOR DIARIO DE NUTRICION_ALIMENTACIÓN.xlsx" (hoja MES ACTUAL).
// Tabulador SEPS de Nutricion (Departamento de Nutricion), servicio "alimentacion-y-dieta".
// La Interconsulta se aplano a filas VO/NE · 1ª VEZ/SEG (1 columna por dia).
import type { SepsTemplate } from "@/lib/seps-templates";

export const NUTRICION_TEMPLATE: SepsTemplate = {
  serviceId: "alimentacion-y-dieta",
  establishment: "HOSPITAL NACIONAL EL SALVADOR",
  tables: [
    {
      id: "nut_lorena",
      title: "Tabulador diario de Nutrición/Alimentación",
      subtitle: "Responsable: Licda. Lorena Patricia Barrientos de García",
      detailLabel: "Servicio / Unidad",
      rows: [
        { key: "nut_lorena_13", label: "MEZCL.", group: "MEDICINA INTERNA" },
        { key: "nut_lorena_14", label: "PCTE.", group: "MEDICINA INTERNA" },
        { key: "nut_lorena_15", label: "MEZCL.", group: "CIRUGIA GENERAL" },
        { key: "nut_lorena_16", label: "PCTE.", group: "CIRUGIA GENERAL" },
        { key: "nut_lorena_17", label: "MEZCL.", group: "HOSPITALIZACIÓN SERVICIOS POR CONVENIOS" },
        { key: "nut_lorena_18", label: "PCTE.", group: "HOSPITALIZACIÓN SERVICIOS POR CONVENIOS" },
        { key: "nut_lorena_19", label: "MEZCL.", group: "UCI" },
        { key: "nut_lorena_20", label: "PCTE.", group: "UCI" },
        { key: "nut_lorena_21", label: "MEZCL.", group: "UCIN" },
        { key: "nut_lorena_22", label: "PCTE.", group: "UCIN" },
        { key: "nut_lorena_23", label: "MEZCL.", group: "EMERGENCIA" },
        { key: "nut_lorena_24", label: "PCTE.", group: "EMERGENCIA" },
        { key: "nut_lorena_25", label: "MEZCL.", group: "UNIDAD DE CUIDADOS ESPECIALES" },
        { key: "nut_lorena_26", label: "PCTE.", group: "UNIDAD DE CUIDADOS ESPECIALES" },
      ],
    },
    {
      id: "interconsulta",
      title: "Alimentación y Dietas — Interconsulta",
      subtitle: "Responsable: Licda. Debora Marisol Lopez Granados",
      detailLabel: "Servicio / Unidad",
      rows: [
        { key: "interconsulta_38_1ª ", label: "VO · 1ª VEZ", group: "MEDICINA INTERNA" },
        { key: "interconsulta_38_SEG", label: "VO · SEG.", group: "MEDICINA INTERNA" },
        { key: "interconsulta_39_1ª ", label: "NE · 1ª VEZ", group: "MEDICINA INTERNA" },
        { key: "interconsulta_39_SEG", label: "NE · SEG.", group: "MEDICINA INTERNA" },
        { key: "interconsulta_40_1ª ", label: "VO · 1ª VEZ", group: "CIRUGIA GENERAL" },
        { key: "interconsulta_40_SEG", label: "VO · SEG.", group: "CIRUGIA GENERAL" },
        { key: "interconsulta_41_1ª ", label: "NE · 1ª VEZ", group: "CIRUGIA GENERAL" },
        { key: "interconsulta_41_SEG", label: "NE · SEG.", group: "CIRUGIA GENERAL" },
        { key: "interconsulta_42_1ª ", label: "VO · 1ª VEZ", group: "HOSPITALIZACIÓN SERVICIOS POR CONVENIOS" },
        { key: "interconsulta_42_SEG", label: "VO · SEG.", group: "HOSPITALIZACIÓN SERVICIOS POR CONVENIOS" },
        { key: "interconsulta_43_1ª ", label: "NE · 1ª VEZ", group: "HOSPITALIZACIÓN SERVICIOS POR CONVENIOS" },
        { key: "interconsulta_43_SEG", label: "NE · SEG.", group: "HOSPITALIZACIÓN SERVICIOS POR CONVENIOS" },
        { key: "interconsulta_44_1ª ", label: "VO · 1ª VEZ", group: "UCI" },
        { key: "interconsulta_44_SEG", label: "VO · SEG.", group: "UCI" },
        { key: "interconsulta_45_1ª ", label: "NE · 1ª VEZ", group: "UCI" },
        { key: "interconsulta_45_SEG", label: "NE · SEG.", group: "UCI" },
        { key: "interconsulta_46_1ª ", label: "VO · 1ª VEZ", group: "UCIN" },
        { key: "interconsulta_46_SEG", label: "VO · SEG.", group: "UCIN" },
        { key: "interconsulta_47_1ª ", label: "NE · 1ª VEZ", group: "UCIN" },
        { key: "interconsulta_47_SEG", label: "NE · SEG.", group: "UCIN" },
        { key: "interconsulta_48_1ª ", label: "VO · 1ª VEZ", group: "EMERGENCIA" },
        { key: "interconsulta_48_SEG", label: "VO · SEG.", group: "EMERGENCIA" },
        { key: "interconsulta_49_1ª ", label: "NE · 1ª VEZ", group: "EMERGENCIA" },
        { key: "interconsulta_49_SEG", label: "NE · SEG.", group: "EMERGENCIA" },
        { key: "interconsulta_50_1ª ", label: "VO · 1ª VEZ", group: "UNIDAD DE CUIDADOS ESPECIALES" },
        { key: "interconsulta_50_SEG", label: "VO · SEG.", group: "UNIDAD DE CUIDADOS ESPECIALES" },
        { key: "interconsulta_51_1ª ", label: "NE · 1ª VEZ", group: "UNIDAD DE CUIDADOS ESPECIALES" },
        { key: "interconsulta_51_SEG", label: "NE · SEG.", group: "UNIDAD DE CUIDADOS ESPECIALES" },
      ],
    },
    {
      id: "dietas_asistidas",
      title: "Alimentación y Dietas — Dietas asistidas",
      subtitle: "Responsable: Licda. Karla Georgina Rolin Villanueva",
      detailLabel: "Servicio / Unidad",
      rows: [
        { key: "dietas_asistidas_67", label: "MEDICINA INTERNA" },
        { key: "dietas_asistidas_68", label: "HOSPITALIZACION CIRUGIA GENERAL" },
        { key: "dietas_asistidas_69", label: "HOSPITALIZACIÓN SERVICIOS POR CONVENIOS" },
        { key: "dietas_asistidas_70", label: "Unidad de Cuidados Intensivos" },
        { key: "dietas_asistidas_71", label: "Unidad de Cuidados Intermedios" },
        { key: "dietas_asistidas_72", label: "EMERGENCIAS" },
        { key: "dietas_asistidas_73", label: "UNIDAD DE CUIDADOS ESPECIALES" },
        { key: "dietas_asistidas_74", label: "DIALISIS PERITONEAL" },
        { key: "dietas_asistidas_75", label: "TERAPIA SANGUINEA" },
      ],
    },
    {
      id: "racion1",
      title: "Alimentación y Dietas — Ración 1",
      detailLabel: "Servicio / Unidad",
      rows: [
        { key: "racion1_90", label: "MEDICINA INTERNA" },
        { key: "racion1_91", label: "HOSPITALIZACION CIRUGIA GENERAL" },
        { key: "racion1_92", label: "HOSPITALIZACIÓN SERVICIOS POR CONVENIOS" },
        { key: "racion1_93", label: "Unidad de Cuidados Intensivos" },
        { key: "racion1_94", label: "Unidad de Cuidados Intermedios" },
        { key: "racion1_95", label: "EMERGENCIAS" },
        { key: "racion1_96", label: "UNIDAD DE CUIDADOS ESPECIALES" },
        { key: "racion1_97", label: "DIALISIS PERITONEAL" },
        { key: "racion1_98", label: "TERAPIA SANGUINEA" },
        { key: "racion1_99", label: "TEST DE GUSS" },
      ],
    },
    {
      id: "nut_jessica",
      title: "Tabulador diario de Nutrición/Alimentación",
      subtitle: "Responsable: Licda. Jessica Tatiana Artiga Ortiz",
      detailLabel: "Servicio / Unidad",
      rows: [
        { key: "nut_jessica_114", label: "MEZCL.", group: "MEDICINA INTERNA" },
        { key: "nut_jessica_115", label: "PCTE.", group: "MEDICINA INTERNA" },
        { key: "nut_jessica_116", label: "MEZCL.", group: "CIRUGIA GENERAL" },
        { key: "nut_jessica_117", label: "PCTE.", group: "CIRUGIA GENERAL" },
        { key: "nut_jessica_118", label: "MEZCL.", group: "HOSPITALIZACIÓN SERVICIOS POR CONVENIOS" },
        { key: "nut_jessica_119", label: "PCTE.", group: "HOSPITALIZACIÓN SERVICIOS POR CONVENIOS" },
        { key: "nut_jessica_120", label: "MEZCL.", group: "UCI" },
        { key: "nut_jessica_121", label: "PCTE.", group: "UCI" },
        { key: "nut_jessica_122", label: "MEZCL.", group: "UCIN" },
        { key: "nut_jessica_123", label: "PCTE.", group: "UCIN" },
        { key: "nut_jessica_124", label: "MEZCL.", group: "EMERGENCIA" },
        { key: "nut_jessica_125", label: "PCTE.", group: "EMERGENCIA" },
        { key: "nut_jessica_126", label: "MEZCL.", group: "UNIDAD DE CUIDADOS ESPECIALES" },
        { key: "nut_jessica_127", label: "PCTE.", group: "UNIDAD DE CUIDADOS ESPECIALES" },
      ],
    },
    {
      id: "nut_martha",
      title: "Tabulador diario de Nutrición/Alimentación",
      subtitle: "Responsable: Licda. Martha Nohelmy Perez de Nolasco",
      detailLabel: "Servicio / Unidad",
      rows: [
        { key: "nut_martha_138", label: "MEZCL.", group: "MEDICINA INTERNA" },
        { key: "nut_martha_139", label: "PCTE.", group: "MEDICINA INTERNA" },
        { key: "nut_martha_140", label: "MEZCL.", group: "CIRUGIA GENERAL" },
        { key: "nut_martha_141", label: "PCTE.", group: "CIRUGIA GENERAL" },
        { key: "nut_martha_142", label: "MEZCL.", group: "HOSPITALIZACIÓN SERVICIOS POR CONVENIOS" },
        { key: "nut_martha_143", label: "PCTE.", group: "HOSPITALIZACIÓN SERVICIOS POR CONVENIOS" },
        { key: "nut_martha_144", label: "MEZCL.", group: "UCI" },
        { key: "nut_martha_145", label: "PCTE.", group: "UCI" },
        { key: "nut_martha_146", label: "MEZCL.", group: "UCIN" },
        { key: "nut_martha_147", label: "PCTE.", group: "UCIN" },
        { key: "nut_martha_148", label: "MEZCL.", group: "EMERGENCIA" },
        { key: "nut_martha_149", label: "PCTE.", group: "EMERGENCIA" },
        { key: "nut_martha_150", label: "MEZCL.", group: "UNIDAD DE CUIDADOS ESPECIALES" },
        { key: "nut_martha_151", label: "PCTE.", group: "UNIDAD DE CUIDADOS ESPECIALES" },
      ],
    },
    {
      id: "racion2",
      title: "Alimentación y Dietas — Ración 2",
      detailLabel: "Servicio / Unidad",
      rows: [
        { key: "racion2_162", label: "Radiologia" },
        { key: "racion2_163", label: "Unidad de conservacion y mantenimiento" },
      ],
    },
  ],
};
